apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: educs-backend-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./secrets/backend-secrets.yml
