apiVersion: batch/v1
kind: CronJob
metadata:
  name: k3supdater-cron
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: k3supdater
            args:
            - update
            - --repo-owner=cguertin14
            - --repo-name=k3s-ansible-ha
            - --group-vars-filepath=inventory/cluster/group_vars/all.yml