apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: argo-rollouts-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: argo-rollouts
  endpoints:
  - port: metrics