apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:C+Bd8r7Snu2qhuwCjOsQPqyRs3uXZsy1gRSKyU410Z8GFCpiAAsK52ru2Cj2yU6cx7Yd3HtcQqU=,iv:Iyvhukar9Rm5/GxfcZDMZya/8lX1FBgU4R9YF/+2lDo=,tag:wizb/v5ze2wMtYArV2bypg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-27T02:59:19Z"
    mac: ENC[AES256_GCM,data:2jwe0so/dcjY3Z+K7WWkMAVaSzWaYXKDhI6ZWqMsFUMD3RfhjiHCSOsBeN/QhIeTpw+0tL2awGe2VqvToZNjQziySMmI5SmJlnJRd3YGstbc8k0O1gX9ajwlXNThgijvM275PHkz4Abk426Jnx5/fsbXvkuPGPJTmGi1IoFfly0=,iv:fhXtdAwa3TKAnGcnCa4nfy+a9amQMJwCCFlCakCksq4=,tag:Cm+42dKE6f363v0rwGAtHQ==,type:str]
    pgp:
        - created_at: "2021-03-27T02:59:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf+PFEclYs2BZawLhL4Z/cP1j49OwEoAJ/FOukjFTAOFMSi
            Yj6D9KxQ2K8cIInOJ6n3WupKiLaxGhNX4AcrCFq/qzR1/8tpzkvV4QR47wiAG/oF
            8gKRQJRgmzqhAcpvtq1ASyfwE2OaNydKFUt3ux1cL4g+vu0TyDONlIQSbhHvY9Ay
            UIg4aRWWql/n/DrYJ80c9+FuW1vyB6esTqQHMdCSeABEEXEAaRjh+jeoGv6aT8Ag
            KFr7+Ti3heGCOMil7L6T44hcInTGBylC4stdEVDjBEsvOmTQ8xMFaiEF3EKRQ7M0
            z0Y+aVfmMmtuMOCayHdcFBgZxvhFTfn72DlgkQQbHNJeAc+dRKn8epHp7Bg+p+Mp
            Ug6X6szhU2FWbhuk2uod54CxiLPk1Pgl88FwqasN85Tnm0n7zPhBDUpkkh9hu0vk
            I6idgWnHxSM5jXl02viZ/G8/BJlqOPcezU17m3qFMw==
            =BuZe
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2021-03-27T02:59:19Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/XodwdRDfSAwz/rCyj10Sxksmx3MHmakGW2ln5WjW4qiJ
            04OpK4x9GHD43gLmZmBo/AkpL+2//y0MmHqlXk+clVPxff/FEapLDMw2UpgzDmoU
            LN4Zwk0P6JGXkx0d1WQcnWyZdOb14DW3fdlA+l1zCq9DTNffnVf5Lq5QrVvCfd6o
            WZxmaM676VyGfI8RfjdLRuOWhi4B1ip+uuEWPKmCao3PV6ye8l1d99mJ1kQLX6/Z
            CruE+QF2YLET/oJfChNS3sz9pzvr4lQRmhproK3wPip3Rk7M2esHbbl2PAqO6w3s
            D0OIaUhano96LCQA83NJtPj/9TrtPfb9rHwl06PfNNJeAcqOiY6nJGZIeMC1wYzl
            IivYNMjVM9Gk0cY57BtrANZ7Lcl5eVPWZvaex7RUV+0VgUQzyEJrN8Y6cHMZpmrb
            VYE3KykmkDl1N6hMNWs5e74rIjn/l+87m4SYTOEGNg==
            =jA4y
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
