apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-api-token-secret
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:3mbzozWYndptJE87clHfVsVw4qlpsjW8DQjXYYBAV1eV0otWnUpaly/kWH/QTbcZlXozhkIJz3w=,iv:bNXycnu+en7dd0Ozm9JdJT8pEe6r33t3lSWI/XvDy+M=,tag:CIStuqlAtQ+cud8OlH+bDw==,type:str]
sops:
    lastmodified: "2023-04-20T05:47:42Z"
    mac: ENC[AES256_GCM,data:510bD3xiFjEhmYAdfTFdehL4rfkPp1g9bz/jX91iLFHvqUgTcBwAOPIh2yPDyQfrAjB9yMF307JeNeVF5OWWIVJuWuROHc+4YuooR8cwIWL7Pindc7DhH4MW6mYlqwOO3nU/zmMCHTvwHWQYf59Ca52p34rQ2Br/UJdhG+eJvYM=,iv:sn+Zjlr578JWtlrkONg3vhzwfCEimboz1T1ZrIJDH/Y=,tag:pDpBMG02P9RTx5Jq62/CdA==,type:str]
    pgp:
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv/fK3Of/7goepaTu6EkJ++FzqDkRg3UEwHJrgFhA3KZ1vc
            GMfUO65yXGSoDgj3OFUmQI37e/4FQdA6ATjJ7GOtv+zLrxmROizgtBmQhNa5CRKe
            wjFdPWqX7/cN/iwvH9C9kxId9ZmY/lH3+ZDguj3GymzdtQnPmC9j6LTyyo2XY+jS
            olz5AQXcxMdkRwT56GRXnDgEziMTtq/Q/AzQtDCVuTc8m0UxLBaQn+uFW8t6hDBZ
            sSbqmBkXMQpaEyEze+wgxD8k2LEpcvqEupPsUEKeqCWmQ2Jc4oNxZYGrAvdYmyEx
            zdkvDtxMpBxdt8DZY4F6/EciXKgXLSPu0NsPCkn0/kFwQA2GG8OSSEoA7BMFAxai
            amB13IMwDGJbQ5NVYcbfs7W/suK6As15IpDm2jQ59QeS319ytFLB0ufwrDeF84Dy
            fvPlj39QJi0gm4e4XLeTUAeqaIi4mh1XCGjGQB3V2OnYGAnNu4321O3QGrkEzm42
            ySWHEYnnPxRSeZ48zAQW0l4B/IEeJl+7uVsu24uMh8fVDM8ChnEJZamxNRMRt13J
            BU0pbR24QTQMz4enwz4dlKPNAmcA7gO2QOEN8tqB0oy5lQSi5eVxCsj8kiE6iTjv
            oD495q6s+TRnBkNCGEhl
            =ySfe
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAiHEkDDz1USMSbJbXjmlO3rspMosog3BbDcwLa/uuIhKf
            H90B3HZLOU6+tIfZ6UnH5C9R7mrPHt0qZRoRVI08l9DxUrT7QJi1lUpzncVZcv56
            soAnmEd+HgzfruI1fYmgOjYUMgG9XnlZxxRSCpGTZF/tALTF8XLCW8kkg9WGPw46
            zEvloX6yFeDfrnWnECbFcwTVr8bo2dpJYl8iRgUGESK5erk14QLFtNL2IRgn84EG
            LgWFAWUdledefKHme4A8UR8FF168KcV1WMk4w8HNdKg3DpUrbWEjqnxiCXcDY3Le
            dACIf3CBHxb/F4h5boqz38J1Gs0pEaLYOm0I8ykvkdJeAdnbf5u3fN5ApW9pyqSj
            XMujsBFSnb6dZgha3JAORpnHmmTgwstx8u0tg8L02GdhpDxXBZsDptnk6HloM5Gt
            ylTnG3cXu9u5r2Dl6qvvKHYdJTpIfkoyPVyOr6xp/w==
            =9sly
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
