apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:ujQfEYbhIBeBgJPXjsDHYAlrHAl88TBPI96ORca6ceLq,iv:to+F31IJ59U8xb5Jply8S8aK0pLd3JM3NJCi0OLz5XI=,tag:MBOXPZ82+f4akCaFIIaONA==,type:str]
    namespace: cert-manager
type: Opaque
data:
    api-token: ENC[AES256_GCM,data:RK9CKBwMfHNK+50CZ28joaeb/iXt/U2qnsn9RQTV87HkvdJl+zYRdmBW6dGH5M1pNxGFqsXJR20=,iv:bRdfxk5AaJRWGrmXdPo9H6MYOaA02xX34juqJveYims=,tag:C6O7WvU63oFfkTUabdky+w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-02-19T16:34:49Z"
    mac: ENC[AES256_GCM,data:zHQiQa4mqe/TnWsMtIZekoZ+PIkMLW8hyFc8rLzZfSKZbjnetnet2v8oNu0M2VIhb7jb+JBGbfZZUsYijvMuUjg+FwcRIVs3Tyx5nrQO1aCUEWBGi4/Hm5C8hMkRMud7UtO2PdWmiT26qeezOPIB17ZTljozWsGjIS1oVPElqPk=,iv:urDukOnhG/B7p9RM0cw1bbMx4hdoUTswXIHtV9GYuCE=,tag:AriXg4DZ1i83Q/Qk7jRfSw==,type:str]
    pgp:
        - created_at: "2025-02-19T16:34:49Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/Xgi1vca0PuC+8/RnpIjkknfEeJPNIKAGnSSal3N8T3EQ
            FcMu+pApnjOwUp1xlb1UBZLVdT9ApbUb3jK7Ys9BmKrVLsA5PcL3znC/TiJskBqf
            xYbPV02AFjGLn5trKIlFa85SjRiaSGqmm3pn+5sqbozY+tuVSK0LpRYjt89LuZ1/
            UVnmNOGWy2fajcyMK85E8CT7DxfplKFwk+DGWezXzasjKB5JG2ZF0SqBfPlQ4Bz3
            MA41iNRcd204ImoD26ETwNM/u+fIl92Xg/NMKcIQ+fV9xolhIzR+LQcETXPLk4O3
            jaHoRqY0uI5TegEXt2194Dk7xEoX6KA34WjqabK7j9JeAQZ73cYaKD7JuxITlS0o
            XYVVFDl5BZvF6vXv7jezeFLPxHm17mQYJ3ATL4bfVR83ML6YwF6NM1Xa8QBLLEv8
            1INgyv43czySLDd8jQVyHF9MTugGQJshb9MHBGwAsQ==
            =T0Z/
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
