apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: node-agent
  namespace: velero-backups
spec:
  template:
    spec:
      containers:
      - name: node-agent
        command:
        - /velero
        args:
        - node-agent
        - server
        - --features=EnableCSI
        - --node-agent-configmap=node-agent-config