apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/cguertin14/ddns/manifests?ref=v1.6.2

configMapGenerator:
- name: app-config
  behavior: replace
  literals:
  - ZONE_NAME=cguertin.dev
  - RECORD_NAME=lb

generators:
- secrets-generator.yml
