apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: blog

commonLabels:
  app.kubernetes.io/name: blog

resources:
- ../../base
- ingresses.yml

images:
- name: cguertz/cguertin.dev
  newTag: v1.1.6

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml
