apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
- resources/namespace.yml
- resources/ca-issuer.yml
- resources/webhook-issuer.yml
- resources/service-monitor.yml

generators:
- secrets-generator.yml

helmCharts:
- name: linkerd2
  repo: https://helm.linkerd.io/stable
  version: 2.11.2
  releaseName: linkerd2
  namespace: linkerd
  includeCRDs: true
  valuesFile: resources/linkerd-values.yml