apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: linkerd

resources:
- resources/namespace.yml
- resources/ca-issuer.yml
- resources/webhook-issuer.yml

generators:
- resources/helm-chart.yml
- secrets-generator.yml