kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

## About the arm64v8.2 mongo errors:
#
# NEW ERROR WHEN RUNNING `mongod` on v7.0.4: Illegal instruction (core dumped)
# discussion: https://www.mongodb.com/community/forums/t/raspberrypi-4-8gb-docker-entrypoint-sh-27-illegal-instruction-core-dumped/132518/3
# solution: https://github.com/cguertin14/mongodb-raspberrypi-docker
resources:
- operator-rbac.yml

generators:
- secrets-generator.yml

patchesStrategicMerge:
- patches/replicaset.yml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: educs
    app.kubernetes.io/name: mongodb
