kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

## About the arm64v8.2 mongo errors:
#
# NEW ERROR WHEN RUNNING `mongod` on v7.0.4: Illegal instruction (core dumped)
# discussion: https://www.mongodb.com/community/forums/t/raspberrypi-4-8gb-docker-entrypoint-sh-27-illegal-instruction-core-dumped/132518/3
# solution: https://github.com/cguertin14/mongodb-raspberrypi-docker

resources:
- https://github.com/mongodb/mongodb-kubernetes-operator/config/rbac?ref=v0.9.0

images:
- name: ghcr.io/cguertin14/mongodb-backup-s3
  newTag: v1.1.4

# Comment if restore enabled.
configMapGenerator:
- literals:
  - MONGODB_HOST=educs-mongodb-0.educs-mongodb-svc.mongodb,educs-mongodb-1.educs-mongodb-svc,educs-mongodb-2.educs-mongodb-svc
  - MONGODB_PORT=27017
  # - INIT_BACKUP=true
  # Uncomment if need to restore DB.
  - INIT_RESTORE=true
  name: mongodb-backups-config

generators:
- secrets-generator.yml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: educs
    app.kubernetes.io/name: mongodb
