kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

# NOTE: for upgrades, refer to https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
helmCharts:
- includeCRDs: true
  name: community-operator
  releaseName: mongodb
  repo: https://mongodb.github.io/helm-charts
  version: 0.9.0

images:
- name: ghcr.io/cguertin14/mongodb-backup-s3
  newTag: v1.1.4

# Comment if restore enabled.
configMapGenerator:
- literals:
  - MONGODB_HOST=educs-mongodb-0.educs-mongodb-svc.mongodb,educs-mongodb-1.educs-mongodb-svc,educs-mongodb-2.educs-mongodb-svc
  - MONGODB_PORT=27017
  # - INIT_BACKUP=true
  # Uncomment if need to restore DB.
  - INIT_RESTORE=true
  name: mongo-backups-config

generators:
- secrets-generator.yml

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: educs
    app.kubernetes.io/name: mongodb
