apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to download/copy custom binaries into the emptyDir
      initContainers:
      - name: install-ksops
        # Match Argo CD Go version
        image: viaductoss/ksops
        command: ["/bin/sh", "-c"]
        args:
        - echo "Installing KSOPS...";
          mv ksops /custom-tools;
          mv $GOPATH/bin/kustomize /custom-tools/;
          echo "Done.";
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Volume mount the custom binary to the bin directory (overriding the existing version)
      containers:
      - name: argocd-repo-server
        env:
        - name: XDG_CONFIG_HOME
          value: /.config
        - name: ARGOCD_RECONCILIATION_TIMEOUT
          valueFrom:
            configMapKeyRef:
              name: argocd-cm
              key: timeout.reconciliation
              optional: false
        volumeMounts:
        - mountPath: /usr/local/bin/kustomize
          name: custom-tools
          subPath: kustomize
        - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops/ksops
          name: custom-tools
          subPath: ksops
        - mountPath: /.config/kustomize/plugin/viaduct.ai/v1/ksops-exec/ksops-exec
          name: custom-tools
          subPath: ksops