apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      volumes:
      - name: gnupg-home
        emptyDir: {}
      - name: deploy-gpg-key
        secret:
          secretName: deploy-gpg-key
      initContainers:
      - name: import-gpg-key
        image: alpine
        command: ["/bin/sh", "-c", "apk install gpg --update --no-cache && gpg --import /deploy-gpg-key/deploy-key.asc"]
        env:
        - name: GNUPGHOME
          value: /gnupg-home/.gnupg
        volumeMounts:
        - mountPath: /deploy-gpg-key
          name: deploy-gpg-key
          readOnly: true
        - mountPath: /gnupg-home
          name: gnupg-home
      containers:
      - name: argocd-repo-server
        env:
        - name: GNUPGHOME
          value: /home/argocd/.gnupg
        volumeMounts:
        - mountPath: /home/argocd/.gnupg
          name: gnupg-home
          subPath: .gnupg