apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-cm
  namespace: argocd
data:
  admin.enabled: 'false'
  url: https://gitops.k8s.cguertin.dev
  repositories: |
    - url: https://github.com/cguertin14/infra
  repository.credentials: |
    - url: https://github.com/cguertin14/infra
      passwordSecret:
        name: repo-access
        key: password
      usernameSecret:
        name: repo-access
        key: username
  dex.config: |
    connectors:
    - type: github
      id: github
      name: GitHub
      config:
        clientID: $dex.github.clientId
        clientSecret: $dex.github.clientSecret
        orgs:
        - name: homelab-infra
  resource.customizations: |
    extensions/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
    networking.k8s.io/Ingress:
      health.lua: |
        hs = {}
        hs.status = "Healthy"
        return hs
  kustomize.buildOptions: "--enable-alpha-plugins"