apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-server
spec:
  template:
    spec:
      containers:
      - name: argocd-server
        command:
        - --insecure
        - --staticassets
        - /shared/app
        - --redis
        - argocd-redis-ha-haproxy:6379