apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:q+4KKU7Es/qbRhVIK735IiOTeeKUYnCqU9M4JQ==,iv:6DaTeP5f0gJMrXAYLjAV6jKVjWt38OboAhmI5SvBnQ4=,tag:bggJ5sf68+G3NaqBfoiTxw==,type:str]
    namespace: monitoring
type: Opaque
stringData:
    username: ENC[AES256_GCM,data:vnfwsPw1qg==,iv:foodB6HN2jPLSpxqfAviQrfn3aTvuyfTKBGfhGefnhc=,tag:6yEQ2URblsc+nkQLGYkLtA==,type:str]
    password: ENC[AES256_GCM,data:AFiul+1FVHZlRn6K7Kz+E5lw2+SXkaWHCbDtyyxF8sitUlPU+9RDcEytGDQ=,iv:r218m80ujxbrqQn2YD1QoQwUzskTxUSZFUn4f8xrnXE=,tag:tO5ml7roveFNpU7f6UjIag==,type:str]
sops:
    lastmodified: "2026-08-20T20:32:58Z"
    mac: ENC[AES256_GCM,data:MmXb2RV6MWqvF5xHt4Y1B8f0WgEFspyGNeoFDzmKGQ8t3LoTUQLECXDGnK0uRDxPc9SQ6MIlxv2jWWUwCa5Ht6wH3BhSwH0niQXKNcn9oYKYL8oheddXxQZx2ZK5Oa5qxOmCVJUU2uJFEXc3+SjWHONknVKMjamxwUrudwN1dgU=,iv:RvPcIjjiD7j2tw+sDjQKzYLO1lYvpS7jlqB8fhdfAxI=,tag:1k8YQNSDePXz5b6xqcMb+w==,type:str]
    pgp:
        - created_at: "2026-08-20T20:32:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+KPlxYzAwVkXjLwTKhoK5jpShh3dEySHLlDtKP0TnTM/1
            3g5aSxTpUFfqPK42fFhee1HzsEUP12zJwhDuZtKvy00dVSEqsMv9A3Jm12Pg9NQy
            oC+4HUIs37wE2GvSKsFPE5F/nQtC1Xiwd2QG4a5Tz1DkRcCb50fpv7xyXep6Kugs
            JSO/Tqda0T9mF11/+UAS3ZtTWeSRUXTSQhPR6vHL9GwUNgaKwHiu/lLdCHthLA6Y
            /M+qoHT26+u97btiTYGEtR12CASYG2EV3ISYxPqiny+bTdWvYzZ3yZh+89zlb52E
            nRa/8RXTZ1/+jCYLT9+BAxLuzXSO1M8o8xUM5ZHmmtJeAZ/brl7+0tP/E0PwDnzu
            vC+UMi+prOSriO4EKcyWTj2Xc/gi4+Ir1h05U6vmm25Mmd5/z3AAawc6rZffY87Q
            IRY8JXcCufWxkl0zDKLeeVJMNJ9cnLyL28LhnbjaBw==
            =An0x
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-08-20T20:32:57Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv/Txbyb9sny3TKQG/oni/BsrfZJ9nKqqUw3ksEUQqdPdvr
            Rhe0p1L+oa7x5ovwqoHoyQQmAX71SHPAz7Sn4kZ4jlNSa+X5uQN826x56cfRRJOt
            SiahJPHmLWLSaQhEX2iDhlPr1saFoD1d+P3K5VMW1Uz9zncyRcZnNhvqvAYKRGPk
            fv5o+Nwoo2tzMULhJGiJh+sX4ZE07jLyo3kcfW24OKeV5JmwTbPpIOaVqC9QCHXk
            L7AOj5d13Mm623rtecyNQ9m/8bOTZHPCO5+K+V8KUFfpeNpDaS5Sqjjc3qXiG8hx
            +HKG474o0L62aYmS/XvN8ukFdIfZXICtrAOhlOOx/V9OivpESgBc+U8fZOiI24dj
            LTh1ZphDU8dMLxxwMQWdM3r9hMaEB480Z322CAAFDzYTl0bSgUwRc+RUlpph8rhZ
            mtFzCU8zYk41BGUGdmPqgolut4t9i68y+Lt+ZpOtpgXrg54MxkXJwy6ncYEyrx6i
            WqBKUNhBHKI19E2SHHwz0l4BexNXKb6btsqI5MOyvgbdcRjGi4Spj/SUtOVXwXAn
            wME+g+A6uaEh0vJ0MEhIUeTdI7SpRebo043gHvQXITe1irk9aJmtIv83JaXxiTTC
            u9LsB6XqvQX+Wi4shBTi
            =RLYr
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
