apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: mongodb-operator

# NOTE: for upgrades, refer to https://github.com/mongodb/mongodb-kubernetes-operator/blob/master/docs/install-upgrade.md
helmCharts:
- name: community-operator
  namespace: mongodb-operator
  releaseName: mongodb
  includeCRDs: true
  repo: https://mongodb.github.io/helm-charts
  version: 0.13.0
  valuesInline:
    operator:
      watchNamespace: "*"

resources:
- namespace.yml