{
 "title": "Blog - Service Level Objectives (SLOs)",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "DS_PROMETHEUS", "query": "prometheus" }
  ]
 },
 "panels": [
  {
   "title": "Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[SLO] Availability % 28d",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(sum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) - (sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) or vector(0))) / sum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))"
    }
   ]
  },
  {
   "title": "Time Envoy served != 5xx in last 28d",
   "type": "gauge",
   "description": "For a 99.9% slo, Envoy is allowed to be down for 40.32 minutes in a 28 days period",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (\n(sum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) - (sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) or vector(0)))\n/\nsum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n)) * 60 * 60 * 24 * 14"
    }
   ]
  },
  {
   "title": "Error budget spent in 28d",
   "type": "gauge",
   "description": "Error budget percentage consumed",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\n(sum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) - (sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d])) or vector(0)))\n/\nsum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n)) / 0.001"
    }
   ]
  },
  {
   "title": "Error budget spent in range",
   "type": "gauge",
   "description": "Error budget percentage consumed",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\n(sum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[$__range])) - (sum(rate(envoy_cluster_upstream_rq_xx{envoy_response_code_class=\"5\", envoy_cluster_name=~\"httproute/blog/.*\"}[$__range])) or vector(0)))\n/\nsum(rate(envoy_cluster_upstream_rq_completed{envoy_cluster_name=~\"httproute/blog/.*\"}[$__range]))\n)) / 0.001"
    }
   ]
  },
  {
   "title": "Requests Status Code Seen from Envoy",
   "type": "piechart",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (envoy_response_code) (increase(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/blog/.*\"}[$__range])) > 0",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "requests / seconds displayed by HTTP Code seen from Envoy",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum by(envoy_response_code) (rate(envoy_cluster_upstream_rq{envoy_cluster_name=~\"httproute/blog/.*\"}[$__rate_interval]))",
     "legendFormat": "{{envoy_response_code}}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "targets": [
    {}
   ]
  },
  {
   "title": "[SLO] Latency % 28d",
   "type": "gauge",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "sum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"500.0\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n/\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"+Inf\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))",
     "legendFormat": " "
    }
   ]
  },
  {
   "title": "Time Envoy is under SLO in the last 28d",
   "type": "gauge",
   "description": "For a 99.5% slo, Envoy is allowed to be under slo for 201 minutes in a 14 days period",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "(1 - (\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"500.0\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n/\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"+Inf\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n)) * 60 * 60 * 24 * 14"
    }
   ]
  },
  {
   "title": "Error budget spent in 28d",
   "type": "gauge",
   "description": "Error budget percentage consumed",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"500.0\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n/\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"+Inf\", envoy_cluster_name=~\"httproute/blog/.*\"}[28d]))\n)) / 0.005"
    }
   ]
  },
  {
   "title": "Error budget spent in range",
   "type": "gauge",
   "description": "Error budget percentage consumed",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - (\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"500.0\", envoy_cluster_name=~\"httproute/blog/.*\"}[$__range]))\n/\nsum(rate(envoy_cluster_upstream_rq_time_bucket{le=\"+Inf\", envoy_cluster_name=~\"httproute/blog/.*\"}[$__range]))\n)) / 0.005"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "heatmap",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "targets": [
    {
     "expr": "sum by (le) (increase(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/blog/.*\"}[$__rate_interval]))",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Latency Percentiles",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.999, sum by(le)(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/blog/.*\"}[$__rate_interval]))) / 1000",
     "legendFormat": "99.9 percentile"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/blog/.*\"}[$__rate_interval])) by(le)) / 1000",
     "legendFormat": "95 percentile"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/blog/.*\"}[$__rate_interval])) by(le)) / 1000",
     "legendFormat": "90 percentile "
    }
   ]
  },
  {
   "title": "Count of request by latency bucket",
   "type": "bargauge",
   "gridPos": { "h": 10, "w": 24, "x": 0, "y": 35 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum by (le) (increase(envoy_cluster_upstream_rq_time_bucket{envoy_cluster_name=~\"httproute/blog/.*\"}[$__range]))",
     "legendFormat": "{{le}}"
    }
   ]
  }
 ]
}