{
 "title": "Machine Temperatures",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "amd64 nodes temps now",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"x86_pkg_temp\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "arm64 nodes temps now",
   "type": "gauge",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "node_thermal_zone_temp{type=\"cpu-thermal\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "amd64 temps over time",
   "type": "timeseries",
   "description": "Temperatures over time per instance.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_thermal_zone_temp{type=\"x86_pkg_temp\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "arm64 temps over time",
   "type": "timeseries",
   "description": "Temperatures over time per instance.",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "sum by (instance) (node_thermal_zone_temp{type=\"cpu-thermal\"})",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "amd64 stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 21 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min_over_time(node_thermal_zone_temp{type=\"x86_pkg_temp\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(node_thermal_zone_temp{type=\"x86_pkg_temp\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max_over_time(node_thermal_zone_temp{type=\"x86_pkg_temp\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "arm64 stats",
   "type": "table",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 21 },
   "repeat": "datasource",
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "min_over_time(node_thermal_zone_temp{type=\"cpu-thermal\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "avg_over_time(node_thermal_zone_temp{type=\"cpu-thermal\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    },
    {
     "expr": "max_over_time(node_thermal_zone_temp{type=\"cpu-thermal\"}[${__range_s}s])",
     "legendFormat": "{{instance}}"
    }
   ]
  }
 ]
}