apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-machine-learning
spec:
  template:
    spec:
      containers:
      - name: immich-machine-learning
        resources:
          limits:
            nvidia.com/gpu: 1 # Request 1 GPU