apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  app.kubernetes.io/name: logging

resources:
- resources/namespace.yml
- resources/metrics-rbac.yml
- resources/promtail-rules.yml
- resources/promtail-metrics.yml

helmCharts:
###
## Loki deployment
#
- name: loki
  includeCRDs: true
  releaseName: loki
  version: 2.10.2
  repo: https://grafana.github.io/helm-charts
  namespace: logging
  valuesFile: resources/helm-values-loki.yml

###
## Promtail deployment
#
- name: promtail
  includeCRDs: true
  releaseName: promtail
  version: 3.11.0
  repo: https://grafana.github.io/helm-charts
  namespace: logging
  valuesFile: resources/helm-values-promtail.yml