apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

commonLabels:
  app.kubernetes.io/name: logging

resources:
- namespace.yml

helmCharts:
###
## Loki deployment
#
- name: loki
  includeCRDs: true
  releaseName: loki
  version: 2.10.1
  repo: https://grafana.github.io/helm-charts
  namespace: logging
  valuesInline:
    replicas: 3
    config:
      common:
        replication_factor: 3
      compactor:
        retention_enabled: true
    persistence:
      enabled: true
      storageClassName: nfs-client
      accessModes:
      - ReadWriteOnce
      size: 200Gi

###
## Promtail deployment
#
- name: promtail
  includeCRDs: true
  releaseName: promtail
  version: 3.11.0
  repo: https://grafana.github.io/helm-charts
  namespace: logging
  valuesInline:
    loki:
      serviceName: loki
    config:
      lokiAddress: http://loki.logging.svc:3100/loki/api/v1/push