apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ingress.yml
- service.yml
- pdb.yml
- deployment.yml

generators:
- secrets-generator.yml

images:
- name: ghcr.io/cguertin14/educs-backend
  newTag: v3.3.2

replicas:
- count: 3
  name: educs-backend

configMapGenerator:
- literals:
  - NODE_ENV=production
  - PORT=80
  - URL=https://erabliereducoeursucre.com
  - NODE_OPTIONS=--max-old-space-size=1024
  - LOG_LEVEL=info
  name: backend-config

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/name: educs-backend
