apiVersion: v1
kind: Secret
metadata:
    name: mongo-backups-secrets
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:VGEgZcGf1t+/c1McB/GGY6J8AOdmQdtsbGJYtQ==,iv:9+yDy2ofyE6r9/v0nX0+nyVgwfo2+OuBgEuvyPNo76Q=,tag:oEPxPMXAMTQTqRZni0ZUsA==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:oOIKgMr83uQ2RCV1tHHXJXD/EiOYz6+cFReQSppKcHyDPrO9OMD79BAx0nZ7inLBDuQOfdYCew4=,iv:uZBh+diDEpKEKagufeLXqijA/2JrXfuRcd8Nq87sRAI=,tag:GnlGmuKdx6AR5jIzF/zQkQ==,type:str]
    BUCKET: ENC[AES256_GCM,data:DkIvxPElCShL7DdBtA0v9eAFK8WnK918Qr7GP9PsmdE=,iv:Vfn5CtxJUyJA+XMXc96J8+dx8lVPU1MII4YagylbauA=,tag:YQ0tqG4jim2VNCi9qmP94w==,type:str]
    REGION: ENC[AES256_GCM,data:nUIjjuH2JEKQ5pBf,iv:1/AMjBFcNfFxJSd15bqa8T0YdI/wIksPb6dLxOp6SeY=,tag:TglONUDHaiU7hLpsn8n+bg==,type:str]
    BACKUP_FOLDER: ENC[AES256_GCM,data:ynjVotzfv8gFpgOYHcu2MVjQBR+JBBOz,iv:SmykgMMo0H5/rIZ1o7FiwEapgdxuNOc90F8oIe2jKho=,tag:dMIwqrv5HPIIZMPAbyRz7w==,type:str]
    MONGODB_DB: ENC[AES256_GCM,data:nRIVTU3ArdRmMfF2XChoP05bklu6W1sJ3gfK5A==,iv:V+gW6zobm6elrdknXCXczD68v1pWeaCiw0xUByfQ4yc=,tag:NigEdlKFCMMIDj8Hxec+SA==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-18T23:15:13Z"
    mac: ENC[AES256_GCM,data:F7ejn0q5uph0iEjfxc2TMjCvjoEPLHk3sX5k1ApIWNLxesL9NCGPwAglLurKLqnkIr37U6P0TI9UhHaKvna7gB23pa0hvHrpaerdC4kmPJl65QBeuTTmFyO0MPReCZsjEsAjol8vICU64UAFYTmQ1XwcqdgR1uxCuIttbaILQf0=,iv:8n0x0O66L4VgopXoSl3xwZGSxJne8vilPox7dJB90mg=,tag:ZvuC1ExEsnTiKI43cFRUFQ==,type:str]
    pgp:
        - created_at: "2023-04-18T23:15:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf/ZwR9PuTRnBh75b3bgNTVBOcLj6MeI6gqr1xZq+cVDmwM
            6guCQ1aN/t90DJBRwUw0Uq8+37Cekalmx3xICKkfgKvEW8es/9AW9B5xVwlBbDuD
            9rociN1FzZm8kibIlZk3/6o+GUR03s15HqA9OnV1jRghOUusS5/4Hw2h8kFW+bWK
            Fa3v1PygjK9AdIlSSbLl5H6fJ4yE4FcYUErDQ026FspESJdaxee2bF/LxBMLj6gB
            XJbTMSEORdM705LGon0Z8IolDL+ujZrXKI/lRMK09BAIryO3W+3fU0fUTyIlIzFY
            XlOJkye8xRuYzuEn5knr2wiSs+i9saEfhj4f6DgmKdJcAf2RrgmmZgo+VZZejXED
            fo/ibvBPeSxmSzMWO+hXwemGGeuaveVF4uMkxjvB2tYGL8FAsW6ldN6Sr02Pk3tl
            jOZABKoscM5YFOKGrmu+t67pL9mgTj6jbQbEvrs=
            =jypS
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2023-04-18T23:15:12Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/cEZDE4HBGNaL6g0RsQ9DXQqHwiqS7QuDU2wpa3aSW62b
            Ht8D//HjIkEbP0mcUS44JCHWsD8Ct1N+O6N++I4gzlK1qrkV/1qT+h4lKr8+CnrY
            C21xcuZxZuTXs0mtMndt8XGOBSDvlCYZxBGjUX/+dBP2vTF8a+T3PJ3uhJw6PDEB
            1TeyYzE+DkQF4s16hJWGuEuYs1gwoExDSFS3lFgVBU9SOqBfaniL2/ZBpR5AOhKU
            KJvt0o3qPcpu1SqQsaFE1MQV7rk62HB9936yL6CwP8dA9Z4WRhmyuB14CyrXpOMA
            +ol19Knf6rviK/hg/ktd993WMQwb79RwDxZd1lp+n9JcAZ9QNDSz0ebgvC3LUdZl
            yaHg/zObcDbnA0N2S8D8ehLmXKaC/6iBDf/ldf9XO6Hnwxf2iH7j1xkZN5htsg6p
            Vtw6pMdwvTfuHMgpXwn/ZyI8QnhDuIH9LONlDL0=
            =XFGJ
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
