apiVersion: v1
kind: Secret
metadata:
    name: mongo-backups-secrets
type: Opaque
data:
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:pbssaLtezTHfPVHb8R0J+P/rhX41rdaDLhk79g==,iv:WiiLvhEpTiWsOi6ApHKPr+HApCekBUcSDsVIi1l3EsU=,tag:6VVj+5foK7B8AsY7Q+G8Kw==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:wIAHuSIXuVuh9J7K9vCWTfINUdG5/395sl4b2pppCEiWEftc8lq0CvnIhhkclnRMSsxmEh5bE/8=,iv:MX2+NtnZDtKUkl3jxAm8cOUFvdNyG9TpzDU1MYroJaU=,tag:DK2gjX5BD7+r2eJAsrEgyw==,type:str]
    BUCKET: ENC[AES256_GCM,data:1B6UxPZUgH804+unPRHjGDrEHThT7361Y+fNqF3a99o=,iv:X1hyuNmMmqFeG1QosfDI+b2WJlJIjuwtNl4tke3qTM0=,tag:7z7ALPnpUfBxiR0WgQFaPw==,type:str]
    AWS_DEFAULT_REGION: ENC[AES256_GCM,data:PKi1fGULc8ihx3EM,iv:gxMPpDsU4ufV2EYoWLgRtL1oL4+ZeaTZJgch67QPLbU=,tag:TkZbrDJjjU+3gie+j1ixQQ==,type:str]
    BACKUP_FOLDER: ENC[AES256_GCM,data:PGlbNNCR4GMo3T6oDn0p+4l6489iKJbK,iv:th9uJ46iPIgTj7V6namRd1ao6AZ7LIM8Jn9z9E8EDEw=,tag:n5/MWVFJ3KZVjA5ur9ViUQ==,type:str]
    MONGODB_DB: ENC[AES256_GCM,data:D9mWU1GSCgPJSh23qbWnxwv60/2Ev+WsW5GBGQ==,iv:RjCVKuAMRGVGEOxxAiZ6HekS+JjxGLsG+pJhUgVrS5A=,tag:j2ZWg3WY9DKhCyWMc/7NbQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-20T17:35:29Z"
    mac: ENC[AES256_GCM,data:APrTlvmshp9n4CcoubVTN6Mb7KkE/IAqSF1JLbok3lcNDI2Eb0962Xf2XfMzokFj8sqERaopo4GzvmbNpp3tt3O9Etrh4+GUcFZxiWwAvKi4fiZHaYRHzJGYpPPXik7b9tSCb4uNlDiumpJCJ+EucRV27ND6dLpxFLd5lZM21CY=,iv:p4JbYzbXnaqd4C8QDLN/+kxgkdyIUyaDAcsBKuZRcuI=,tag:Hb2nJn6ofKT10vhwijLqDw==,type:str]
    pgp:
        - created_at: "2023-04-20T17:35:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf/alXHxSa9lwEN5aDvI+UGtwNf/YWJHw/F/m9UMN/HmNBe
            y3Oxn7KD1addd2snlLQUzFZ2Bor4tA0Rum0/V52JTJX0EBVjsMn9Le29n38LOLtJ
            Mfn61f4t/NUXJevFV/gJQWr+cb2S3AaOvFd0DlT4YGbV6swJMCt8hsSNxNovS3JV
            CVPPrBkISPMQttBlfdFcWpU4JXY9IeSezdha4Aa/V3uESSkppE2QY4e1thDdMO5k
            YtK9y388prIn77fAFny3uf0wb4tED0PsfM5KmXWmyWTcL1HDLsS9GukWP1u/Urjf
            wIcaSAba13DXctXBz3mBfPn85CC7IcldCDybycAahdJeAZISvk9lt1CmxUJSVhIT
            VNdIAtz2zfk0hhf4j0vL4nOlw0CFVUcJZHLp2o+Nur5x8471o0l+lDubvMjkCP8n
            RHi9dnt6XKhVccrpv6V/Bf1KsbTZX81RsDqRWrRFkw==
            =owSt
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2023-04-20T17:35:28Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9EkoAzHNGDEMB8MM3vWHGP6azygE3ZIKbmsdKYDh3J46X
            elB3FdYAmFupIqcCSv9OJMcvN4+xvzge+iBPDrIlC0IQKaq7dBnR4Nf+cnRNm9Rh
            3Gw1f2wGn1JzjCRJrWuUb+FQn9OsniyiEGzJu8pZiDgEPMG2jzpv5YOKDy2z9Bdy
            HG11epHDTzKanzGlh/UEgnwj6gDdRBbugU1Rvny71KyRqN4IxXOI9FE2ZGGcmA37
            xZ7SF3HBD937CGIgSNqLlKiNo6U+Bc15Nv85J/2GohiOvI7QqzMo/FMhuneiQQXt
            NGnoDVzBRHs6GC7VW5sT461yWL6M8EL+ZxMQJ8yDfNJeAWgTYGKVPV10MmDQhvxI
            JEWQIn58rPSygurhh1cgxzdKb2ssB2JtUvTjeDZWJ2934oN7WQv4v5iVRqHv/emE
            32Vf7wwXQ+5fQjcn58p/Nt6NORC+ViZ8zVUQLj9iNQ==
            =Ikry
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
