apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: stockchecker-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./secrets/slack-webhook-uri.yml
