apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: educs-backend

resources:
- deployment.yml
- ingress.yml
- service.yml

generators:
- secrets-generator.yml

images:
- name: ghcr.io/cguertin14/educs-backend
  newTag: v2.0.32

replicas:
- name: educs-backend
  count: 3

configMapGenerator:
- name: backend-config
  literals:
  - NODE_ENV=production
  - PORT=80
  - URL=https://api.erabliereducoeursucre.com
