apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik
name: traefik
repo: https://helm.traefik.io/traefik
version: v10.3.4
releaseName: traefik
releaseNamespace: kube-system
valuesInline:
  rbac:
    enabled: true
includeCRDs: true