apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: traefik
chartName: traefik
chartRepoUrl: https://helm.traefik.io/traefik
chartVersion: v9.19.1
releaseName: traefik
releaseNamespace: kube-system
extraArgs:
- --include-crds