apiVersion: traefik.containo.us/v1alpha1
kind: Middleware
metadata:
  name: traefik-forward-auth
spec:
  forwardAuth:
    address: http://traefik-forward-auth.kube-system.svc.cluster.local:4181
    authResponseHeaders:
    - X-Forwarded-User