apiVersion: v1
kind: Service
metadata:
  name: traefik-dashboard
spec:
  ports:
  - name: dashboard-http
    port: 80
    targetPort: 9000
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-prometheus
spec:
  ports:
  - name: metrics
    port: 9100
    targetPort: traefik
  type: ClusterIP
---
apiVersion: v1
kind: Service
metadata:
  name: traefik-forward-auth
spec:
  ports:
  - name: auth-http
    port: 4181
    targetPort: 4181
  type: ClusterIP