apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- hubble-ingress.yml

commonLabels:
  app.kubernetes.io/name: cilium

helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  version: 1.17.3
  releaseName: cilium
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    # Enable prometheus metrics
    operator:
      prometheus:
        enabled: true
        serviceMonitor:
          enabled: true
    prometheus:
      enabled: true
      serviceMonitor:
        enabled: true
        trustCRDsExist: true

    # Hubble & ipam configurations
    hubble:
      listenAddress: :4244
      peerService:
        clusterDomain: "cluster.local"
      relay:
        enabled: true
      ui:
        enabled: true
      metrics:
        serviceMonitor:
          enabled: true
        enableOpenMetrics: true
        enabled:
        - dns
        - drop
        - tcp
        - flow
        - port-distribution
        - icmp
        - httpV2:exemplars=true;labelsContext=source_ip
        - source_namespace
        - source_workload
        - destination_ip
        - destination_namespace
        - destination_workload
        - traffic_direction
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDRList: ["10.42.0.0/16"]
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDR: fd00::/104
        clusterPoolIPv6MaskSize: 120
