apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- hubble-ingress.yml

commonLabels:
  app.kubernetes.io/name: cilium

helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  version: v1.11.1
  releaseName: cilium
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    hubble:
      listenAddress: :4244
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      operator:
        clusterPoolIPv4PodCIDR: 10.42.0.0/16