apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- hubble-ingress.yml

commonLabels:
  app.kubernetes.io/name: cilium

helmCharts:
- name: cilium
  repo: https://helm.cilium.io/
  version: 1.13.4
  releaseName: cilium
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    hubble:
      listenAddress: :4244
      relay:
        enabled: true
      ui:
        enabled: true
    ipam:
      mode: cluster-pool
      operator:
        clusterPoolIPv4PodCIDR: 10.42.0.0/16
        clusterPoolIPv4MaskSize: 24
        clusterPoolIPv6PodCIDR: fd00::/104
        clusterPoolIPv6MaskSize: 120
