apiVersion: apps/v1
kind: Deployment
metadata:
    name: ENC[AES256_GCM,data:2Xlkpm8lkfPEwrrbIg==,iv:YXLWYrjZYBtdSSt+DBKR9qR+MaMjr4KZccrTBkGvkHo=,tag:Uhw7+zhsrFNQXUwENUlscA==,type:str]
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0
    template:
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                    - worker1
                                    - worker2
                                    - worker3
                                    - worker4
                                    - worker5
            imagePullSecrets:
                - name: ENC[AES256_GCM,data:sm1YaxXN2euUm2k=,iv:wzGLy9tx3XBI8RTiiGC7+3PaLAjsMdsPsJcoaXOLShU=,tag:7SzXQ84P+r2EN4QlcibqCg==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:2jDtd/NXCiFqWZex7Q==,iv:oMzFPJS6dM2y6ahObBbKkuZ1Mtb2y+uQthjUL+ePyEw=,tag:8fpf7Hcg+tAkHLm54a6O2w==,type:str]
                  image: ghcr.io/cguertin14/educs-backend
                  ports:
                    - containerPort: 80
                      name: ENC[AES256_GCM,data:pXq1iw==,iv:xw8pF4FfX/r6kM8kfgLLdPNBNcNxzhWqAH3IVR1CmWA=,tag:OxUjlq2XQQxlKp2Tya4mPA==,type:str]
                      protocol: TCP
                  securityContext:
                    allowPrivilegeEscalation: false
                  envFrom:
                    - configMapRef:
                        name: ENC[AES256_GCM,data:43PCoTbSjSlpHQUuMpI=,iv:Ncv8WTCXadiDTd8r6IwXF9wTsuT0Kci4ASmYcJcrYU4=,tag:KI/v5RgnDU7tHWeGdGfsJQ==,type:str]
                    - secretRef:
                        name: ENC[AES256_GCM,data:QTMezFg3+qTKjNCI7o0R,iv:C4Fh82Ear4S4aIej78VbnwrcQhztW/C7hEhe9hlZo5I=,tag:Nr+8a/++Ti4dPmKlBW6Vcg==,type:str]
                  env:
                    - name: ENC[AES256_GCM,data:vnwtaU4MH0UfmKw=,iv:yNiyNjxqL7PDww3R/GhQWcFLmjz44bH0lef8TmDHcZU=,tag:KGLFWhyqu7QN8/GyFrwT/w==,type:str]
                      valueFrom:
                        secretKeyRef:
                            name: ENC[AES256_GCM,data:gNIWklqxJwW7BPCChS3HEeyypbdFnNvdrIADc2AQDvQr,iv:QrRMLh0aOO6O0UD4jtWkBpE4pbUKPB/sxK0WL+bzsLU=,tag:f+ibiaDsQQEVp/QiPalKnw==,type:str]
                            key: connectionString.standard
                  resources:
                    limits:
                        # No CPU limit
                        memory: 1Gi
                    requests:
                        memory: 1Gi
                        cpu: 400m
                  livenessProbe:
                    httpGet:
                        path: /api/health
                        port: 80
                    initialDelaySeconds: 100
                    periodSeconds: 20
                  readinessProbe:
                    httpGet:
                        path: /api/health
                        port: 80
                    initialDelaySeconds: 80
                    periodSeconds: 10
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T06:11:18Z"
    mac: ENC[AES256_GCM,data:MuLYP+LDnlAN2qrz31dz58k4fGpgYPPEy7Jk7SkzgNfPDVwtxqoEW3wFfeOAvqSCBGBdroijr92HbOrFO5nOwNOEuZAxP5snB/JMik4qRtjqxqxiGcShbTK7z+1+iRKNWLnRpkgsd/DzfMklOaq9Mu+AdMhgmDoAnb9lKH/tRFA=,iv:ekorDz2+EBLz9+SoSzbADJb+IxkfgO5LnYoqcjjP20g=,tag:rqG2kh29wWMKPfucd17TiA==,type:str]
    pgp:
        - created_at: "2023-12-23T06:11:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/RoYX3P45V4lxY/s+2M4GkelbxYv6mtrxAvOjq8PCjN/Z
            jBEsNYm/5bnzRE2Ep2hfB5RksY9Cq4DUxnCHR4Mvz2P6+qKhDnXQlFTKVkA/2wZ/
            wiI4BvbyHAiWDZ0soVhHTu2CJ8R45vSaCmsz00lagp0L+KHTuotAS5GFKVrAXk6Y
            WSTCfBl6HNlqGd0JnZHluH45vbHaP2y2FqtMYBYq+CDNmz0/ujbq7btrFIoDpD3r
            SEdYP0CVYMZaQB6Lww2IomlGMXrtJMsYKfzMfpbvQRovAEm4M/eSbntZ0nkC+Ylz
            A1jfKH+YKH9tBnVhnuKcn27V7vKokHZn2f6+m4W9pdJcAYR4ZNy59ZyH8/6hiMBM
            puB2tnJWlo1ahHO336Kz1DEqSOFJj5j8qCGaCgm6gV/199SerfwQHpP3vo6b+JjL
            5mFX1ax7CP9XduUQAWQftg7kpSZg1FwEjrmvcVU=
            =0u8e
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
