apiVersion: apps/v1
kind: Deployment
metadata:
    name: ENC[AES256_GCM,data:EJf3B0l0cg78YLpcvg==,iv:gDkgJXoIu4sK0D0BM+jlI+Hc+RWRcspSG+zjcQJh8ao=,tag:HqH5bp4g/6+/XN69EN9E/w==,type:str]
spec:
    strategy:
        type: RollingUpdate
        rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0
    template:
        spec:
            affinity:
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                    - worker1
                                    - worker2
                                    - worker3
                                    - worker4
                                    - worker5
            imagePullSecrets:
                - name: ENC[AES256_GCM,data:nqwMWnZmRqGmss8=,iv:Vq6rnyyYZ1Ls4rMJjsz28X5CwkyyZGnIsDferWSyNCM=,tag:R9GiD4OE5/bP4V6OqTjamA==,type:str]
            containers:
                - name: ENC[AES256_GCM,data:+kZ1F8ulQTAXz6ErwA==,iv:eDT0jcdEFlUvB1U5b1+eVV5G0zo7EGHtuHUfMf24v0c=,tag:7TogNCzYtMzPaXBYcNf8Vg==,type:str]
                  image: ghcr.io/cguertin14/educs-backend
                  ports:
                    - containerPort: 80
                      name: ENC[AES256_GCM,data:oeglZQ==,iv:zWxiv97Z3UBHRpypo9TvtiVHh50lAzGTMG8jwN4Vo1o=,tag:v3dtrNKR3owVd5wlabWsOg==,type:str]
                      protocol: TCP
                  securityContext:
                    allowPrivilegeEscalation: false
                  envFrom:
                    - configMapRef:
                        name: ENC[AES256_GCM,data:6DLNgKUULUJTODna8gk=,iv:wxOq9mVoeE/ZhH/tPPssD+wF+tZsZsKM83LAAC6tIh0=,tag:HTYJ4JC8qZ9PzTCH32v9Pg==,type:str]
                    - secretRef:
                        name: ENC[AES256_GCM,data:wOJYybz4cpT19A1WFBU6,iv:AHpaykdr5LpQUV2WAiVTsD24VfZT171Dd+clLYhzptM=,tag:1WQ6LIjOBoOQFMR/ky4SDQ==,type:str]
                  resources:
                    limits:
                        # No CPU limit
                        memory: 1Gi
                    requests:
                        memory: 1Gi
                        cpu: 400m
                  livenessProbe:
                    httpGet:
                        path: /api/health
                        port: 80
                    initialDelaySeconds: 100
                    periodSeconds: 20
                  readinessProbe:
                    httpGet:
                        path: /api/health
                        port: 80
                    initialDelaySeconds: 80
                    periodSeconds: 10
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T06:23:31Z"
    mac: ENC[AES256_GCM,data:JyhATLA5XAA52GB0egrG5tdwp5jjqI6TgQgGA8wIQjTC6KAVCkgfpPDSPc3x21n5bMlk4zz3u/VELGDkkSWX0AXoy/temYwUrpi0APk64SWDyL2XCds2xbuWPGZBtlGvB6ryQiiyDkn6Io/tPJcGDCZ1tyIFZwY7bTI9te0WGsE=,iv:8DvVWEbFHoUXBje3xaZrPabgEZgNObpnDfEA4aMyj74=,tag:hXMGnZ/RxQpHHUZYUX1Fmg==,type:str]
    pgp:
        - created_at: "2023-12-23T06:23:31Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAm169Qf0RpF4DlUiiPKJxj3PswMJy0ATYVlXjsr9ZoNhp
            sOKmTcOiRsSfeYCW39jpsWXHPHsUv59JViYLpjn2qwfec6gyUqvvhG8X0+GlbtbL
            zRcJr2EghH3Le7Jn3sv7RxxrGSZS51Xrbs8MCCGzDXLIduGOCthmh2JgTOULj4rZ
            MRo3dBQw8lhPj7gqh6RxxaZyiNXZV5lWy2REZ69ug0gort08RQNSN0RVcZ5iEQqV
            J7/+IxoFo1ikcLEXHLQzDeyb4AH0D3h/ucs9i9uZB4eFpB540BOivo9V4HDNjmZO
            PfLRYWotxKat2AyBjElwQi5o3rV0TsO5LVQW0VOfvNJeATohvZorhHMv03L8qF0Q
            0ryHp3s+VgN7B7j1MG3kqARWBBvRUaCbwd+bFP753+DqmkVAb+pbpHJCREADMm8u
            Zzi9Y1SrntXM0SEBiOK+mxK7g1FHHnPVTOkhHfw0Cg==
            =yXDh
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
