apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/instance: promtail
  name: promtail-metrics
  namespace: logging
spec:
  ports:
  - name: http-metrics
    port: 3101
    protocol: TCP
    targetPort: http-metrics