apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: grafana-postgres
  namespace: monitoring
spec:
  imageName: ghcr.io/cloudnative-pg/postgresql:18-system-trixie
  instances: 1

  bootstrap:
    initdb:
      database: grafana
      owner: grafana
      secret:
        name: grafana-postgres-credentials

  storage:
    size: 10Gi
    storageClass: ceph-block

  resources:
    limits:
      memory: 250Mi
    requests:
      cpu: 100m
      memory: 250Mi

  affinity:
    nodeAffinity:
      requiredDuringSchedulingIgnoredDuringExecution:
        nodeSelectorTerms:
        - matchExpressions:
          - key: kubernetes.io/arch
            operator: In
            values:
            - amd64
