apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.13.0
- rbac.yml

patchesStrategicMerge:
- patches/rbac.yml
- patches/namespace.yml

images:
- name: k8s.gcr.io/kube-state-metrics/kube-state-metrics
  newName: registry.k8s.io/kube-state-metrics/kube-state-metrics
  newTag: v2.10.1
