apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- github.com/prometheus-operator/kube-prometheus?ref=v0.10.0
- rbac.yml

patchesStrategicMerge:
- patches/rbac.yml

images:
- name: quay.io/coreos/kube-state-metrics
  newName: k8s.gcr.io/kube-state-metrics-arm64
  newTag: v1.9.5
  # newName: k8s.gcr.io/kube-state-metrics/kube-state-metrics
  # newTag: v2.0.0-rc.1