apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: adguard-home-auth-redirect
  namespace: adguard-home
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: adguard-home
  responseOverride:
  - match:
      statusCodes:
      - type: Value
        value: 302
    redirect:
      scheme: https
      hostname: auth.k8s.cguertin.dev
      path:
        type: ReplaceFullPath
        replaceFullPath: /oauth2/start?rd=https://adguard-home.k8s.cguertin.dev/
      statusCode: 302
