apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:5utSUrAqUPU02Tw=,iv:KQi7FrWQ3JSs3kaVNfAc/tec14EQS5npmrbGNAHG5t4=,tag:hD5vSexAXcwo8ngEFHIM6g==,type:str]
type: kubernetes.io/dockerconfigjson
data:
    .dockerconfigjson: ENC[AES256_GCM,data:xtGC0K0Cv0AhMfE6NnGBXgWKBPxsB90Y5RJN4od4rQ3RoToelBbQyj2ayZTN5q0+1Apcj2hbaPp6ZVHbKbTEVUJZxJxnJEHJ2bGnBBTYUfewD5AkXkVKXHnxgEI9yUicECqg8n7UGM+ziFsTqvQ1v0/Lb3XMBonC3yVry9TTjd5wDqhRSI0VHA==,iv:X2o8ahFQZjLqIExJzyZ63oQCRh2nFIpxiypgmzmKzNw=,tag:YySmCn3hqjbO14sHMNkv3w==,type:str]
sops:
    lastmodified: "2025-08-12T13:29:12Z"
    mac: ENC[AES256_GCM,data:6SpBu1ORBAifuXpiJJfjJR7b44vvxJEB2ZhCTPpFikdZdkEL749KHvXCeFu0KlsxpcYO83tNYr3HPzBZCR7iyRFO5BQXBmNY5q39MiY+W6bRcnRbsLklnjjBvR2c1A8idtDElEke0Gu0RpLMmC5Ws93d/tt8s8LHF2mW1kUeQpo=,iv:+z3s6g/9EoUPnnnIpFX2Sqi66pqU9+CP3Xb9BiS31wc=,tag:IyMob+6mHz83pU7SQCEa6Q==,type:str]
    pgp:
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQwAlEGhTEykYUgzSMW3lA0e47XqFdlYOYmQOiOCfviC9SNA
            I0n6XmMOWHCqsfKtUgmS88i7OjWDBSl2SAjzNOmjgVKxKQKVkTrTMDrl7QV55KMJ
            /zkP6J8db9Y9lBgRHJpLh51vbnL4SxosMpaQuJxN3A4Pfd3Da0kWCm7d1o1KYzu+
            31zxugG9TSd1geIRFMsPUVI0/OIUtUlah8qG+nab/Oppq/YRVP+wg9w1FYw/JU/7
            C16uOdIq4p1cdwK3y49FYJelQCELsQ/MF0yVj+V6jqknJCQNtuzHYQ7o1wtVkhtt
            ZPL3Ti8KTtF8YwACLNYxdM0sRQ7anIvJZN237Cgc+z1dMCtg/UPbtMSgl7AejE8J
            A1DE/rwtMcdrTojlCFLsUnv1aBHqKVFSEmjZgvWCDn5jdEf1kZ4795+HmmdTzKMU
            KN3LnwQG8TbYcc7H8c5ks2ue6pqJFE+ppmWZ4jUGoheKw7d04Aw63liUuDwcny6Q
            LzNVpaXkyuXhFZRdgeTF0l4BH2EVS32hvBATPlgPWbhcyjrRF0XXrPh5ixeTUTAZ
            nUp5PEOnNcjx391hsx2cLC1fEwXmvMRlMH9XdVyW84UlZCWO9p1zinRY8ncGGiWc
            b/BkbZbMDJlJbkKpIOhk
            =OS2Z
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9F8itMowxsyXpCsXJqqur5ShgfiexbNwqjUEhzeLXiP1B
            dm3a/jIk6zYYE+5hbxDnM82ojKvnDYKQ2eZ+WtsbPDEH9n47rsIjp2MBDGirBEWh
            gmEP5M0Y9RfwDtAYEfiom2IkYrsLOlhohD+DGfq6l8yk9NUu0z6csFVwIEjrsMjp
            /S34U3TYfLZZgWBf442XigTBCAv8wDlBpWmaJUtF17KvUt0p+2BK58qj2toBK6gZ
            Yucy9saMMXIeyuE7xBXr2JxQuBB27nZyRW8sQrMZP94fuwkGZ/zJZ89SYesSy4ak
            fvtmO2EaOBJLxjZ3+XW2rQ5jpzljd2lDsIioHwm1MtJeAQGHhGl8gqWheJEkmVnP
            HSpPp24FVs21bPo3UgbcZthv8d3Dygsx5Drho9yc9HnYrbWM3vCEo9d9Xr/z/Gv3
            BmZXdhXU87bWO6Du/MGmQpFOjmyUZdNSFPk0LYxxWQ==
            =OQRi
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
