apiVersion: gateway.envoyproxy.io/v1alpha1
kind: EnvoyProxy
metadata:
  name: envoy-proxy-config
  namespace: envoy-gateway-system
spec:
  provider:
    type: Kubernetes
    kubernetes:
      envoyHpa:
        minReplicas: 3
        maxReplicas: 10
        metrics:
        - type: Resource
          resource:
            name: cpu
            target:
              type: Utilization
              averageUtilization: 80
        - type: Resource
          resource:
            name: memory
            target:
              type: Utilization
              averageUtilization: 80
      envoyService:
        type: LoadBalancer
        loadBalancerIP: 192.168.0.20
        externalTrafficPolicy: Local
        patch:
          type: StrategicMerge
          value:
            spec:
              ports:
              - name: metrics
                protocol: TCP
                port: 19001
                targetPort: 19001
      envoyDeployment:
        container:
          resources:
            requests:
              cpu: 200m
              memory: 512Mi
            limits:
              memory: 512Mi
        strategy:
          type: RollingUpdate
          rollingUpdate:
            maxSurge: 25%
            maxUnavailable: 0
---
apiVersion: gateway.networking.k8s.io/v1
kind: GatewayClass
metadata:
  name: eg
spec:
  controllerName: gateway.envoyproxy.io/gatewayclass-controller
  parametersRef:
    group: gateway.envoyproxy.io
    kind: EnvoyProxy
    name: envoy-proxy-config
    namespace: envoy-gateway-system
---
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: envoy-gateway
  namespace: envoy-gateway-system
spec:
  gatewayClassName: eg
  listeners:
  # *.cguertin.dev (wildcard cert covers cguertin.dev + all *.cguertin.dev)
  - hostname: cguertin.dev
    name: cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: preview.cguertin.dev
    name: preview-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: ha.cguertin.dev
    name: ha-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: photos.cguertin.dev
    name: photos-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: kiosk.cguertin.dev
    name: kiosk-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: classeur.cguertin.dev
    name: classeur-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  # *.k8s.cguertin.dev
  - hostname: auth.k8s.cguertin.dev
    name: auth-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: gitops.k8s.cguertin.dev
    name: gitops-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: monitoring.k8s.cguertin.dev
    name: monitoring-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: network.k8s.cguertin.dev
    name: network-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: adguard-home.k8s.cguertin.dev
    name: adguard-home-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  # *.monitoring.k8s.cguertin.dev
  - hostname: alertmanager.monitoring.k8s.cguertin.dev
    name: alertmanager-monitoring-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: monitoring-k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: prometheus.monitoring.k8s.cguertin.dev
    name: prometheus-monitoring-k8s-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: monitoring-k8s-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  # *.media.cguertin.dev
  - hostname: jellyfin.media.cguertin.dev
    name: jellyfin-media-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: media-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: radarr.media.cguertin.dev
    name: radarr-media-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: media-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: sonarr.media.cguertin.dev
    name: sonarr-media-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: media-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: prowlarr.media.cguertin.dev
    name: prowlarr-media-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: media-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  - hostname: sabnzbd.media.cguertin.dev
    name: sabnzbd-media-cguertin-dev-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: media-cguertin-dev-wildcard-cert
        group: ''
        kind: Secret
  # Educs (explicit certs - different issuer)
  - hostname: erabliereducoeursucre.com
    name: educs-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: educs-frontend-cert
        group: ''
        kind: Secret
  - hostname: www.erabliereducoeursucre.com
    name: www-educs-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: www-educs-frontend-cert
        group: ''
        kind: Secret
  - hostname: api.erabliereducoeursucre.com
    name: api-educs-https
    port: 443
    protocol: HTTPS
    allowedRoutes:
      namespaces:
        from: All
    tls:
      mode: Terminate
      certificateRefs:
      - name: educs-backend-cert
        group: ''
        kind: Secret
---
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: global-timeout
  namespace: envoy-gateway-system
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: Gateway
    name: envoy-gateway
  timeout:
    http:
      requestTimeout: 120s