apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  template:
    spec:
      hostNetwork: false
      containers:
      - name: exporter
        image: ekofr/pihole-exporter
        imagePullPolicy: IfNotPresent
        env:
        - name: PIHOLE_HOSTNAME
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        - name: PIHOLE_PORT
          value: "80"
        - name: PIHOLE_PROTOCOL
          value: "http"
        - name: PIHOLE_PASSWORD
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-secrets
        resources: {}
        ports:
        - containerPort: 9617
          name: prometheus
          protocol: TCP
      - name: pihole
        env:
        - name: FTLCONF_webserver_api_password
          valueFrom:
            secretKeyRef:
              key: password
              name: pihole-secrets
        envFrom:
        - configMapRef:
            name: pihole-config