apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- alerts/
- grafana-pvc.yml
- ingresses.yml

generators:
- secrets-generator.yml

patchesJson6902:
## 
# First, this JSON patch below changes the CPUThrottling alert:
# 
# - Change from 25% to 75%
#
# Second and Third, the JSON patches below remove the following alerts: 
#  
# - KubeSchedulerDown
# - KubeControllerManagerDown
#
# We need to remove the 20th group twice, because
# that is the index of one of the two alerts, and
# once we remove one of the two, the other one takes
# the 20th index and so we need to remove that one too.
#
- path: patches/prometheus-alerts-patch.yml
  target:
    group: monitoring.coreos.com
    kind: PrometheusRule
    name: kubernetes-monitoring-rules
    namespace: monitoring
    version: v1

patchesStrategicMerge:
- patches/prometheus-modifications.yml
- patches/grafana-strategic-patches.yml

configMapGenerator:
- name: grafana-settings-config
  namespace: monitoring
  envs:
  - env/grafana-settings
- name: grafana-dashboards-custom
  namespace: monitoring
  files:
  - dashboards/argocd.json
  - dashboards/traefik.json
  - dashboards/node_temperatures.json
  - dashboards/pi_hole.json
  - dashboards/blog_slos.json
