apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- alerts/
- grafana-pvc.yml
- ingresses.yml

generators:
- secrets-generator.yml

patchesJson6902:
## 
# First, this JSON patch below changes the CPUThrottling alert:
# 
# - Change from 25% to 75%
#
# Second and Third, the JSON patches below remove the following alerts: 
#  
# - KubeSchedulerDown
# - KubeControllerManagerDown
#
# We need to remove the 20th group twice, because
# that is the index of one of the two alerts, and
# once we remove one of the two, the other one takes
# the 20th index and so we need to remove that one too.
#
- path: patches/prometheus-alerts-patch.yml
  target:
    group: monitoring.coreos.com
    kind: PrometheusRule
    name: kubernetes-monitoring-rules
    namespace: monitoring
    version: v1

patchesStrategicMerge:
- patches/prometheus-modifications.yml
- patches/grafana-strategic-patches.yml

configMapGenerator:
- name: grafana-settings-config
  namespace: monitoring
  envs:
  - env/grafana-settings

- name: grafana-dashboards-custom
  namespace: monitoring
  files:
  - dashboards/argocd.json
  - dashboards/argo-rollouts.json
  - dashboards/traefik.json
  - dashboards/node_temperatures.json
  - dashboards/pi_hole.json
  - dashboards/blog_slos.json

## All Linkerd2 dashboards are defined below
#
- name: grafana-linkerd2-dashboards-1
  namespace: monitoring
  files:
  # Replace 'stable-VERSION' when a new release comes out
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/authority.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/cronjob.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/daemonset.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/deployment.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/health.json
- name: grafana-linkerd2-dashboards-2
  namespace: monitoring
  files:
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/job.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/kubernetes.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/multicluster.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/namespace.json
- name: grafana-linkerd2-dashboards-3
  namespace: monitoring
  files:
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/pod.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/prometheus-benchmark.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/prometheus.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/replicaset.json
- name: grafana-linkerd2-dashboards-4
  namespace: monitoring
  files:
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/replicationcontroller.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/route.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/service.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/statefulset.json
  - https://raw.githubusercontent.com/linkerd/linkerd2/stable-2.11.1/grafana/dashboards/top-line.json
