apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- alerts/
- grafana-pvc.yml
- ingresses.yml

generators:
- secrets-generator.yml

patches:
# Networking changes to expose services publicly
# by going through a reverse proxy
- path: patches/network-policies-reverse-proxy.yml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: alertmanager-main
    namespace: monitoring
    version: v1
- path: patches/network-policies-reverse-proxy.yml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: prometheus-k8s
    namespace: monitoring
    version: v1
- path: patches/network-policies-reverse-proxy.yml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: grafana
    namespace: monitoring
    version: v1
# Prometheus networking changes
- path: patches/network-policy-prometheus-traffic.yml
  target:
    group: networking.k8s.io
    kind: NetworkPolicy
    name: prometheus-k8s
    namespace: monitoring
    version: v1
## 
# First, this JSON patch below changes the CPUThrottling alert:
# 
# - Change from 25% to 75%
#
# Second and Third, the JSON patches below remove the following alerts: 
#  
# - KubeSchedulerDown
# - KubeControllerManagerDown
#
# We need to remove the 20th group twice, because
# that is the index of one of the two alerts, and
# once we remove one of the two, the other one takes
# the 20th index and so we need to remove that one too.
#
- path: patches/prometheus-alerts-patch.yml
  target:
    group: monitoring.coreos.com
    kind: PrometheusRule
    name: kubernetes-monitoring-rules
    namespace: monitoring
    version: v1

patchesStrategicMerge:
- patches/crds-length.yml
- patches/prometheus-modifications.yml
- patches/grafana-strategic-patches.yml
- patches/apiservice-metrics-server.yml # use metrics-server instead of prom-adapter for metrics.

configMapGenerator:
- name: grafana-settings-config
  namespace: monitoring
  envs:
  - env/grafana-settings
- name: grafana-dashboards-custom
  namespace: monitoring
  files:
  - dashboards/argocd.json
  - dashboards/argo-rollouts.json
  - dashboards/node_temperatures.json
  - dashboards/pi_hole_3.json
- name: grafana-dashboards-custom-2
  namespace: monitoring
  files:
  - dashboards/blog_slos.json
  - dashboards/nginx-overview.json
  - dashboards/nginx-performance.json
  - dashboards/nvidia-dashboard-3.json
  - dashboards/educs_slos.json
- name: grafana-dashboards-custom-3
  namespace: monitoring
  files:
  - dashboards/ceph_cluster_dashboard.json
  - dashboards/ceph_osd_single_dashboard_v2.json
  - dashboards/ceph_pools_dashboard.json
  - dashboards/velero.json
- name: grafana-dashboards-custom-4
  namespace: monitoring
  files:
  - dashboards/velero.json

secretGenerator:
- name: grafana-datasources
  namespace: monitoring
  behavior: replace
  files:
  - datasources.yaml=secrets/datasources.json
