apiVersion: viaduct.ai/v1
kind: ksops-exec
metadata:
  name: monitoring-secret-generator
files:
- ./secrets/grafana-github-sso-credentials.yml
- ./secrets/grafana-admin-credentials.yml
- ./secrets/alertmanager-main.yml