apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: argo-rollouts

resources:
- github.com/argoproj/argo-rollouts/manifests/cluster-install?ref=v1.4.1
- github.com/argoproj/argo-rollouts/manifests/dashboard-install?ref=v1.4.1
- resources/ingress.yml
- resources/namespace.yml
- metrics/rbac.yml
- metrics/service-monitor.yml
- templates/replicaset-ready.yml
- templates/slo-success-rate.yml
- templates/load-tester.yml

images:
- name: quay.io/argoproj/argo-rollouts
  newTag: v1.4.1
- name: quay.io/argoproj/kubectl-argo-rollouts
  newTag: v1.4.1
- name: cguertz/load-tester
  newTag: v1.0.0

configurations:
- https://argoproj.github.io/argo-rollouts/features/kustomize/rollout-transform.yaml

commonLabels:
  app.kubernetes.io/name: argo-rollouts

patchesStrategicMerge:
- patches/controller-metrics.yml

patchesJson6902:
- path: patches/remove-unknown-fields.yml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: analysisruns.argoproj.io
    version: v1
- path: patches/remove-unknown-fields.yml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: analysistemplates.argoproj.io
    version: v1
- path: patches/remove-unknown-fields.yml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: clusteranalysistemplates.argoproj.io
    version: v1
- path: patches/remove-unknown-fields.yml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: experiments.argoproj.io
    version: v1
- path: patches/remove-unknown-fields.yml
  target:
    group: apiextensions.k8s.io
    kind: CustomResourceDefinition
    name: rollouts.argoproj.io
    version: v1
- path: patches/add-configmap-to-clusterrole.yml
  target:
    group: rbac.authorization.k8s.io
    kind: ClusterRole
    name: argo-rollouts-clusterrole
    version: v1
