apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- resources/argocd-ingress.yml
- resources/project.yml
- resources/applications.yml

patchesStrategicMerge:
- patches/argocd-rbac-cm-patch.yml
- patches/argocd-cm-patch.yml
- patches/argocd-server-patch.yml
- patches/argocd-repo-server-ksops-patch.yml
- patches/argocd-repo-server-gpg-import-patch.yml
- patches/application-controller-patch.yml

generators:
- secrets-generator.yml

images:
- name: quay.io/argoproj/argocd
  newName: cyrilix/argocd # arm64-capable ArgoCD docker image
  newTag: v2.2.5
- name: argoproj/argocd
  newName: cyrilix/argocd # arm64-capable ArgoCD docker image
  newTag: v2.2.5
- name: viaductoss/ksops
  newTag: v3.0.1-arm64 # arm64-capable version of ksops
