apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- resources/argocd-ingress.yml
- resources/project.yml
- resources/applications.yml

patchesStrategicMerge:
- patches/argocd-rbac-cm-patch.yml
- patches/argocd-cm-patch.yml
- patches/argocd-server-patch.yml
- patches/argocd-repo-server-ksops-patch.yml
- patches/argocd-repo-server-gpg-import-patch.yml
- patches/application-controller-patch.yml

generators:
- secrets-generator.yml

images:
- name: viaductoss/ksops
  newTag: v4.3.3-arm64 # arm64-capable version of ksops
