apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- resources/argocd-ingress.yml
- resources/project.yml
- resources/applications.yml

patchesStrategicMerge:
- patches/argocd-cm-patch.yml
- patches/argocd-rbac-cm-patch.yml
- patches/argocd-server-patch.yml
- patches/argocd-repo-server-patch.yml
- patches/argocd-repo-server-gpg-import-patch.yml
- patches/application-controller-patch.yml

generators:
- secrets-generator.yml

images:
- name: argoproj/argocd
  newName: cyrilix/argocd # arm64-capable ArgoCD docker image
  newTag: v1.8.7
- name: viaductoss/ksops
  newName: cguertz/ksops # TODO: Remove once https://github.com/viaduct-ai/kustomize-sops/pull/102 is merged.
  newTag: v2.5.1-goreleaser-test-3-arm64 # TODO: Change tag once https://github.com/viaduct-ai/kustomize-sops/pull/102 is merged.