apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base
- resources/cluster-issuer.yml
- resources/namespace.yml

generators:
- secrets-generator.yml

namespace: cert-manager