apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-issuer
spec:
  acme:
    # You must replace this email address with your own.
    # Let's Encrypt will use this to contact you about expiring
    # certificates, and issues related to your account.
    email: charlesguertin@live.ca
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      # Secret resource used to store the account's private key.
      name: letsencrypt-private-key
    solvers:
    - dns01:
        cloudflare:
          email: charlesguertin@live.ca
          apiTokenSecretRef:
            name: cloudflare-api-token-secret
            key: api-token
      selector:
        dnsNames:
        - 'cguertin.dev'
        - 'preview.cguertin.dev'
        - 'plex.media.cguertin.dev'
        - 'radarr.media.cguertin.dev'
        - 'sonarr.media.cguertin.dev'
        - 'prowlarr.media.cguertin.dev'
        - 'qbittorrent.media.cguertin.dev'
        - 'mesh.k8s.cguertin.dev'
        - 'monitoring.k8s.cguertin.dev'
        - 'network.k8s.cguertin.dev'
        - 'alertmanager.monitoring.k8s.cguertin.dev'
        - 'prometheus.monitoring.k8s.cguertin.dev'
        - 'rollout.gitops.k8s.cguertin.dev'
        - 'gitops.k8s.cguertin.dev'
        - 'auth.k8s.cguertin.dev'
        - 'pihole.k8s.cguertin.dev'
        - 'erabliereducoeursucre.com'
        - 'www.erabliereducoeursucre.com'
        - 'api.erabliereducoeursucre.com'