apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: adguard-home

resources:
- resources/namespace.yml

images:
- name: adguard/adguardhome
  newTag: v0.107.66

helmCharts:
- name: adguard-home
  namespace: adguard-home
  releaseName: adguard-home
  repo: https://k8s-at-home.com/charts/
  version: 5.5.2
  valuesInline:
    env:
      TZ: America/Toronto

    persistence:
      config:
        enabled: true
        mountPath: /opt/adguardhome/conf
        storageClass: ceph-block
        size: 1Gi
      data:
        enabled: true
        mountPath: /opt/adguardhome/work
        storageClass: ceph-block
        accessMode: ReadWriteOnce
        size: 2Gi

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-issuer"
          nginx.ingress.kubernetes.io/auth-url: "https://auth.k8s.cguertin.dev/oauth2/auth"
          nginx.ingress.kubernetes.io/auth-signin: "https://auth.k8s.cguertin.dev/oauth2/start?rd=https://$host$uri"
        ingressClassName: nginx
        tls:
        - hosts:
          - adguard-home.k8s.cguertin.dev
          secretName: adguard-home-cert
        hosts:
          - host: adguard-home.k8s.cguertin.dev
            paths:
              - path: /

    service:
      main:
        primary: true
        ports:
          http:
            port: 3000
      dns-tcp:
        enabled: true
        type: LoadBalancer
        ports:
          dns-tcp:
            enabled: true
            port: 53
            protocol: TCP
            targetPort: 53
        externalTrafficPolicy: Local
      dns-udp:
        enabled: true
        type: LoadBalancer
        loadBalancerIP: 192.168.0.21
        ports:
          dns-udp:
            enabled: true
            port: 53
            protocol: UDP
            targetPort: 53
        externalTrafficPolicy: Local