---
##
# TEMPLATES
#
execute_on_tags: &execute_on_tags
  # This filter will ignore changes to all the branches
  # It will only be triggered when a tag with the following format v(anything you want here) is pushed
  filters:
    tags:
      only: /v.*/
    branches:
      ignore: /.*/

execute_on_main: &execute_on_main
  # This filter will ignore changes to all the branches
  # It will only be triggered when a tag with the following format v(anything you want here) is pushed
  filters:
    branches:
      only: main

##
# WORKFLOWS
#
workflows:
  version: 2
  # Triggered only with main changes
  linters_check:
    jobs:
      - tf_lint:
          <<: *execute_on_main          
  # Triggered only on tags
  terraform:
    jobs:
      - plan:
          <<: *execute_on_tags
      - apply_approval:
          <<: *execute_on_tags
          type: approval
          requires:
            - plan
      - apply:
          <<: *execute_on_tags
          requires:
            - apply_approval

##
# EXECUTORS
#
executors:
  terraform-executor:
    docker:
      - image: hashicorp/terraform:1.1.7

  scripts-executor:
    docker:
      - image: cimg/base:2022.04-20.04

##
# JOBS
#
version: 2.1
jobs:
  tf_lint:
    resource_class: small
    executor: terraform-executor
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: Test if terraform configs are valid
          working_directory: dns
          command: |
            terraform init -input=false
            terraform fmt -check -recursive -diff

  plan:
    resource_class: small
    executor: terraform-executor
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - run:
          name: Plan production terraform config
          working_directory: dns
          command: |
            terraform init -input=false
            terraform plan -input=false
      - store_artifacts:
          path: terraform/tfplan.production
          destination: tfplan.production

  apply:
    resource_class: small
    executor: terraform-executor
    steps:
      - checkout
      - run:
          command: >-
            echo "credentials \"app.terraform.io\" {token =
            \"$TERRAFORM_TOKEN\"}" > $HOME/.terraformrc
          name: Create .terraformrc file locally
      - attach_workspace:
          at: terraform
      - run:
          name: Apply production terraform config
          working_directory: dns
          command: |
            terraform init -input=false
            terraform apply -auto-approve -input=false