apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: redis

resources:
- deployment.yml
- service.yml
# - network-policy.yml

replicas:
- count: 1
  name: redis

images:
- name: redis
  newTag: '7.0-alpine'

configMapGenerator:
- name: redis-probes
  files:
  - config/liveness.sh
  - config/readiness.sh