apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

commonLabels:
  app.kubernetes.io/name: redis

resources:
- statefulset.yml
- service.yml
- pdb.yml

replicas:
- count: 6
  name: redis

images:
- name: redis
  newTag: '7.0-alpine'

configMapGenerator:
- name: redis-cluster
  files:
  - config/redis.conf
- name: redis-probes
  files:
  - config/liveness.sh
  - config/readiness.sh