apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero-backups

resources:
- resources/namespace.yml

generators:
- secrets-generator.yml

images:
- name: velero/velero-plugin-for-aws
  newTag: v1.12.0

helmCharts:
- name: velero
  releaseName: velero
  namespace: velero-backups
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 8.7.2
  includeCRDs: true
  valuesInline:
    credentials:
      existingSecret: velero-s3-credentials
    
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

    configuration:
      backupStorageLocation:
      - name: aws
        default: true
        provider: aws
        bucket: velero-backups-bucket20250418195129140400000001
        accessMode: ReadWrite
        config:
          region: us-east-1
      volumeSnapshotLocation:
      - name: aws
        provider: aws
        default: true
        config:
          region: us-east-1

    schedules:
      volumes-backups:
        disabled: false
        schedule: "0 */24 * * *" # every 1 day/24 hours
        useOwnerReferencesInBackup: false
        paused: false
        skipImmediately: false
        template:
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: aws
          # Specific PVs/PVCs namespaces
          includedNamespaces:
          # TODO: Add more namespaces here once all PVCs/PVs are migrated to rook-ceph...
          - immich
          # Only backup PVs and PVCs
          includedNamespaceScopedResources:
          - persistentVolumeClaims
          includedClusterScopedResources:
          - persistentVolumes
      etcd-backups:
        disabled: false
        schedule: "0 */72 * * *" # every 3 days
        useOwnerReferencesInBackup: false
        paused: false
        skipImmediately: false
        template:
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: aws
          # All namespaces
          includedNamespaces:
          - argo-rollouts
          - argocd
          - blog
          - cert-manager
          - cloudnative-pg
          - ddns
          - default
          - educs
          - gpu-operator
          - home-assistant
          - immich
          - k3supdater
          - kube-node-lease
          - kube-public
          - kube-system
          - kured
          - lululemon-stockchecker
          - mediaplatform
          - metallb-system
          - mongodb-operator
          - monitoring
          - pihole
          - rook-ceph
          - synology-nfs
          - synology-nfs-media
          # PVs and PVCs are backed up in a separate backup schedule
          excludedNamespaceScopedResources:
          - persistentVolumeClaims
          excludedClusterScopedResources:
          - persistentVolumes