apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: system-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/cguertin14/infra
      revision: main
      directories:
      - path: system-apps/*
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
    spec:
      project: production
      destination:
        namespace: kube-system
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/cguertin14/infra
        targetRevision: main
        path: '{{.path.path}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: namespaced-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
  - git:
      repoURL: https://github.com/cguertin14/infra
      revision: main
      directories:
      - path: applications/*
      - path: applications/argocd
        exclude: true
      - path: applications/educs-topology
        exclude: true
      - path: applications/educs-network
        exclude: true
  template:
    metadata:
      name: '{{.path.basename}}'
      namespace: argocd
    spec:
      project: production
      destination:
        namespace: '{{.path.basename}}'
        server: https://kubernetes.default.svc
      source:
        repoURL: https://github.com/cguertin14/infra
        targetRevision: main
        path: '{{.path.path}}'
      syncPolicy:
        automated:
          selfHeal: true
          prune: true
        syncOptions:
        - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: argocd
  namespace: argocd
spec:
  project: production
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cguertin14/infra
    targetRevision: main
    path: applications/argocd
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - ServerSideApply=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: educs-topology
  namespace: argocd
spec:
  project: production
  destination:
    namespace: educs
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cguertin14/infra
    targetRevision: main
    path: applications/educs-topology
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: educs-network
  namespace: argocd
spec:
  project: production
  destination:
    namespace: educs
    server: https://kubernetes.default.svc
  source:
    repoURL: https://github.com/cguertin14/infra
    targetRevision: main
    path: applications/educs-network
  syncPolicy:
    automated:
      selfHeal: true
      prune: true
    syncOptions:
    - CreateNamespace=true
