apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
- resources/namespace.yml

generators:
- secrets-generator.yml

images:
- name: velero/velero-plugin-for-aws
  newTag: v1.12.0

configMapGenerator:
- name: node-agent-config
  namespace: velero
  options:
    disableNameSuffixHash: true
  files:
  - config/node-agent-config.json

patches:
- path: patches/node-agent-ds-configmap.yml

helmCharts:
- name: velero
  releaseName: velero
  namespace: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 9.0.0
  includeCRDs: true
  valuesInline:
    credentials:
      existingSecret: velero-s3-credentials
    
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

    deployNodeAgent: true
    configuration:
      defaultRepoMaintainFrequency: 6h0m0s
      defaultSnapshotMoveData: true
      defaultBackupStorageLocation: aws
      features: EnableCSI
      uploaderType: kopia
      backupStorageLocation:
      - name: aws
        default: true
        provider: aws
        bucket: velero-backups-bucket20250418195129140400000001
        accessMode: ReadWrite
        config:
          region: us-east-1
      volumeSnapshotLocation:
      - name: aws
        provider: aws
        default: true
        config:
          region: us-east-1

    schedules:
      # This backup includes all resources in the cluster EXCEPT PVs/PVCs
      etcd-backups:
        disabled: false
        schedule: "0 2,14 * * *" # every day at 2AM & 2PM
        useOwnerReferencesInBackup: true
        paused: false
        skipImmediately: false
        template:
          csiSnapshotTimeout: 30m0s
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: aws
          includedNamespaces:
          - '*'
          excludedResources:
          - persistentvolumes
          - persistentvolumeclaims
      persistent-volumes-backups:
        disabled: false
        schedule: "15 2,14 * * *" # every day at 2:15AM & 2:15PM
        useOwnerReferencesInBackup: true
        paused: false
        skipImmediately: false
        template:
          csiSnapshotTimeout: 30m0s
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: aws
          includedNamespaces:
          - educs
          - home-assistant
          - immich
          - mediaplatform
          - monitoring
          - pihole
          includedResources:
          - persistentvolumes
          - persistentvolumeclaims
