apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: velero

resources:
- resources/namespace.yml

generators:
- secrets-generator.yml

images:
- name: velero/velero-plugin-for-aws
  newTag: v1.12.0

configMapGenerator:
- name: node-agent-config
  namespace: velero
  options:
    disableNameSuffixHash: true
  files:
  - config/node-agent-config.json

patches:
- path: patches/node-agent-ds-configmap.yml

helmCharts:
- name: velero
  releaseName: velero
  namespace: velero
  repo: https://vmware-tanzu.github.io/helm-charts
  version: 9.0.0
  includeCRDs: true
  valuesInline:
    metrics:
      enabled: true
      serviceMonitor:
        enabled: true
  
    credentials:
      existingSecret: velero-s3-credentials
    
    initContainers:
    - name: velero-plugin-for-aws
      image: velero/velero-plugin-for-aws
      imagePullPolicy: IfNotPresent
      volumeMounts:
        - mountPath: /target
          name: plugins

    deployNodeAgent: true
    configuration:
      defaultRepoMaintainFrequency: 6h0m0s
      defaultSnapshotMoveData: true
      defaultBackupStorageLocation: backblaze
      features: EnableCSI
      uploaderType: kopia
      backupStorageLocation:
      - name: backblaze
        default: true
        provider: aws
        bucket: velero-backups-bucket
        accessMode: ReadWrite
        config:
          region: ca-east-006
          s3Url: https://s3.ca-east-006.backblazeb2.com
          checksumAlgorithm: '' # fix for s3:PutObject error https://github.com/vmware-tanzu/velero/issues/7534#issuecomment-2033987674
      volumeSnapshotLocation:
      - name: backblaze
        provider: aws
        default: true
        config:
          region: ca-east-006

    schedules:
      # This backup includes all resources in the cluster EXCEPT PVs/PVCs
      etcd-backups:
        disabled: false
        schedule: "0 6 * * *" # every day at 2AM - time is in UTC
        useOwnerReferencesInBackup: true
        paused: false
        skipImmediately: false
        template:
          csiSnapshotTimeout: 60m0s
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: backblaze
          includedNamespaces:
          - '*'
          excludedResources:
          - persistentvolumes
          - persistentvolumeclaims
      persistent-volumes-backups:
        disabled: false
        schedule: "15 6 * * *" # every day at 2:15AM - time is in UTC
        useOwnerReferencesInBackup: true
        paused: false
        skipImmediately: false
        template:
          csiSnapshotTimeout: 60m0s # wait up to 1 hour for the snapshot to be ready for use
          ttl: "336h" # 2 weeks / 14 days
          storageLocation: backblaze
          includedNamespaces:
          - educs
          - home-assistant
          - immich
          - mediaplatform
          - monitoring
          - pihole
          includedResources:
          - persistentvolumes
          - persistentvolumeclaims
