apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:6c69+4HBSrmXRXfrTKTa+rkZ,iv:J8ipWYr9Q7SlHDkRJ3CZV3YqnE9U65uZ5cub7gPpVSM=,tag:8AQH4LTD+tMluEmIRSQQMA==,type:str]
    namespace: obsidianls
type: Opaque
stringData:
    adminUsername: ENC[AES256_GCM,data:oVn1iyM=,iv:camN8yqIuHuH8McQgx2TAdToxjck78v6ZHTW8BazSCw=,tag:82WXRFN9fc/MsB7a4S60Fw==,type:str]
    adminPassword: ENC[AES256_GCM,data:YM8Nsn+wwA5WSVm2HhfR76n2Sx5K8A8dkLJNZx7+Ubw=,iv:vvpnwYcuutHVtIkHKxIf/9gCNHY3GCoi7kZdbnU/3/s=,tag:QWm/v2MKqRCtIyM4NzqIqQ==,type:str]
    cookieAuthSecret: ENC[AES256_GCM,data:WVbxE1wyqr53T6dUg/3U4LVSb53D0zMlw1PDgZMUqqw=,iv:Eliu6sb0BYWhxwXxrPoJ1yy9yjrTUg2hkzy/VqOyqyE=,tag:/UuDPrKKiKw3ADubF6P6kg==,type:str]
    erlangCookie: ENC[AES256_GCM,data:8aWFnOUjEDpdnjP63CM5OaKFdhy4cvsNbo3lpUVmwxk=,iv:vwTb0jgfAupcsHsmzV6MzLZMPx8xIcZ5badPZWPYdhM=,tag:zezDdrHhRZiNfhjQKi9Hpg==,type:str]
sops:
    lastmodified: "2026-04-19T18:34:28Z"
    mac: ENC[AES256_GCM,data:JheILNdvxmb+MUCkuTT0wGPVZ6PIYdGLRsvwfrtdswKDy8wVpG4u4cZxaIJQ1147KafCuh+N78TcIaHbMtpywkGegLq1K66zSIIjEpP2dKZhdRHF/06tYeKBuX05J+XVQt8FzN1w+UITfupf5v3r3Q9Rd2l00W7O5e5Q3HnN/K4=,iv:aBSg1IVsWsYwySL9Eun6o6wj1uyLl+Rg4d+GTPBNpYw=,tag:xDlTnTI2ubogIe4A7IDjkg==,type:str]
    pgp:
        - created_at: "2026-04-19T18:34:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAlmfYNNeVL85/guk7PGDDBfcSMASA+f3l7JwBz5JBGYsI
            qRRjR5vAr4sXDJrz5ORw/fpZH6NCl03iNryppFFXxz5ZQS1YNYpLsblp1oyArquR
            KhiviUwo5AQMEri+CYb32358FS8sk5aQSmK0KwnD01NSD4l6sUZ13ruD+KnQmQ8K
            LMfr652zISqDUNaBl/fFhJAwFMEw/PBtFerEsCcbng2aBv4ZSPVH2DjrQoDA4iKm
            ObxjASJy6Mly0aLEL3p/OlSnkFKdqyjlokpaPzewg1yvsKjs0rns8/ngPiYlzFrJ
            KL6OuVums+YugFPi/UyRIJo1DH2eYA6gkwMJuCy9f9JeAY1Otmz9jfDDteWLhqib
            f0NGRJYJKd8fTr4Kx4booWQuzUuNN5LuVjqms++vLi78X4hS3l30ayXcBLGrK/sc
            rf4W2lsyEq4qAzYo/+RCtFGlIhAPqHpmdpFlOyOAug==
            =SVxq
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-04-19T18:34:28Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQwAiMrs51t7dioOKTMyH/yGXoLbpHoQvMNXv7YAxWzUS8KU
            IE5WbBZlMgLp7B/9ASDUMRTSZF5MrveV+TiAyat8l5agnSXX4lZI/o1nTgFH3eEA
            8hI+iaqx8qDr7vegJ2oKrR6jlvPNTZeFn9Zcp++eSpThS9oFaMHUFO6d+L3sIhBI
            OqMyDp51Rv0EVUa1vbU1zjj+5wOr4n4JWNcy/XJhBaHyq/GvGDz408VRaD6ys8ZY
            +nI1u/1383bIMDgX74hnkH7gqCrSK335H1npQNxiB7Ci6Un+qwkKySskkZazfeRQ
            tSQIDZC7lXiThhbPI9BahIJD3SzlrSPiH5uj89O5It9gkVkpGFY7pCVqO7+k7RdO
            hUTSQMvDEcTpJfYT1fbc0atuHqpM9DkHyAwORDmlVXszZzQUOk9O0s3OmK4YGYNY
            g22r0d8Y9iYDcydQy47BEEaCaLMlVVrBxNIVxz9wtNWsv+w40fcpGsraM/mFOnK4
            7ROmHwqswozKTUxXOKX00l4B9KrFRqAji1FcKmPYnMeYVQ84tsRFjWXJmWFr6gkP
            pYP0T0HpLYK1P+qxscEvIstoQDufhzre9jRHYNQauwNTaprl2TH4OSSbaLYpJB/Q
            rrjlRtSxOafPAIMCD8Jf
            =xB3e
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
