apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: oauth2-proxy

images:
- name: quay.io/oauth2-proxy/oauth2-proxy
  newTag: v7.4.0

generators:
- secrets-generator.yml

resources:
- resources/deployment.yml
- resources/service.yml
- resources/ingress.yml