apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/services.yml
- resources/ingress-class.yml
- resources/middleware.yml
- metrics/service-monitor.yml

generators:
- resources/helm-chart.yml

patchesStrategicMerge:
- patches/deployment.yml

commonLabels:
  app.kubernetes.io/name: traefik

images:
- name: thomseddon/traefik-forward-auth
  newTag: 2-arm64

namespace: kube-system