apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- resources/services.yml
- resources/ingress-class.yml
- resources/middleware.yml
- metrics/service-monitor.yml

patchesStrategicMerge:
- patches/deployment.yml

commonLabels:
  app.kubernetes.io/name: traefik

helmCharts:
- name: traefik
  repo: https://helm.traefik.io/traefik
  version: 15.3.0
  releaseName: traefik
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    rbac:
      enabled: true

images:
- name: thomseddon/traefik-forward-auth
  newTag: 2-arm64
