apiVersion: batch/v1
kind: CronJob
metadata:
    name: ENC[AES256_GCM,data:+GIzoaWE4MuXZ0lgeuLQ,iv:HJxLmFSxMOy2qlqHJlJ/O5mQpmp3Pj24Tnv2Lsur/4k=,tag:A7sw8dngaQxvAcKfz6lTDA==,type:str]
spec:
    # suspend: true # Uncomment if need to restore DB.
    # every 4 hours
    schedule: 0 */4 * * *
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 4
    successfulJobsHistoryLimit: 4
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - image: ghcr.io/cguertin14/mongodb-backup-s3
                          imagePullPolicy: IfNotPresent
                          name: ENC[AES256_GCM,data:DrQG75/fKtGJK2kpeAml,iv:rC+sA0VpUWADKNW+vignd2y7j4/1rQuq+adfyY4zad8=,tag:Zd/2+tFYG40mFRACbOG7ow==,type:str]
                          envFrom:
                            - configMapRef:
                                name: ENC[AES256_GCM,data:lFXFjlzfKdwGKV8es9JW1B89SKWmpw==,iv:2UUKgYyd5/JR/c1U2x5xBHLuNyMHLAqJAEhotn7Vxlk=,tag:22FYQwJlTHzldOZXoCMA6g==,type:str]
                            - secretRef:
                                name: ENC[AES256_GCM,data:ULt/XoOhPv3I3DmcO3T1YGKlmkvn3CA=,iv:bbu4G+CIp189ujkS4r51kFFIuLgkGyIX6Rp/5+Fnjbg=,tag:TZeH1Umo0oGn0ZNb/OtjIw==,type:str]
                          env:
                            - name: ENC[AES256_GCM,data:mhXNcnvD1AaHJOfC,iv:tXvJgeGB2mjiVEMZJyaTW7IO5pwGYK5oWz9Co34pnBI=,tag:U2Ix3VgicKXZTKGfbsioTA==,type:str]
                              valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:5TJlvDRkTxO6iJOg8YMEdX9ndo75ucKSTBN/WblUKNnm,iv:I1+2uf7ZZ349hBe2NqDhJcGKwg8Dyr1lBD+LAz4cxxc=,tag:nWnFKmRoRUije5yHncrQ/w==,type:str]
                                    key: username
                            - name: ENC[AES256_GCM,data:t47vX7yi8SXhSVw0,iv:jCc2Jl/i/jMMZAAcIt2xlKTTbtJC2oiJsuJTzMCVVbM=,tag:6ZcN7sCO+O0XZLwgeSXyRg==,type:str]
                              valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:AKoarELDZgutRHzcmX/A5XngU0YnXStwyGPW3AljLeYc,iv:o7rIMYQdz+0ateAUOEc2/xEjs4K1PEKswBCSSnS9plI=,tag:/fvb4P7uAFHiGutviMzICQ==,type:str]
                                    key: password
                          resources:
                            limits:
                                cpu: 200m
                                memory: 128Mi
                            requests:
                                cpu: 100m
                                memory: 64Mi
                    dnsPolicy: ClusterFirst
                    restartPolicy: OnFailure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T17:25:17Z"
    mac: ENC[AES256_GCM,data:CPb9VlLvwos8izxyzl0frfs5M6wyoE1k0BwzGj9JaTAzBqQ33c812NtGYaCHuroX4ksqGYTwI/ihKn9ul3+DAks66/O1G/4JoqV3IcEGoUSemGOYUWJR0gd48F86Jk+3gWtpNa3E4TxTMB81X/eHhgZV1ci+KI09VwfQ1P6Pov8=,iv:SX9QHocxUEKrKaxZdQE3iv7F2xGX0LzQHLDVT9N1shg=,tag:rWSGvlZASgiTcrtzH29gaQ==,type:str]
    pgp:
        - created_at: "2023-12-22T17:25:17Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+PwaiUwbTN1lJblgFNZrCBZHoCpPEVI1RBhutKK6cwDjZ
            Z/2m/Zr0xj77xxlV4y+5dv0JripcH0ZCTQKhTWaOGhoylANljaHqE3Ee0eGhN8wC
            7V8sFUmY7GV73sZ6KUIklvsFSopPLZ8jypRwuvPUmjgETNdGT0bBBf5++Ak6Vuxk
            +IZ+aU0tLIKhPmsOusLPZBkRZGoVJpoSaWvgO2N90pkNNQcyiskowgezFqazIaYs
            L0Ib7z9kJUmZTY+OBZpxUE1Tn25RHKprT9KW6RojDg8f32eUE24gUnWgKL2t0XvT
            EodwlKVXYnvapA2P/h376EuO4ES1K+ko2jWU6jdpadJeAWZVTO5U/SR/wqS7CJ2w
            3p/TFFkp/peqVqz39FlZhR0qwjwiU8Or8zJQj0rK9Rz4Oyc21bfIVLlsPOm4RzB5
            J1tvJtQL6L/oQ2Dkjy6i7TqSB3Q96ixBs35f3HIhKQ==
            =aR7j
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
