apiVersion: batch/v1
kind: CronJob
metadata:
    name: ENC[AES256_GCM,data:IF3AqqyslAzkgzkKM3/C,iv:WPttllyBngtiqqHKoLAbqPIz3oA7wsIatbrwmDpwaoQ=,tag:9nJ3sZjS9Lae1hDrD4fFsA==,type:str]
spec:
    # suspend: true # Uncomment if need to restore DB.
    # every 4 hours
    schedule: 0 */4 * * *
    concurrencyPolicy: Allow
    failedJobsHistoryLimit: 4
    successfulJobsHistoryLimit: 4
    jobTemplate:
        spec:
            template:
                spec:
                    containers:
                        - image: ghcr.io/cguertin14/mongodb-backup-s3
                          imagePullPolicy: IfNotPresent
                          name: ENC[AES256_GCM,data:TbM44B9e9HM9pfRXvA==,iv:0od2BxiDo3Z/WZEYGwMLtJtogzeKl1BjfwhWntGg6PU=,tag:V+wOPN6AhJAgn4q3lFxDBg==,type:str]
                          envFrom:
                            - configMapRef:
                                name: ENC[AES256_GCM,data:8o6ZGq/f2h7+EGiWDR6nidD3VSA=,iv:FzTgm1wT9b02fi1qE8ghK6mTxWVCKR0kMOV34LaFQZk=,tag:eOm4ldqoZ7MHwGSsZtj/bQ==,type:str]
                            - secretRef:
                                name: ENC[AES256_GCM,data:ENwChbwVA00g3kb90KavfOtTKu7j,iv:S9yRkiFZ3CIr5B3OowTguIYbwj6CgXztxzfQbMMaNdk=,tag:OR2DJmct8WZO66XcSjf+EA==,type:str]
                          env:
                            - name: ENC[AES256_GCM,data:7vkIpocq4VBsYsJi,iv:63AOZ5YBhayu+8PAHHvFG85ZckmYB+7mOkFBZsasAVA=,tag:LUkIxp6Q1op1pNJmkeKV/g==,type:str]
                              valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:gV+r0FAi7zBZOzRtjFoSbvxjIy3hOzbuuLgMPyrKGx5w,iv:eAC/JDkJd+ebkGiLdYmzf0x25Hby7Nt1C/YOBQQmTBk=,tag:DPDDxSdxKE0zDTUzsNiYew==,type:str]
                                    key: username
                            - name: ENC[AES256_GCM,data:t9IwxnM68evlucR8,iv:nVwJfh+8UvshGdjX4NUNmZliGcmjPUTAcn1IgeHZbCM=,tag:ynWqZ5DSZhbIF8gxyoXOKA==,type:str]
                              valueFrom:
                                secretKeyRef:
                                    name: ENC[AES256_GCM,data:ZGlbugVldtQglBXh2PHFWjwEho31T2skwLL8w3BSarOO,iv:Cysc3F0jx+uVipm00ScuV02xkYZnb3weupEBpvp3K1g=,tag:0qjr+v3Ioxkj0nbuf/CdXw==,type:str]
                                    key: password
                          resources:
                            limits:
                                cpu: 200m
                                memory: 128Mi
                            requests:
                                cpu: 100m
                                memory: 64Mi
                    dnsPolicy: ClusterFirst
                    restartPolicy: OnFailure
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T03:45:36Z"
    mac: ENC[AES256_GCM,data:NvUPplQV2ZMrRrZCIelir5fh82Y0Xrla7JCL86lvO2BhZdo4vWX4NpeXqs3htgnC8GgygXvs27e8RU0x1EOJgxi2wZywou6WztbNSVEDHKBzMrrTGUHtKmQyTECGrPtQ8rFX3HQ0/CFPtydUxI1QMMSr4gJsZQJzi97wafY/XqM=,iv:LytmPzePpZjT2V6I/SWTSnyu/WecbnksTC1ilH7rAl4=,tag:yziq1HO0E3UcIw60r5dKng==,type:str]
    pgp:
        - created_at: "2023-12-22T03:45:36Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/Zz7WOA9kM+ZlFLCzCL1Y5mLIuTCcsZpyTlqJviqLlAFq
            Rj6UfiiM11WL97FUXXQtwHjIM1DMNycNQ/aL7ihlZk1BltLsblYTuX9JkLOy1vZS
            NcP9L44IQjW8hwyvOVX5dJ5xGk3cJQ0hosZF8fjTnHKlGrc1QIX4omXDDi8PI3MM
            ykrdGB3JBmGylqCZnsXQjjYB2bssI246zjjTOPjBT08F0HFsHS/WreVcZrA+Ew4C
            heYnZhUjc9DNqmQ3Qtf7+1qS9+q5PjpeScWlaZll3+6A2x/DB3a0uvJyhSD1LQ2N
            cvi2LVIy8vVeCuFaq7i4TE5CKacj+Uy5dT2oa+6HjtJeATf8B1IGXU0rnvxqR+Pm
            IH7EcADnIUdk6PNbfobNyJN8fwIHx45//hwgYLpXeQdguxrDJ0A2Uoi1sLWgsR7M
            GxwX5uqYRFOwecdVrHQulw9Y/SdXiklcbyMjVEM7YA==
            =Dd/V
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
