apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:GpfYBf0g6zZoOm6lQQ==,iv:bcgUEI3U9NXs4XFZHSfgwF+hevqMiKTwXGIu9GLO2Js=,tag:g4BzSm0JywT5j7Xdkpm9Wg==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.4
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:Rs1gtpc6/16S4qeSlw==,iv:ZakxVTV45XYEnez1lgYJSmA8+VCQceOvS1f8P0HfgXU=,tag:UsCAfkHJECjwSGwYNd08hw==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:12.0.25.7724-1
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:Oh1lwEDKvoGmnVY=,iv:2axA2/rRyJP3sdOECpigWNyi/c0JT098fnrcZ2Z6tlc=,tag:8DbZCdFe1IPrBpTAVl8T9Q==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:pq4lqahMA+1lxSRCCA==,iv:I0iTn6WoNGHsLBJ6L0zZfp1PcZPe2MXUhKEJ0wSa9J0=,tag:Z47r5nm6RBjUSj9y9jk2wg==,type:str]
          db: ENC[AES256_GCM,data:qH9j43Q=,iv:XZVfLCzZQg1wf5jdxBQy86+FszEXM2TKeQBQDufQGpE=,tag:sBlqN51GF3J1xaiZ5qf2aQ==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:Faz1eUZtKGbqat08kcY/pLYcI2vooA==,iv:tyR6s7yPpWXy5eJXmoXPwa9KC4g4Bf6Xf07ajZmFTMM=,tag:pyxCVCTXbsa2U8Bw2wR5mw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:dpvvEzjjTWmt,iv:JOOdSvhTkaoLqieqicEsJaYM6yPyqBGv6V6FlmNu9+I=,tag:ICBp/p2jKTsvBa7veAVIHQ==,type:str]
              db: ENC[AES256_GCM,data:qoo+x+kUJAeQvYrLLy9s+5NFo2FT,iv:dzOS0XsEqrs5wweI1zPJc8RddQ4gvuEuXtRIPy/fdZY=,tag:ByYL0uD7fRCTCFhEZ+y5Cg==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:uf568fr2DGcQ8HQ=,iv:sktrMkY26qYmH28FPKuY5NIu5gVtB//tathhYCM5cvU=,tag:VWRi2ggg2n8L4/1gXYMkiA==,type:str]
          db: ENC[AES256_GCM,data:0GjA8rM=,iv:15Fad83MAS8YqlKLo96dEdaMgy9BI3x9/Pxvnxi8DJ0=,tag:lWwAxPI5Zm42hbdZ3PA8Jg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:DJByH/sH2pZu0uuFqswHJ3IeuMw=,iv:yoAsogu7JjNxBoz3QrDuQNjOLEOa7LwNvbqaS9aF70w=,tag:z6X9DKiMMq8qU8IM65V1NQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:hVWvgOAPRYCKnqEK,iv:AibUIenFAulNdghDjjXnBTnew9Hzh4n0WcsSJkbiLoE=,tag:ipHFeOmKURpGgR7hphquXQ==,type:str]
              db: ENC[AES256_GCM,data:ptKuH8E=,iv:vI7sDFwTXpDIQ50H6Kitp83/QPfoi1pG+tyuyioqpmg=,tag:K0ZVtTsUTdXGrsOeQ3joCg==,type:str]
            - name: ENC[AES256_GCM,data:G8EJ4FPjOb+LJhe+DZFuFRtXjBY=,iv:yRNgOcvRy8PVXkquIlYVYwXQkDmOc6ETbc/R195v+ec=,tag:UNm46V0bBeMSTmSRQqTD3A==,type:str]
              db: ENC[AES256_GCM,data:iSx3Fts=,iv:iXiwyypLkZ6iWzNuIIJcjqe2IcQErb2gf3KnO0ecsQc=,tag:U2kQvmneK3ZStvSQZCqoeg==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T04:05:07Z"
    mac: ENC[AES256_GCM,data:n/mHknM2uaaT4pb1w/gBXvfCLWjg/hnvBoXfle8BwJ0I37hzeN0L6uAz7T0HzjX0nTtUqSLmOTFwHfbZFF7JgGcGbgW5xUIRSLtRM+VxVmjhwAdBowYOaXh0eVwn/vQw09YwVuQzAYLDC43p6onE9m7GEZb3JE7FOVBPuMoxwTM=,iv:9Mz7vgLLSf6WDEfsBCM1zeQpop1EYKmzBkfYAYhLygE=,tag:W+iYIk6wUROR1QXDvFtrNg==,type:str]
    pgp:
        - created_at: "2023-12-22T04:05:07Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAinpXDfXLbfrw9+KmfjK3fqY4nIDOaOx0JxPPUlCZqUWJ
            +TO/QP+awM0PXt3UligN3YSUCAEsrVNeqSMAMYlAUNLVNQRMlYnZpjScvS+VFj05
            jjpbrmLddzGjh81j2066qRNG5rMBhrEiqlbgEKE68GYKv0tao32SzE1wBCMRTgUD
            zsTDo2C4C9oHDmDNB/ZQ6U6IfKt9S8yg4nW/vHFr7rekBwks6wCSpC9cXJeb1Dfi
            aLBc3I3u6gzrYxkKoWV2Z1cggYocoliIabah3ygF0Cb4lHnUVydgBW9Uw/85HB+c
            ux3bYtqc/phRmPl8WBuueeyI2gjMDB6OWXCHjkMFgtJeAZ5dl5EdYZ5GhvWIjFNE
            a1z1/PGF1DZmSymlDq2PnnwHQXfmmSx3/teecS8vr2PFNJyTiqrNBCp6DYtJU/xL
            Y8E2aA0c9XZh5z3kPjAop9kESPQGnzSWEJgXfgTqAg==
            =LG18
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
