apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:k+hKUI/ktqtaguqy5Q==,iv:vyEimtKARjwf8KGq3A+iBHxDXZJ9l+DKMv3Iqn6zOkU=,tag:rJEcQ9OWZssv4PHFKemxKQ==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.4
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:nRMtfj2P5IicZt4roA==,iv:WunoEI9uJxap3gMn07h86C0GEt2oo0Hmrh5Jj1w+edY=,tag:Lxy6Z5oS+8BTBbeRlDXXTA==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:107.0.0.8465-1
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:hgqq4Ar0JBRRL8k=,iv:MDLMKUIGC1ZjYjDgOrca0jdTet24Ejbpasc71/BPNqo=,tag:Pi5oNLvni6WBT3/dnDbvkg==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:BTnDLN/J8Lq1zRcntw==,iv:q0SXhRo7VGHO+sl/kvBFLh92QQqptEvLCOKOOrI2+wo=,tag:STZgr1G5dAORV0FoPuzjQQ==,type:str]
          db: ENC[AES256_GCM,data:piZM3dI=,iv:XQJjqhQIfeOLTazCMTQ4FfXCnp0nj/mjq7osah1Iigo=,tag:9IdNOzTUrk74Q/VvV7EBbg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:Llp7h7GY1a6Ln104XMum7ftHeHNdOQ==,iv:B7HfR3bilHidT+iD5hhpc4M5MPhNgCtnEOHq8GcO+8o=,tag:8Y53Fwx8fpL/Hoz+EppehQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:N0mTtaHxOzT2,iv:bBnB0/vwiSBFhXW8D5JIfXDUtPjHKZZcmA8L5NAMs2Q=,tag:s7igW+UxNFWTMGHSeLJ+nQ==,type:str]
              db: ENC[AES256_GCM,data:5MD7I3kY9pQuSreciHu4n0OLUAZb,iv:vlJIx738ox6zmb6Xk+MTPV0K2kzJb+fKNUKrdtKpn/M=,tag:lfQ2DMjyEo+YxufiCg3t8A==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:mYAPxuMIQozvrbs=,iv:h3XNijuucHbMisfnr0gxX3ITQ3aIqEH7fbXWEtEuepE=,tag:dSg93EmMU8ReAJQ0G4Mxxg==,type:str]
          db: ENC[AES256_GCM,data:xcDGdwU=,iv:qpU9w4nDBq/iACpDv1ItNo0tzExbtuBYn9lB2in7BGY=,tag:aTSgzuRk2k0RllDThWjiaQ==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:75fVdPnQrauyh9abMdHbGChgzzg=,iv:8+EXfyWVy9fXJnZJVTEtExDhDzj56uYYwv4PSI5o8Uc=,tag:/XXrp1gwk5KhJJ6DETPbJA==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:bb+2MCh246J8hn0N,iv:kqHeOT2dY7cOKecewRSHgieZpzDf8WGqpvc/qPpPRc0=,tag:ZbHB93rOdBynIA74EG9r7Q==,type:str]
              db: ENC[AES256_GCM,data:wbcIgqk=,iv:FFOmOLomdWr18gpsB49KRDGGxob+kDAyBo9p/Gx3Seg=,tag:/tDERYM3UUNKht3mjDB+0Q==,type:str]
            - name: ENC[AES256_GCM,data:vYxWomp3jXJtZDob2NnrwWPG1Tk=,iv:ezfCBBpk1onHU+tqo6rpmTRi9bKVXfK5hEMgQjPDXl0=,tag:iM/ET8aRtgACvs8DBcO/Wg==,type:str]
              db: ENC[AES256_GCM,data:yzahqNA=,iv:pBjwjDzLCtIxesl5QmHr/lPRrYk0RWh8CJz/pdFB23k=,tag:yhypiuNHLCvTW9TuRZWSTw==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T05:36:47Z"
    mac: ENC[AES256_GCM,data:ayEXrADxL9J25Tfefcd16Wlb/tyJ39jD3Qtn0OxoxcSh1T5thE6OYNzB/vo+E9YpOfySndk+NR03eLmVmVd4QXnBlIS5ZNmG99NXhS5bHxrxNdBKbkY0ufBf3QGRtCTwWHsNqPMkeN6SHOyTw8amXwob1J0hPSewKHLrQmd4PKY=,iv:dw8T2aH+bLXKx8A3dd9Sjl0xa2u7YT5ccqLNDzAl4RY=,tag:b9easqxbK0id8izqOayZqw==,type:str]
    pgp:
        - created_at: "2023-12-22T05:36:47Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+J9zIfRRuk2QLixw4VOzNqOdKtd4l6aR8Z0oYstSPFWmh
            b6EINtlWmhMs9c0uEBwuQjmmU83LFEC2hluqYuFuTFr1A2GYtIcS3zcpnt5JGq4b
            JkAYBLYOa+D2s0Oc08ODB601ctoBbOltoCQgzSPyy1Cv3VcCyJC8j4KYsIejlqjC
            cMHxbupw9gsJn/GEJ9vRbc+j+snDSM2miX3s0M2qU6OZC/3Na+hYl71/fpCGgI3q
            Ih25OluFJ1P7O4eumRrRsIZ40JtdP8d8jCenz8jG8/CADSvEkKf9vOUVvj2SRaJR
            P91TDrDleu7cwwLIPfq5MC4SimJBsvGovhn5WJzzatJcAcQEbCX3a/7xmR2+ZIgw
            gAOwtckCC3S0//wFbaJfNgNe1InkGE7faLnWM3bcAUIEx/T4W2jQtpi76HUXQ04T
            yFRvOykwxfGfjkedVe0LHFJTHGv0lbCXIv6vXs4=
            =RdY7
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
