apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:0Svu3XNsRoBWj/TbZA==,iv:rBdmKODAUZcbdc8J/6mRYKlwvqFRivDkvhZgqzH3aGk=,tag:uuHLcw4867YvYa/sHXoVGw==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.17
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:Rfz73MUmTfij2g+Vdw==,iv:Jl2WqxY1HCUQtYZyHdYaKT7N+TcQNKB748hEgCygqfU=,tag:WRv5V+hDWhPbW/GPvco5cQ==,type:str]
          db: ENC[AES256_GCM,data:Jj2Wjf8=,iv:nhv1BHJqO8Mzu5KzRt5+AR+c93UDTEsR1Fj9IPenIeo=,tag:o1TZ9jQPqdYxwUkCnDcUGw==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:hZhL6/5RAydWDWMgfbrB1pPJOD+NWA==,iv:2WUTm8hsivUNJ5lpTIUoTbiCSf3+E8CSzsChHeQVscw=,tag:tH5WOrQJ9IUIIvVp9bMI+Q==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:RYev3meAul2r,iv:tCi9CfFYC6bERXconBCa1MmwpywhzWfTupEqLomi8po=,tag:gJjgbyyqrhDfB6JExImYCA==,type:str]
              db: ENC[AES256_GCM,data:kkdYSEhw8zb0T9fpt9QbOXTVMmbs,iv:uASK6Pdx5BWoM0hIpcTTeT5UHtsVevwlUBCWBdxDrhA=,tag:DdZQHnqsvivQy0yEo/QmRA==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:UfYr4F4Mrw6M0eE=,iv:TGhDGlw3Fkm9/EEWpvDlHasVAu+DkEUeJ7CHz6zX6qA=,tag:Ur0tPswYv4Fsq+e3f/jXNQ==,type:str]
          db: ENC[AES256_GCM,data:czB7pec=,iv:SVVwLpXESlPZZ4+Sg09bKVfa+GRpM7NMw8eyOJFMoZA=,tag:sAiFRVzuI81570CXgDMpyw==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:mETrsWaHuld4OHWfNbscQqD0Bhc=,iv:0wWJzTP7PCs5tbH+jH91qCbkOFjLWAvh8bmFx/ti7oU=,tag:DFCRBIM3i4RsJKadMPBHGg==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:H7ANUuqBU3po1tW+,iv:EXaMYM1TUCQ82tAf441V1K6ZpSVnN5yiqhU/o0nixfY=,tag:iolOZquc0fnrZS0+6TzWOw==,type:str]
              db: ENC[AES256_GCM,data:wCF3nu8=,iv:1HN8IdszXjIQb+ocwgKrhFLal0t38DbP0RW7lNHSSdw=,tag:ExkrIRSgatn/y0YzcU9vDw==,type:str]
            - name: ENC[AES256_GCM,data:b7pOTSXOPo/Kvzrg3f6tHch5c9A=,iv:gDBpfLWJOMnSWpr2gYMWef1kJyy6YXpzbTlHRzA8Wss=,tag:cFMNfuG+h8Xgpd9IQa7abA==,type:str]
              db: ENC[AES256_GCM,data:IVE4LaQ=,iv:f/OOCU+9Er1GkfASjoHxFV8Q4jSQsrvVpcLYVJEaOpA=,tag:bpltAbBvvt6jlSR3WIKXHw==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-19T20:59:45Z"
    mac: ENC[AES256_GCM,data:0S2A/RIjn/3arkargqzX9urCmETv+9DISAZBaH5GDy6ptq3ZATogyTqBSLPkNeVaViMghcQpFf857X5zOkRMy5h2j3veWOt24cVDUIlcLrK/KaCkEwmChyEdDqbnYR+UqHQ1CROPN3PU7KUpKYaNuVfGvqkLrk/3GtwNV7WJB80=,iv:HSJndLEwsM0oV7pgSgHbeyReiL29KRy9hrTit8nSuCU=,tag:YrzTJkDjWobyxl1PmzBS4w==,type:str]
    pgp:
        - created_at: "2025-03-19T20:59:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAjgfMYA+mKHgZ+ZedoipD3Lm0S5icsPPX8+LPA5Ciuwr9
            Y+LXuVN1ecXOhPtnsx82mLi/4TwXpr28jnAGOpEgE7UITaJBP5awaoRJDkoHC8qh
            IcrmnuDooIAplDj24wx2HlmWn/2kA1+LCha/OtfOA3HLxmVR4wj1t69RWMggY2wh
            OUJyN1aCOWkDJ/CEe369I2WbjRELEXcOldQqxFY5TYVcGLP9w1Ne2xWKV9gBqmOl
            L2qeiaQtSiLjHjJDwgnecSqSgU4oy3kv89czpy5YJO4+2UKdoDx5t/FEioOtK8uj
            pRGmw5P5G3VbRemBORFe43Y+xHuB8FueZkRW3KQYRtJeAdIfKwPulI9BEqY8mveM
            0uHDgpyxFfH84L6cbjDrnyxzN7GnohSnEN9PuxDQMGwbFhILSrPS0Q2ohEtaB1bc
            bFBej3lkF+QEDv7KMQQk70W8CdvePhB+wgjYgtvZYQ==
            =z8gE
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
