apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:3rDSfL2UVme7R8o7/Q==,iv:guLEoqUk5I5f+Vd2xNbnvZnUz3K7wkj1qRD6FpkvH08=,tag:2XXfKYlUrZHfQjv3Y0aTbA==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.3
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:j6CMA5J0A7+5/aJWng==,iv:UNJrVbvyPhnDCxb9wThGIIaJJG4qy8hyDjebkETSsF8=,tag:bd8APkIVvd+LTh6ZxyjGBg==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:107.0.0.8465-1
                        - name: ENC[AES256_GCM,data:XLRn0m9T,iv:njORnALFEf/Wj6SL82Q50Z09A/yliLBW8S18ZBsbc9U=,tag:MN+IvK88GxHJ1pvtr5OjkA==,type:str]
                          image: quay.io/cguertin14/mongodb-raspberrypi-docker:7.0.3
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:EygxkwBya0taw10=,iv:1WCNyJpYvdKOwgLLppCqeBUOtdzuYC7EceW58b9L1Aw=,tag:wKFW5hR4wsKNqKgIizkEUQ==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
                    storageClassName: manual
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:3jlCcYV1mON3tk11ZQ==,iv:ICrayiAysgdSZahW3q7zm7WfNli1I9E491O+uWtJNUI=,tag:PIYvH4WzktKhz89NgzqRIg==,type:str]
          db: ENC[AES256_GCM,data:ktV4bPk=,iv:hUHVr7ZFs5e4sz1cAFkzwnhZp56oxkj/77y2dP1u2YQ=,tag:Ii1xjJx5Vl2n9UmjV4isnw==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:90hchLsbrQ842nJktHCJ+nzAh5OojQ==,iv:bPnmESLazh4gxuiMGQI2oRFNO3AInivAy2qUWp/zLPc=,tag:308KBupGMwzo4BBWoX/zHw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:UDN/7O3thxvK,iv:j9X5Ue9hPC5tZtdtQ1222bevmApTapQ/6D7CDFM2+MI=,tag:rCelkvfPBxHZf67gMlN+Hg==,type:str]
              db: ENC[AES256_GCM,data:1KHHyYOR3lmJDALNIrbhyI/jmftZ,iv:bSwR/hUtHYDQNjCeJqsK3e2BNQKYvNbczemYoEd3I4k=,tag:vRdpIxb62aoiS7v+Y6qKZA==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:IJSrVLaYD1Vq5V8=,iv:9snOSbw4w3fFzuaq4lNeUhn6aWM7m/DQyprYdDQXGco=,tag:iuV2LCzUNVwuA8CbXOIAOA==,type:str]
          db: ENC[AES256_GCM,data:b+bu4o8=,iv:PGikuvjVFdBKxFyjz/s4kZkEfnFsSdKMSzps9ly6KpY=,tag:4NPkMFgUS2eQ29bvkYYAYA==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:5lGL0S1xny5dVUg4Yu0wN5Yi0CQ=,iv:LyqUXiWYFn9WO6BP3uJldX9M8iEEN2YiOhJ4Q9dhUeA=,tag:EStVZPYBCfr3aVZFOIPVGQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:2dLGW62Cd31Pm1+A,iv:/y903cGb9Mn00YNLX+csQH2tREiG4h4kEgHvs1udPq4=,tag:859Uzs5YP1OAlQgfL1sECQ==,type:str]
              db: ENC[AES256_GCM,data:BqAkrL4=,iv:jpQ2EafoZnn91po6vEuQAxNlh+7PPxF3H6ovC4rP2oI=,tag:LH9/LA6ShDkasYYq2AaAuQ==,type:str]
            - name: ENC[AES256_GCM,data:nga4KZ8IDMAObN3FDLHJ+O3nj4s=,iv:/pSBRYYtfPQH32C70eMdXl2df32VN4hUeZvF8xGyRPk=,tag:I0fafcndCDbPnCDJPDgdZQ==,type:str]
              db: ENC[AES256_GCM,data:H/v5tYc=,iv:AZZLfUwq4wbbo1TIV/6OZDSuC1r2ABJt6j80PuI/HQg=,tag:RTU8TbP14CrzEyDqYqf+jg==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-06-09T12:42:52Z"
    mac: ENC[AES256_GCM,data:RytpgUq4kOY6oBLNdXJu2OJNNwhX0zt3I00RxaGe6pFBmFSJFr8zCMrCKS+JFSbcqWP3OSZvsr4iIsOc593BXV3EGZ+pH+dl0vgNWQf96UMn5V7IZHQT+jNULGWWJK1MzNVeKfNU2CbyrrNPIM3E9elwqfr0Iv+naTPegWyFRAo=,iv:nGw2fo6wQipcEl7GdKoZmZwBwNnP7DnB+6ljRb+dfDA=,tag:qKv1KOUAY5iNCY3x3BF9PQ==,type:str]
    pgp:
        - created_at: "2024-06-09T12:42:52Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+Jl9zQ5sHKVEPEt+b4bRGFSDcNMnaVK4etOW6TSasbW4X
            U/DuWYeixFWzoqZ3fsvHGbbYfP9lj21u/NaI3GS37h6HqPl0uWbZcPHY7TQ8KwLH
            GDL+R5p4dy5Xd6c5GfM3MQ3ZvxH44OQQrFBJ25/PhMOYZFnMJETWqkwpsT21MK9l
            +d2wdJVk7KAExEr4Ki3M8vjyRB7lI+TqeCH9k2syszj2dTDJbNKs3R2izuUApiuV
            7J19VtbloUHCAhmKWe3EEB2jySygv2aOnEP4UoS5kKLs22VoGoJ8BWXYeU9KBbKX
            G631a8r4aw1Zqfb1eW+q26bd8JVRvxbUsTvrrF/eE9JcAfQmi89fBGufsdbIfewr
            o4+Upofc25nmTwBrUQ17PiNhlVBm7vF0xQLaTcJmSA3ysF0KTzYw5ZW2DEpioxVf
            m4oA4seUwnx3zb4tkL8/RlsK+29BPzd5Lqs4XVU=
            =r2So
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
