apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:lOrLcF55x16lcPfnRw==,iv:4W+muU4r66h724bo0l+N5WAUq8OGyUWGtfo7Bb5zYCM=,tag:sXSAacYtANkRttYYw/JNQA==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.17
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:p4muwj/WGxSuMLScZw==,iv:83GxFX7j3ASqZpqxWrvIWEd2IRVi5lgGhkLxxb5SyUQ=,tag:JmroH4lX+MlfAGO09Wv9sA==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:13.31.0.9376-1
                        - name: ENC[AES256_GCM,data:r7TFM54Z,iv:eNuFlqQAueuxT96wojUQiSZG1CEdwjzm70gpx2vp0v4=,tag:wbS+dlizrK5MvzCi3diyOA==,type:str]
                          image: mongo:7.0.17
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:FIOp1OR9N7NUIB4=,iv:7XRwJWMjjwjem8Yg4vyq+dyxqM2MGLx/EJmqAf0x3Dw=,tag:kPnzIrE8X/XEgDpD1Uy/NA==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
                    storageClassName: nfs-client
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:F0ZptoauDAYPzJHwdw==,iv:fAdsNlUa41bBT53iQThoZs82K9O7HbhEKBarJeIAxbo=,tag:NfGDbPXQmKwbgEohdmHy6g==,type:str]
          db: ENC[AES256_GCM,data:xgngwgY=,iv:omdblnf3+YfcNTiCGK28XDEK59xVG4fy/Amgt8EHsyg=,tag:wFDrBhCykpI4ORYYhjV/Zg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:ceXD8iV3bmk71HCDss7rBrlnRujrBg==,iv:57JXXYJPsBBSfc/x5hebCo37xR8QXAm3lmqP72A5jec=,tag:UqB4iaWBkETAJnwi0JAvTw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:BdZix8g6aZZ1,iv:aSjEkE4hIoa6N3QqhP1aRP9tSJ4rHoooj3tzaCsxFto=,tag:L8NNJ8RHv8Xn1qaVuTSu3g==,type:str]
              db: ENC[AES256_GCM,data:yGstEQ8id37b6BZfXNgrp4VewAR4,iv:aglZwkYp6fYNT+wrYCTwpS/KuJy9v9l04HarLWfSHLU=,tag:ydBYjPQmokgMKiE6IeQDcw==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:oG52slLViL4ZngY=,iv:bkZbAKJ3HZqBxfM9XkXPnG1JQcFQo+V/Kg5VKBX6h3w=,tag:3Cx64Am/7JCoxFOvNWDMEw==,type:str]
          db: ENC[AES256_GCM,data:EP4Vm5c=,iv:enyi+cK+nphw/jnXK3cEep0bIPf5sJAHcLKIfEeyZD0=,tag:gDduEPCkGCxzo6YQr48GZA==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:jp7f2Y1TvjKDNSOTE4g/4BaNQRA=,iv:j4OzVo88xBD5um/ZnotTB8/8CWsTdBxQa/No+4fc1aU=,tag:5NVrM6X2ADt8snvPKF5aaQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:mpBmR5Kq4vDV/aTy,iv:ncEg/lO1CZO5OHu7QLvNanjZXU6KNp2U3WG1TCUCP/k=,tag:9SZNbRIfwxZMnqzJewnuwQ==,type:str]
              db: ENC[AES256_GCM,data:A4ucyik=,iv:EsnnN5Kpypgu4eU52it4F5r3Ys4/daWTPtlJmb279jE=,tag:n30ygl1m/sPCjIp5wO41Hw==,type:str]
            - name: ENC[AES256_GCM,data:R86JarIoU70paNEwo2mQB6sWoI8=,iv:v0VCu5+HmvbVw6Wao+q+FnMBCZHeq4nXivSPorsTAac=,tag:caTJOr8Hi2/eJ3sVGkHa1g==,type:str]
              db: ENC[AES256_GCM,data:xoCi5vI=,iv:MfoswFX6BRgCakENB1uYUQAIcy4tPJOJtOuNGp8b6zs=,tag:Wnk7ykLetnRxblkJobRyCg==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-18T21:01:18Z"
    mac: ENC[AES256_GCM,data:lxOyOaltrFyhNQp3z8AiOkBxa7nQYk0CMZAEWlvN1Cc55AsVaoRiM8cmNp8sUSbn0e16wkVCfjXzDmrA/mQdjRulKoCb7EOBA3hz/0O0bnGtTMHrJU3dEZxHbAX8wtDjFNllCWBuSuwQTU49f16rxDpvxubDneEgq1kCjxlqm40=,iv:SfImcwK/8SKEePw+J0NKtlgQENNysHnoIxXGRkjsqG8=,tag:msOmRmHndZ8jwV+lTKsszQ==,type:str]
    pgp:
        - created_at: "2025-03-18T21:01:18Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+PGPXk75ZLZ7LfA0DiC27XPNj4lp+FrC78KQgdfj/Tjc6
            nSRLQ0yP7b5MDC7r8ABXW59LI5TiEUxZhCfX9jlgOeorGemsrGoPFtKrIvTusVAr
            huAn9VoFeeYrCpbjWV725J+dQGk/okiz4KbdpJRbeaO1NyqSCReEBXD/qv+janws
            9ZxV0LfYInkFzV/WUXJWbZNlXEeEGN6MaB/8fCo3BzYuHvtL8/He7RnqmpGsJ+8Y
            bJiAvFVvivUk27ReSJqN8ktVxrpXLpcly1SAmiYYpEofvBfRs90hK7ey16cx0Tr2
            acqvvhQIvnW2pIbMH3A/0KwXeYsUm2O2tO3xesHAvdJcAWWm/qt83EcdT3T+bSWh
            M/AlD/zj1UDZpeUdAMOojdfrSNRNlI/nd0qf6jQ4WUcEaax+T1yr9NzA5JyTPyy4
            c1LgQKJ9IaahPojm0c88mb1ECXKCT5SoIhhHbI0=
            =mAZ5
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
