apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:zam7/xAy+S3vjiUeBg==,iv:zHyruB6MIOe+tktXFcrZAHArXIABkBzo9VWowj85TKQ=,tag:Ys9Mss9QamHNI9H6YYBXKw==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.17
    statefulSet:
        spec:
            template:
                spec:
                    affinity:
                        podAntiAffinity:
                            requiredDuringSchedulingIgnoredDuringExecution:
                                - labelSelector:
                                    matchLabels:
                                        app.kubernetes.io/name: prometheus
                                  topologyKey: kubernetes.io/hostname
                        nodeAffinity:
                            requiredDuringSchedulingIgnoredDuringExecution:
                                nodeSelectorTerms:
                                    - matchExpressions:
                                        - key: kubernetes.io/hostname
                                          operator: In
                                          values:
                                            - mediaserver
                                            - nvidiaserver
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:SN6n6/Lso70WARs=,iv:uKfea/zYhQoz5ArIne6C64nNMNmRyWhO/yCzuXd8SEM=,tag:mQnfw+H2z2YP1ACvVK11CQ==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
                    storageClassName: nfs-client
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:rY6A3NkfsAc8LcJp/w==,iv:u1OV2j6NH10t2JpebAHfUpbYX285RniQpkwHztebEh0=,tag:cVzOqH41f83LPJwaQU4ELQ==,type:str]
          db: ENC[AES256_GCM,data:fUa3qIE=,iv:Ew3xP55/UZVHUphKEakvQZKDUwF9SsdoRxVNphDB5lM=,tag:+hHgN6d4Bs8RXKkBJzqgOg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:AauJyVGlsx1rQimZwaqD+24oHht2qg==,iv:5WPD2Hag1DDJB2U21wPn7bC/l7YQQL4gor+SfbiKadA=,tag:czAttvAgvUvBFJGbArZunQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:cRTe11GnVum9,iv:IitOeqyhPaDiWoIiQe4kKo9Cvm5+s58M8J0o/DSdbZs=,tag:Btsc+n/U2PPauAYwi+EsOw==,type:str]
              db: ENC[AES256_GCM,data:p7jfFl0xLplCTW2OOYqLMmwb+awy,iv:cUvmiv1cPzb/7Wt9t9Z8uT21I1Yq3j9ikC6zA3oJzXE=,tag:LBmHCUbfRf4XZQ02UbssDQ==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:9Qo4mpMFFDQvVm8=,iv:gCjlEt+U1fIy/erCeRU2LamxY68h0w6SA3p11TSRBUg=,tag:zrb+WngAmSfxNQprjVf74g==,type:str]
          db: ENC[AES256_GCM,data:4o99MOI=,iv:gzJDzoitG2Mi0lw1AfLkh5V7nIpv3ViFg9OJVAF2KQI=,tag:th+LKK41CFte5eP8K1pPMg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:LJ5cqB/i2+OGOGrfAkj6c5BAF60=,iv:vas31Nwm06P/caN8gkG9xzjAn6pUVOs3zl1rE6+HT4M=,tag:Pk1rdcXtcHM1+++xmFtBfg==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:/USkI2wvz/aJONui,iv:qU3t6rxZqJb0cWnK1594NsTD+PugJAhzu8CDajkIQTk=,tag:p3pFDvliLO8ozbCd/Hb87g==,type:str]
              db: ENC[AES256_GCM,data:Ga5HzHo=,iv:sMi8Pklom35Ajs54kABcAENwCz6rc7mP5QGjzbeD73g=,tag:2yJAKdTe6o+DRREWgG84ng==,type:str]
            - name: ENC[AES256_GCM,data:MYwz7Yh/ii6pEPOnGvDeRDAS//E=,iv:b09C9hNCsDyMVlMDNTdinp0fT4EC/q1+uoSGzwYxB2M=,tag:WR6dJ5jdr+lml+EzX+vfoA==,type:str]
              db: ENC[AES256_GCM,data:+nJ6CiY=,iv:kFgPgtLIBssNw8w524DcTIqhDDzHRXl0PMOGUriA+S0=,tag:Zc/UOLc16dmheNRvjLn8Cw==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-18T21:31:26Z"
    mac: ENC[AES256_GCM,data:fA4Gvpf4bB/HWosQWAjwJPz5aLRm+ex/+xdtLqmaN0JYKiyu1a024TDrDa5uDgUvT5TGpJdHBzEk8DyNSEhESM4G4khzj9PTPqN9oDAS7+nI6uX14zmD/cAT/hbt1Srn7JxOhu/aiMIXJnRQ+THSovZkRMcc9B5eHMyBtDl0yPI=,iv:iaacJ1NVl/4G5g7kEUOk0lAHdf5l6TLhswrTTZ/LSME=,tag:0RBCK6lmeZinEPW3Kkm0rg==,type:str]
    pgp:
        - created_at: "2025-03-18T21:31:26Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/Tjp6aB9g704Mg3molN2f1x/5DzRvhBO2yeBOEJ68aI3N
            0CdeRivr+S00xsj1iG6oaL6OPcRG2NcUwCgM6TfjVf6cG2wRI0fDsscpY/WXMjJb
            SDBNpM2AxDn+KwDZzkhJW+Q43ZEZhrCjnkAlXLY1jMxazYIKm11P0WHF8tBeUCFN
            o3l1vpqV+kaOiS9fFAJlKbbwTIE3O4/dhG6vIN6BC6IrhUhnT7daYT4Z+2HjGlxc
            aqpsrdrSstf4WnX1/TLqyQFDj3pNKqDfOa3A0TZGIcwgDrJBuhSzQVjAZiqeYr65
            7ZyF3ng2kVDIUnMLyy4f8LzT3XQlUdNYDnQrL0RtwtJcATulqpJ3cV9+yDmkFK76
            bXBGPhiMGiu075uqhescOVKLYFIflGybXZFUg5QEsdzCHI4kss7JEkztZXftbgYn
            tBatPOUrEOck3/WO3g+jbqZDj3yu0IIrsln5qes=
            =nwGj
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
