apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:iBoXHz4yX5Q/Bn5naw==,iv:YQBEvik0xzRQRgXV+UuMCoZbI7srJIXW+axcp9whk7Y=,tag:0YcDB05wQ9QDoYfyOEe6RA==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.4
    statefulSet:
        spec:
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:sKuotqPq0DcZ0AE=,iv:ARnw4WBA8opY4pMIPooH5QmMDS1Th8x8m87AFW3NwUs=,tag:nD6vc6xcOm0hBSN0GBB9DQ==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:Rs32QwRCO/5EqBsWow==,iv:6k5rkK4brI+hxg0CXWiIhzMn0VNSrHFY7mhA7nIMPi0=,tag:S/rWgZRLFggRet3Ww9DDig==,type:str]
          db: ENC[AES256_GCM,data:HwN0dfs=,iv:x5QRSOncTRBnBPr5Iz3U+SPrrus0A6WcW8pI7E7Nnd8=,tag:fk9jYcksgehuggyS/HnUug==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:ayDKvaj6h13ENqIN+jTYcRVwqU8Ibg==,iv:D5bxNC1qfgqF9CtRTjJfyztFxDFYjuli8T5291qOyd4=,tag:d2EFwGTR0joaxbYAodyGJg==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:rQXseVLP4o+g,iv:saMbefFqiBBqcL0zYwkd1ZG9ZSJKnF1hzOmmoBdj5pc=,tag:mgxpXy0cNMqEcfsYg8aT+A==,type:str]
              db: ENC[AES256_GCM,data:oYatuKlzrIk08O7XEahqXksRSh3M,iv:BL4+OmvAta4J2bRPBH8gIqgynSYE6y2e3Nr178AIE/Y=,tag:UBosgprXFYSHTnxv6PM5qA==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:LUNBupQf8fp35zk=,iv:P7sAD2wDqWiVUCefDbXURUBjWlgkABywhIuJcOXCtd4=,tag:MxWiIK4GSgpPscuUU2Adnw==,type:str]
          db: ENC[AES256_GCM,data:hO6kxgQ=,iv:tsCDCUlt4otpK8coFvcmsGv9VN1fhnRJ/rg2IDSJpD4=,tag:oDfDg3QRQIqdIRIwOj5aaw==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:i/b0xlgwJWbcEDgIhWESSXRL5U4=,iv:VDn/HcnCX4rklDiUZqyIhUzP48j1iGpBTM/EiLlkxy0=,tag:oFGuNmoEJi1EbjVzMXIFvw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:/3zroQ5aXeGWx68I,iv:BjY/Dtpsa8YkfSN0Vt1h2iaUAiMcMmV8Mqi9jjE9Q4E=,tag:7AA5sF5gfKeGVQrujDSG/Q==,type:str]
              db: ENC[AES256_GCM,data:+fzd/jI=,iv:LDS0p7McSq+qb3RdHcNc3hz7sEeiMUvtJX0hx2So7Uw=,tag:15EkJ0IvARMBdjPBdtSArQ==,type:str]
            - name: ENC[AES256_GCM,data:Qnu40A0o6on/w/QPvehbAu8g9xA=,iv:7DrTmxWJdAVxWDKJGjmxd6WDngos2BhXklQU6DYO6tc=,tag:GVfbAI5sXe3I0PA/95MdyQ==,type:str]
              db: ENC[AES256_GCM,data:kbpPDqo=,iv:Cj8DCx5Ch9RUT/fSt4JUha6lY2O01R6XskBhYuYeBvw=,tag:5dG0a93mt1xyqs3lzGdGhg==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-22T03:34:53Z"
    mac: ENC[AES256_GCM,data:++4uW3qfQ80WRbT73jtUgcBJ6gPg7AZ1nN4EljenQKK/JGbeRdVRJ5WGOHtLla1ryHnwbWrXxRQslwztBcV3PGF28IwaKzrs6WiNFPMbe84b67NohKmqjzhrwLeTOTshoQnaS7MS79K9xM1SCU2Ink6IFRw41BVfbMQapQzTBFo=,iv:uMG2L1H+hR8bVlebLr+CQJbF9cQ/1NfNjLnV3X9vyhg=,tag:mcc+iHcJmXfDdbXSYf+1Ow==,type:str]
    pgp:
        - created_at: "2023-12-22T03:34:53Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAmpkgXQj2aLyL9SeiYXxCNEOo5+1pQklS0J0+3uBuxE26
            XdZvM80KeNVPtsfAk99nemCK7cDsmETpZFzdz8cs3eweRkrOArdTdsh7e1+44cR7
            oVJMzLK5gTWMgIfgqlpeeKPpgQ7vNgGFLBIopktayWknwxY26W5r7KZuDK9qCer7
            Hz/SW5JOkhHfz4FuN7OkH9yaUAoC/NBHb4rnHxiDxku7EKMz8W4WPbMw203zipOs
            2Fs3CRSmdvqfVac2RgWspX5FCVUWvVJe7xyFimnalsYsUVVnjiai+3RfRvWp5f7d
            j9yQfXS6euVtJb6cZzUA1QabQ1NbC1yfgw9V2B+vTtJcAWJ8DKUgK95EUD9WjG4p
            UCjcnQi1e1y+eV7740hsvXWCJsL9wFIiuHyvcqocX26vYgM6bwQPd44+5orMMjwQ
            IID2FHDZdHS6x493DOjjb0m3TNDBD5DR9SFHUrg=
            =I7FQ
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
