apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:tBzyRIe02lm/nXJYkQ==,iv:RFuc6++EYijJkCfhkXY+XIZRu735AIqnI1wefWbbx2I=,tag:FA6h0OisgzAmuG7rD+iAzQ==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.17
    statefulSet:
        spec:
            # Make sure MongoDB replicas run on different x86 nodes
            affinity:
                podAntiAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        - labelSelector:
                            matchLabels:
                                app.kubernetes.io/name: prometheus
                          topologyKey: kubernetes.io/hostname
                nodeAffinity:
                    requiredDuringSchedulingIgnoredDuringExecution:
                        nodeSelectorTerms:
                            - matchExpressions:
                                - key: kubernetes.io/hostname
                                  operator: In
                                  values:
                                    - mediaserver
                                    - nvidiaserver
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:49PqwD5cEhYxnsw=,iv:w6C+thJqW6KiYNwHLb6VjjiQe2gkuC0XWv6uF7Ca06Y=,tag:bIP0py9ZqN+bO3I4LVRT1w==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
                    storageClassName: nfs-client
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:Fui2qQk5/nUMDFtwFQ==,iv:FI8RfhqlP2E/5tGs3b0XKFDdHX0D6oxHY2naU4iJk5g=,tag:dTnXdEpExQ+lUfzXGBYIsg==,type:str]
          db: ENC[AES256_GCM,data:Mtq/Zuk=,iv:08pn2JXN7tRVGnYdAgqxWkQFnO9iyihJHhop96MG07I=,tag:ArXYBKifQf8l6EciGZzONA==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:BrYUuOWValVOebR5STJohvnAJhncaQ==,iv:4fS8huB9sdN25MxTYsBYnGNfU6xKAUXFjQfj07JY5tI=,tag:CF9rLNIqSe6Y4oFWfhtihw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:xYLhBcgaRgLs,iv:2tgXYT5rokQTqCR6Jco1Bq5skaczK1jKK2Hv5NJEwwo=,tag:32oZEUDTi/ZqkCH6JPvGyQ==,type:str]
              db: ENC[AES256_GCM,data:6ZoraWWv4Z1UQo7AYOZWKYZtuH9F,iv:MBjPqYUvCmdHlEmwcC9RtM02nPC5NPm1nW4T2J3I13A=,tag:enSlk9zUnCuUY7CFpjugFw==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:fukNLj03lkAljF8=,iv:EOvbOCpoupbQukhDeJVo+BnbP5CMreJljKPoYtdoH7E=,tag:WQZo/Xme4mSkkg2Qz9ZIDA==,type:str]
          db: ENC[AES256_GCM,data:SjhXIgs=,iv:dUbkKkTX7o9t05I6yB8AP6o1f80tDvchLJ7GZ3XXsUw=,tag:xfmY1wwYpiAi654K7Sw9yg==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:LpCEqAUhnICyyF+xkLkr0jSDC2o=,iv:J5YFiEOy4OjHsjDR3L15PVGHMOmMELHvVBjm64UVL10=,tag:ZP9HM/W0NlypUyBSHyYMvw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:o68pEf8FegTJNpty,iv:4g+BNcCfSNDYCUxqttyymN4fS0+bf/eTkhpk0sBOejs=,tag:wjQTSALXtT5nfEz0v7V7FA==,type:str]
              db: ENC[AES256_GCM,data:8Vosfx4=,iv:0PV39I14iJE2v5yiWoHgybJs87qG6/WLuUwnxpWDt5w=,tag:HvDQ5NJaU+TctSyGzwE3hA==,type:str]
            - name: ENC[AES256_GCM,data:CUAL0L5MtntNqXf2HcywLCd7eKs=,iv:Sl+Ptl4BrWy2q/OF3H3yMzWsnHJaxxRE8cmKKK4qJIM=,tag:vVbFDO2vFQ81p7Ci+hGqbA==,type:str]
              db: ENC[AES256_GCM,data:qP2XtiM=,iv:3D1sVDX4TJ+VSpTOd7LZ6qvpus98tFrtU8KuISBc7CA=,tag:D2Dy/E5p/YjZAQQlJEL1Nw==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-18T21:16:29Z"
    mac: ENC[AES256_GCM,data:zIWXKTr536rfMlETHA9NYkkOvyOCMfDGLijjiMWof9DPk7Sh48gIBer/9ccCOsh/uGA1ZbrLuPTdZErhVill1BNbBBgHL9P6CiTrFlFdufOLy2u0NZTOspMPSk5+/GAxporpqRZOS4AEkpqbfeiKTKPV2buXEVopTeUlyw0qHnk=,iv:LtBKDA7cnKNrZuNIjPA3VN6Hhh7jeDdD3SI3MLSOhMU=,tag:vAAcA7ZoGzf7XEafk0/+NQ==,type:str]
    pgp:
        - created_at: "2025-03-18T21:16:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+Jpf+N8XXbSGKsTvq1Q/wAlasYrGmK5d6O4yEZZDhMfYK
            CbVGRoRv+0hr5ki7UA5x6K81jAbphE+Tt5KAMhtDVerklEklvIpPF44Y3KypaIK6
            QBuA7XGQAs7E/rrpHfU8zNMgcz+/UndOTbvFF4bec2D++U0ZlePoNTlSWX54C7SL
            EZ+sUsEbpF0x4aQMcZTElfMqR7qxbvgC4Xm4Z9WEQQE8Q5h5uLnxBS38d6xhb18A
            Pgd/e9VHDTdkvf8l7zzLxAeRHZLrBj399fDVuV0rmNTbMNh0ev05towOGnc7+ULJ
            ZUCtuk6Pp29MPrzER+PBIXt869im+7x5qjQfwksW+NJeAfSTqQh8zfHsEmyqzrUf
            mzWkF0Av1hf6pBkrhmPHh+RFuAG0p5cyaWr14Flhflxbtbmx6hMnREoYrUlxKMfG
            xUEE662KKmlJHnWaORl8HkK+5Axjl/EnKHKOOhgr8g==
            =uOCG
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
