apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:5hU+in13x+AaWBn0Vg==,iv:tbLbkWDJkVNobAbdeJC2Hl9lSAe/AAmChspNH9ElTlo=,tag:hTBc88JUyE/2SqKTj5dd+w==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.3
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:zNTY5dEwlmPZDSoxlA==,iv:uALTM2s9uxoEzWZ6arzNSh8wunBW9y9vLChmRT2Fv6w=,tag:MrVJJ2RNujXlEJSCaZrFcg==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:107.0.0.8465-1
                        - name: ENC[AES256_GCM,data:XDcG3ayg,iv:rE4bz/zmZS8t80T+Tn3TcWNTQXMFeEvlhnvgzelO6oQ=,tag:NqmAXBYx7FXvgoNoAw6rxw==,type:str]
                          image: quay.io/cguertin14/mongodb-raspberrypi-docker:7.0.3
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:Lvkpw3vqW74CNNA=,iv:2mTv8p0oJ/0GCR77eRsjV9rEYK2ktDFMBzteykYwLaA=,tag:FsIhOQa+K+Pzs8VkOgACWg==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:ETUgtcCg1sUsEXmTMw==,iv:HMuhG35GU770PvTgq2r5RZ3PRbM1iHIb71wtO5dg1ds=,tag:FzPITaNkFRoEwQkpNGrJgw==,type:str]
          db: ENC[AES256_GCM,data:t+g0s/s=,iv:+QwSjWntPkOeV4+2CFsZh40TX8XukfPvw7HI8uWa8qY=,tag:ALF7jdLbumCu1h5dq6OXLQ==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:M+CDdwW5Ds1s8RBtI3UcdIYdESMZfA==,iv:oyoXfuQBRjsT1f7p+WLczOt32cc7/TaNy4CMmEOIR6A=,tag:Kke4GvawQoY81Oc3wdR4hQ==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:3kfy7j2Bkcjz,iv:6ol5yhaiWgzUuVSlcW9am1+G2ef5F9q/vyNXDtc4vtM=,tag:xyBVyhnz6VwssJPF12t8gw==,type:str]
              db: ENC[AES256_GCM,data:t1gvvhnwyEWPTFiehICKnVZQG+w6,iv:5D6224DoxwesX6ExPIG1ryrXwQ0wm1sP/bkWA7K0dDI=,tag:h7qtsx+CsmMu3wx1VfyYzg==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:InTx7VOwG1OHVsU=,iv:WmaKqT6eavuzXu21Cknup5sXhKWoWW/2n25uS0XMmkU=,tag:vFkeWGoRGbyFrmy/XVG2HA==,type:str]
          db: ENC[AES256_GCM,data:NrJ4TqA=,iv:coqAQyL9KKTtQ/IYvf7GSKONykhozuCwfEDA7xpv9k4=,tag:XCd3UEcthNfPIiyCeoqDuw==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:JpeJ/dKux8kb7muSbvobouLhoAs=,iv:NVm8jvg8948zK/N5VDBsJVxp1pb+XALnWB6XKd4OAmM=,tag:kdWDMWv2hX7plWes96vghw==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:Ky3YsfUvE/IkT4oz,iv:H+Yd7LS99Q+tTKvj1mzkgPPuPuv9fejP8kH9nxyXjaM=,tag:v9LwFZ/BWMQYvcCYUIAfNw==,type:str]
              db: ENC[AES256_GCM,data:5nSZfMY=,iv:7Od5T5CY24Z1AgkCNhrhYSIT2r7UJ3Dsp1TzGn4wUOk=,tag:1eVIVbHaPx7GAq1QqWir9g==,type:str]
            - name: ENC[AES256_GCM,data:644NERySdzVK1h5lKxFmgyz92cc=,iv:D9pbayh8izeubOoRVC1TRq5rjv498KSWFp4CTEjRBTc=,tag:TXRDNkAhSZ+bH1csKzzfug==,type:str]
              db: ENC[AES256_GCM,data:waY+PmM=,iv:NuBCok8l6wpy1IM/ZslPZkklQbLyxHBLQMkqSlDdrY8=,tag:Ego0nWZxTiC/eDiJcvrQmA==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-12-23T05:59:29Z"
    mac: ENC[AES256_GCM,data:4r5M/sxocKiKpF/knU2N3AKbJflW0sIfZJPcqUY/lk83/DQqzFFQjA7uRbxYQeolADN5kfd/hhmvJXqn4eUJ2TOnocPJifmz1mQ9NL6GaQ2J3yprAtGIoXX0hvRIyI/qaCxVg8SuHmh21qKEUTEfHnM9ShVD8Ah95UROX4lfMA8=,iv:zWP1PcEfVLdVSAiT2V3I4ZP0002IcdOIvt6sB0hnEnY=,tag:zjF0RmNYngnEexYfRNUtWQ==,type:str]
    pgp:
        - created_at: "2023-12-23T05:59:29Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+NDo3mrOWt466oV/4SuuDSl+YrrFBHt+Xjj76zr9mUwN0
            h9n1JqLdxyEQnS+a6pA/41MM3Oex7aa+vuEMhs7o+n6ejOqd41DbEuyIVFsTVx6k
            wfL7K1yBP2t3HOdscxR/IRxK9tVFcYiIUAOmhJrgHXKo3ilnpgza6eRHTY9uyyBC
            XObvAsV08Z+oDnGojN9jNBaX3WIKuDqpAymXbH8UKI9wbOFLqkdiMmia8XQNm5sr
            /TzzL9iS+Z1RIxsbBc2FTB67HoujjX8Jp8sw5cpLgt4PvL9OP7UAx3XvQV0R/Qn0
            aLB1uPxqhK5Z27c1cDfMkYTSk2TKXjNkEHorWGCtH9JeAf+zFucZsp9JOeS/M4O4
            Hj+TaXPZL7HdrIdM81k1jxTPbwDwSCDhKaeMFfL2Ozafku5MRzmOy8OuaZw4y6Q9
            fnNimdOOU8vaMY35Z9/addsNH4mp1MqMpceNix/C8Q==
            =PwiT
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
