apiVersion: mongodbcommunity.mongodb.com/v1
kind: MongoDBCommunity
metadata:
    name: ENC[AES256_GCM,data:2eNHENaAgrPsUfQ+oQ==,iv:wBrIUz5D/a/EjIHtd0QTsuRH1adc8kEm66bJMc5X1Dk=,tag:94dtur+u3xF6efBwmhjWMg==,type:str]
spec:
    # number of replicas, minimum for HA
    members: 3
    type: ReplicaSet
    version: 7.0.3
    statefulSet:
        spec:
            template:
                spec:
                    containers:
                        - name: ENC[AES256_GCM,data:ECqGxG74qv+oYER2ZQ==,iv:rTdE1GE6Z3Li0Gv2bXOFfA5WGR+9RVoZaYH33EyAtE0=,tag:MNZ5s5EZu41ZOCk3yZcp7A==,type:str]
                          image: quay.io/mongodb/mongodb-agent-ubi:107.0.0.8465-1
                        - name: ENC[AES256_GCM,data:RCd50x1R,iv:bzbxHhlyq5wDDng+fF1tApUHNpurnoAndJAGaeQAiEE=,tag:fGLj/y+DocW+7Ml0v4CiQw==,type:str]
                          image: quay.io/cguertin14/mongodb-raspberrypi-docker:7.0.3
            volumeClaimTemplates:
                - metadata:
                    name: ENC[AES256_GCM,data:WPm1O8ZErzqLcbA=,iv:dtyxvfPM03Ho3l3io/2547f3eLa/jyJ+wqW+v8dPMBo=,tag:PBiZ7dFFARQunteINoKCAw==,type:str]
                  spec:
                    resources:
                        requests:
                            storage: 20Gi
                    storageClassName: nfs-client
    security:
        authentication:
            modes:
                - SCRAM
    users:
        - name: ENC[AES256_GCM,data:4f9szKlXS+lbvy06IA==,iv:anrVA2I1dt0WjVtVJ307botNbcdi42Zgu1fCYq21o4k=,tag:mMnxgPpJg1mf3oGWxIJjQw==,type:str]
          db: ENC[AES256_GCM,data:H28MocY=,iv:bNY+lyCBOrU4oH7Cf+29WRGtjm8MJFccdBkAazFd4vA=,tag:XRHiCH7w0Tq/17JRsNzCdQ==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:xbrJx6ozSnx/4/IUK8N88Iz1JR9mXA==,iv:cH9anxpwZqHn/Py/QmtBxhbZj2dI7XE+thBR5982kNY=,tag:yz1BDuNP+YSQSNwcUMQNtA==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:3v+jnGpW0QdF,iv:l9sltvGiwU9bb5XALs8OMS6GaVtLZPxzGeACHvH5aO4=,tag:0Kk3QjWBQcdPBNqxCY1otA==,type:str]
              db: ENC[AES256_GCM,data:K+hQ7CFp8z0B7pL21TtCSz1XIjnM,iv:wKGsZoVIWXOfkwBnVeEJOrjEXHTgzsPqux+oEQIQOwI=,tag:ctttt2ndErGaluHJaQVukw==,type:str]
          scramCredentialsSecretName: educs-user-mongo
        - name: ENC[AES256_GCM,data:7DlWGI7nDYf4Bwk=,iv:3sliOTvyOSROPeIwG2TUHAhi795uVZydlFD9ydHx7f4=,tag:dR1uCfseb5npGmW2HYkRkQ==,type:str]
          db: ENC[AES256_GCM,data:1THF2bQ=,iv:TaJsFNn9jAEAYyh0HTLUkcpqswOTWKzGDtFNh0Qy2as=,tag:pvxFb7lfP+mvZit8ePELow==,type:str]
          # a reference to the secret that will be used to generate the user's password
          passwordSecretRef:
            name: ENC[AES256_GCM,data:tunB315SGAbNCMluHo3GfA/yCKw=,iv:JVGOtDAJuOA7iCvvdj6XOIa4syHu7jvfjOeCVUbaZe8=,tag:nXDObk4eVJXgnuvODLqUjg==,type:str]
          roles:
            - name: ENC[AES256_GCM,data:JoBPK7P1nu4+xDxF,iv:26O9pE1MDneZlG6EXCm0SeVBvtf2ArQ8OdmYTmjDrDM=,tag:pRG3msBB7v0719yJJHKh3Q==,type:str]
              db: ENC[AES256_GCM,data:ATOyr3Y=,iv:C8IM3Z+EN9xvLhgt26MPz0Rko+9cft0FVOwlQVB80BI=,tag:Omw+mHsIYf1D/efZot7zmw==,type:str]
            - name: ENC[AES256_GCM,data:avSnO0kPiLYOUOwQ0bdB9o6aM/8=,iv:MKy9jeeevMSbPnjC4IXRb+0nPQOMs7CSCg12SZPQgEw=,tag:lomGBeNNTXMtjX6+bA6Wxw==,type:str]
              db: ENC[AES256_GCM,data:5eIG+8o=,iv:ARCuj95pBEpG4bVya0IoQbW6Xl46uLik1NqKPbC4/pM=,tag:SsfjsM6A7FuPHSaKZL0pXA==,type:str]
          scramCredentialsSecretName: educs-admin-mongo
    additionalMongodConfig:
        storage.wiredTiger.engineConfig.journalCompressor: zlib
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-08T20:15:19Z"
    mac: ENC[AES256_GCM,data:ANbvm89N5/0/52MAZR/ZnshKKEmC76vPnbh9cJwDUMB+hco0GFKKLTB+M/ex2R/8mTiZHaMZQn5bygRjkPoM5zB4KeJ5rrS5eH9wJTmPUxxsWovV6rGSKcYh0+trMBq+jBXR+pADz+dIv0gY6ylAlM4os+qE94LX6CR+oFSkom8=,iv:xoOz/dbWIaawxvnZDssMinddfPBoV+3oAhumX7zkLPA=,tag:zRHegIAuOHjDDTG6QQVdtA==,type:str]
    pgp:
        - created_at: "2025-03-08T20:15:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/Xh/9+5ZdXD8A9Ay90nB+KVmZBSe0m0oVXlq8RSQDCe8I
            TxJEPQl/yh4lYRn+4jCnHbAQKma1NcCmyZt2+1KL3p2DRn+3pJN5N77ODS4FPDFn
            ULQ35ywQjP7UL5fqJnOl6aCXyD7cC3SzzxTGcJHOtmwK5iBw1Dez/SwG/3MY+WZC
            7iwRn83gzjt+bTHEbkU/HZhUhHdqzPga7vn1+T0S72FlvtNpawh27YP6NHqlifl2
            aFX7jnDKcRB67ns/7RfmUH6MbFi0zU+2QzhjioUXRw+GUHeauCzxAPC/pBJknl/B
            rOVEiSdBQKl0YUzBqzqardSbNABiUtiZBhb4s23gEdJeAVpQhO+rxmEDI6AqjD6I
            22oB+ZTFB/qCwbI9J4G+8xEZYHr5RgIIEObz0kFCjQI+JSo8hAHKN21JbiQqBZqy
            SG7UVaNbBE3kyIt88lTq43s13ZJeXzyMhn52sVYNXQ==
            =T8OE
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
