apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: mongodb-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./secrets/replica-set-enc.yml
- ./secrets/passwords-enc.yml
