apiVersion: v1
kind: Service
metadata:
  name: pihole-tcp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.203
  ports:
  - protocol: TCP
    port: 53
    name: dnstcp
    targetPort: 53
  - protocol: TCP
    port: 80
    name: web
    targetPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-udp
  annotations:
    metallb.universe.tf/allow-shared-ip: pihole-svc
spec:
  type: LoadBalancer
  loadBalancerIP: 192.168.0.203
  ports:
  - protocol: UDP
    port: 53
    name: dnsudp
    targetPort: 53
---
apiVersion: v1
kind: Service
metadata:
  name: pihole-metrics
spec:
  type: ClusterIP
  ports:
  - port: 9090
    targetPort: 9617
    protocol: TCP
    name: metrics