apiVersion: v1
kind: PersistentVolume
metadata:
  name: pihole-config
spec:
  storageClassName: nfs-media-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  claim:
    name: pihole
    namespace: pihole
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/pihole-pihole-pvc-459066db-6641-44ca-80a7-c43795d682c3