apiVersion: apps/v1
kind: Deployment
metadata:
  name: sonarr
spec:
  template:
    spec:
      containers:
      - name: sonarr
        envFrom:
        - configMapRef:
            name: mediaplatform-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prowlarr
spec:
  template:
    spec:
      containers:
      - name: prowlarr
        envFrom:
        - configMapRef:
            name: mediaplatform-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: radarr
spec:
  template:
    spec:
      containers:
      - name: radarr
        envFrom:
        - configMapRef:
            name: mediaplatform-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: qbittorrent
spec:
  template:
    spec:
      containers:
      - name: qbittorrent
        envFrom:
        - configMapRef:
            name: mediaplatform-env
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: sabnzbd
spec:
  template:
    spec:
      containers:
      - name: sabnzbd
        envFrom:
        - configMapRef:
            name: mediaplatform-env
        