apiVersion: v1
kind: Service
metadata:
  name: jellyfin
  namespace: mediaplatform
spec:
  ports:
  - name: http
    port: 8096
    protocol: TCP
    targetPort: http
  loadBalancerIP: 192.168.0.22
  type: LoadBalancer