apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: cert-manager-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./secrets/cloudflare-api-token.yml
- ./secrets/cloudflare-api-token-educs.yml
