apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: gpu-operator

resources:
- namespace.yml

helmCharts:
- name: gpu-operator
  namespace: gpu-operator
  releaseName: gpu-operator
  repo: https://nvidia.github.io/gpu-operator
  includeCRDs: true
  version: v24.9.2
  valuesInline:
    # Metrics
    dcgmExporter:
      enabled: true
      serviceMonitor:
        enabled: true
    # k3s compatibility
    toolkit:
      enabled: true
      env:
      - name: CONTAINERD_CONFIG
        value: /var/lib/rancher/k3s/agent/etc/containerd/config.toml
      - name: CONTAINERD_SOCKET
        value: /run/k3s/containerd/containerd.sock
      - name: CONTAINERD_RUNTIME_CLASS
        value: nvidia
      - name: CONTAINERD_SET_AS_DEFAULT
        value: "true"
      # Device Plugin
      devicePlugin:
        enabled: true
        config:
          create: true
          name: time-slicing-config-all
          default: |-
            version: v1
            flags:
              migStrategy: none
            sharing:
              timeSlicing:
                resources:
                - name: nvidia.com/gpu
                  replicas: 4