apiVersion: ceph.rook.io/v1
kind: CephCluster
metadata:
  name: rook-ceph
  namespace: rook-ceph
spec:
  resources:
    cleanup:
      limits:
        memory: 100Mi # default: 1Gi
      requests:
        cpu: 500m
        memory: 100Mi
    crashcollector:
      limits:
        memory: 60Mi
      requests:
        cpu: 100m
        memory: 60Mi
    exporter:
      limits:
        memory: 50Mi # default: 128Mi
      requests:
        cpu: 50m
        memory: 50Mi
    logcollector:
      limits:
        memory: 100Mi # default: 1Gi
      requests:
        cpu: 100m
        memory: 100Mi
    mgr:
      limits:
        memory: 1Gi
      requests:
        cpu: 250m # default: 500m
        memory: 512Mi
    mgr-sidecar:
      limits:
        memory: 40Mi
      requests:
        cpu: 50m # default: 100m
        memory: 40Mi
    mon:
      limits:
        memory: 1Gi # default: 2Gi
      requests:
        cpu: 500m # default: 1000m
        memory: 1Gi
    osd:
      # Default:
      # limits:
      #   memory: 4Gi
      # Warning: this is for avoiding memory overcommitment; but the Rook team says to avoid it: https://github.com/rook/rook/issues/12078#issuecomment-1505926822 
      limits: null
      requests:
        cpu: 500m # default: 1000m
        memory: 4Gi
    prepareosd:
      # No limits on purpose.
      requests:
        cpu: 500m
        memory: 50Mi
