# CephNodeNetworkPacketDrops patch
- op: replace
  path: /spec/groups/6/rules/1/expr
  value: |
    (
      rate(node_network_receive_drop_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_drop_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) / (
      rate(node_network_receive_packets_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_packets_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) >= 0.0050000000000000001 and (
      rate(node_network_receive_drop_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_drop_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) >= 10

# CephNodeNetworkPacketErrors patch
- op: replace
  path: /spec/groups/6/rules/2/expr
  value: |
    (
      rate(node_network_receive_errs_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_errs_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) / (
      rate(node_network_receive_packets_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_packets_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) >= 0.0001 or (
      rate(node_network_receive_errs_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m]) +
      rate(node_network_transmit_errs_total{instance=~"mediaserver|nvidiaserver|miniitx0",device!="lo"}[1m])
    ) >= 10

# CephNodeDiskspaceWarning patch
- op: replace
  path: /spec/groups/6/rules/4/expr
  value: predict_linear(node_filesystem_free_bytes{instance=~"mediaserver|nvidiaserver|miniitx0",device=~"/.*"}[2d], 3600 * 24 * 5) * on(instance) group_left(nodename) node_uname_info < 0