apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: load-tester
spec:
  args:
  - name: service-uri
  metrics:
  - name: load-tester
    initialDelay: 15s
    failureLimit: 5
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: load-tester
                image: cguertz/load-tester
                command: [sh, -c, -x, -e]
                args:
                - |
                  wrk -t5 -c25 -d45s -s report.lua {{args.service-uri}}
                  jq -e '.errors_ratio <= 0.0001 and .latency_avg_ms < 250' report.json
              restartPolicy: Never
