apiVersion: argoproj.io/v1alpha1
kind: ClusterAnalysisTemplate
metadata:
  name: traffic-generator
spec:
  args:
  - name: service-name
  metrics:
  - name: traffic-generator
    initialDelay: 15s
    failureLimit: 5
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: load-test
                image: alpine:3.14
                command: ["/bin/sh", "-c"]
                args:
                - apk add curl --no-cache && for i in {1..60}; do curl --max-time 1 --fail https://{{args.service-name}} || curl --max-time 1 --fail http://{{args.service-name}}; done
              restartPolicy: Never
