apiVersion: apps/v1
kind: Deployment
metadata:
  name: argocd-repo-server
spec:
  template:
    spec:
      # 1. Define an emptyDir volume which will hold the custom binaries
      volumes:
      - name: custom-tools
        emptyDir: {}
      # 2. Use an init container to copy the KSOPS binary into the emptyDir
      initContainers:
      - name: install-ksops
        # Match Argo CD Go version
        image: viaductoss/ksops
        command: ["/usr/local/bin/ksops", "install", "/custom-tools"]
        volumeMounts:
        - mountPath: /custom-tools
          name: custom-tools
      # 3. Mount the custom KSOPS binary into the repo-server container
      containers:
      - name: argocd-repo-server
        env:
        - name: XDG_CONFIG_HOME
          value: /.config
        volumeMounts:
        - mountPath: /usr/local/bin/ksops
          name: custom-tools
          subPath: ksops
        - $patch: delete
          mountPath: /usr/local/bin/kustomize
