kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: cloudnative-pg

resources:
- namespace.yml

helmCharts:
- name: cloudnative-pg
  repo: https://cloudnative-pg.github.io/charts
  version: 0.26.1
  releaseName: cloudnative-pg
  namespace: cloudnative-pg
  valuesInline:
    monitoring:
      grafanaDashboard:
        create: false