apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v2.11.5
- metrics/argocd-serviceMonitor.yml
- metrics/argocd-server-serviceMonitor.yml
- metrics/argocd-repo-server-serviceMonitor.yml
- metrics/prom-rule.yml
- namespace.yml

namespace: argocd
