resources:
- https://github.com/argoproj/argo-cd/manifests/ha/cluster-install?ref=v1.8.7
- metrics/argocd-serviceMonitor.yml
- metrics/argocd-server-serviceMonitor.yml
- metrics/argocd-repo-server-serviceMonitor.yml
- metrics/rbac.yml
- namespace.yml

namespace: argocd