apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: nginx-ingress-controller
  app.kubernetes.io/instance: nginx-ingress-controller

helmCharts:
- name: nginx-ingress
  repo: https://helm.nginx.com/stable
  version: 0.17.0
  releaseName: nginx-ingress
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    controller:
      autoscaling:
        enabled: true
        minReplicas: 4
        maxReplicas: 24
        targetCPUUtilizationPercentage: 75
        targetMemoryUtilizationPercentage: 75

patchesJson6902:
- path: patches/update-resources.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1
- path: patches/remove-replicas.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1