apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- resources/autoscaler.yml
- resources/service-monitor.yml

commonLabels:
  app.kubernetes.io/name: nginx-ingress-controller
  app.kubernetes.io/instance: nginx-ingress-controller

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.12.0
  releaseName: ingress-nginx
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    rbac:
      create: true
    controller:
      ingressClassResource: 
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      service:
        loadBalancerIP: 192.168.0.20
      metrics:
        port: 10254
        portName: metrics
        enabled: true
        service:
          servicePort: 10254
          type: ClusterIP
          labels:
            app.kubernetes.io/other: nginx-metrics
        serviceMonitor:
          enabled: false
      config:
        use-http2: true

patches:
- path: patches/update-resources.yml
  target:
    group: apps
    kind: Deployment
    name: ingress-nginx-controller
    namespace: kube-system
    version: v1
- path: patches/remove-replicas.yml
  target:
    group: apps
    kind: Deployment
    name: ingress-nginx-controller
    namespace: kube-system
    version: v1
