apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- resources/autoscaler.yml

commonLabels:
  app.kubernetes.io/name: nginx-ingress-controller
  app.kubernetes.io/instance: nginx-ingress-controller

helmCharts:
- name: nginx-ingress
  repo: https://helm.nginx.com/stable
  version: 0.17.0
  releaseName: nginx-ingress
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    rbac:
      create: true
    controller:
      enableOIDC: true
      enableExternalDNS: true
      enableCertManager: true
      enableCustomResources: true
      enableTLSPassthrough: true
      setAsDefaultIngress: true
      service:
        loadBalancerIP: 192.168.0.202

patchesJson6902:
- path: patches/update-resources.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1
- path: patches/remove-replicas.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1