apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

resources:
- resources/autoscaler.yml

commonLabels:
  app.kubernetes.io/name: nginx-ingress-controller
  app.kubernetes.io/instance: nginx-ingress-controller

helmCharts:
- name: ingress-nginx
  repo: https://kubernetes.github.io/ingress-nginx
  version: 4.6.0
  releaseName: nginx-ingress-controller
  namespace: kube-system
  includeCRDs: true
  valuesInline:
    nameOverride: nginx-ingress-controller
    rbac:
      create: true
    controller:
      ingressClassResource: 
        name: nginx
        enabled: true
        default: true
        controllerValue: "k8s.io/ingress-nginx"
      service:
        loadBalancerIP: 192.168.0.202

patchesJson6902:
- path: patches/update-resources.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1
- path: patches/remove-replicas.yml
  target:
    group: apps
    kind: Deployment
    name: nginx-ingress-controller
    namespace: kube-system
    version: v1