apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: nginx-ingress-controller
  app.kubernetes.io/instance: nginx-ingress-controller

helmCharts:
- name: nginx-ingress
  repo: https://helm.nginx.com/stable
  version: 0.17.0
  releaseName: nginx-ingress-controller
  namespace: kube-system
  includeCRDs: true