apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-downloads-storage
spec:
  storageClassName: nfs-media-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 200Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-movies-storage
spec:
  storageClassName: nfs-media-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-shows-storage
spec:
  storageClassName: nfs-media-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Ti