apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-downloads-data
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 100Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-movies-data
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 750Gi
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mediaserver-shows-data
spec:
  storageClassName: nfs-client
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 750Gi