apiVersion: v1
kind: PersistentVolume
metadata:
  name: jellyfin-config
spec:
  storageClassName: nfs-media-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.205
    path: /volume1/k8s/mediaplatform-jellyfin-config-pvc-326acbac-cf11-459e-ba9c-718662893c7f
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: qbittorrent-config
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/mediaplatform-qbittorrent-config-pvc-c0f4e1c4-b374-4d78-a89f-bdbb818186bf
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sabnzbd-config
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/mediaplatform-sabnzbd-config-pvc-bc5edae2-d8bf-43e7-a884-d358574c6f6f
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: radarr-config
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/mediaplatform-radarr-config-pvc-9cc29817-1bda-4800-8b3b-32e6c1dc9d5c
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: prowlarr-config
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/mediaplatform-prowlarr-config-pvc-67c4e26a-7790-4974-b05c-b2108b9c180a
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: sonarr-config
spec:
  storageClassName: nfs-client
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  nfs:
    server: 192.168.0.201
    path: /volume1/k8s/mediaplatform-sonarr-config-pvc-681e1c83-a316-4f52-8efc-ead7aa2d2f88