apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: educs

resources:
- resources/
- frontend/
- backend/
- mongodb/

labels:
- includeSelectors: true
  pairs:
    app.kubernetes.io/part-of: educs
