apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:ssYmTEsIETDoj766Mw==,iv:NtQ2gSmlAlc3mCp+SCPlDdfn2MkY/tvM+syrq/Al4uQ=,tag:Kctz5NITxLG/I8PuJQ8RPw==,type:str]
    namespace: kube-system
type: Opaque
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:+BnpbJBbw1ehby8dMhLYDcatzVv4VMYPM4jlrw==,iv:W06RU3eFs5RZ9rqRoE4pzaPH+V4Lg8N9S5xSdIerkJI=,tag:pd6Mj3HyBaQftN8nWzAD3g==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:FMNn6oH27h7hrOAltxDoRFDUbmTiHTjCzi/YYMBCfZ8SaL7aauc/UAkscTHKfQF9P4x+MKrGCVo=,iv:DeB9gcLCqKeykDqblCL5yI1T6NVb1vPiqBnJOuoes0I=,tag:0AEKzs2HUADvIRgT8Jq7Ug==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:x5vEyQ+8lbikp3hLHFwmMFPP/aVF2lDI51G57a8exfKZenhgPY4sZ6n3F8g=,iv:aQ5S1A8EP776ucwx0ZEaaVx4XPGa6aRabQrYqf9pXI4=,tag:DDzj9yYO7z7aTcmSI1bYFw==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-27T00:02:27Z"
    mac: ENC[AES256_GCM,data:w2r8r0oCWxdIDONAvcbe97fRzsgobu57zesUaZIQ6lwR5UPJ6vealdke1VdDycuBddq3eOUUL1D78otvuB8DbB/ZRwHG3M07NbcSoj0JVqT3Q71KHG32hTG8bdsRgbecsL0V/4GfpW+4KMc9QTfZDlFODJMwRAoHc8pcqDyNO4I=,iv:ynb74gp8X4BJ5dDzQPj0Km9MhWgpHSbLaIhb+VC51BY=,tag:HodNlq1xRtLIfQLp8cBkBA==,type:str]
    pgp:
        - created_at: "2024-01-27T00:02:27Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9GO/SR1iC8vS8bQFMgtlDinslWc5N5XKFryTnABwu02hq
            2So7PtDVnhksLAdGyJ0a0wEay0Rm+wAO70es3xJLRnrGVaP6e1hq5+500ht9lpBL
            V3Oevq/1Z8VBtVfqyuW9PtxBXf7VOREmg2MRwqTXkzjlqsBTie/jYoXu8BqIFAoX
            Q5rQX9LUcx1Kjfm3Q4LYqVFeP+6CM5UvVHjsZrMepUWAcZJUAp+n7wcrVOmj8QMs
            em8Uf1kdRhp9GfcxsJYsyH7CgxwM2NZkwfseyqIg3CxOXeVGMu/yGAJLpPGr4g9c
            BWbwugVc29eE7MNNUU5Z5xw5e6fhjkefhQU03Dgi09JeAYJd/MTmF88ocWjzFboi
            5SsTkW62T4WgqZR1CBsheZRJaUX5VokFk5sLcjGRZPKfw4yAHXNuwGv9ELHf6enN
            fWbsnXDv1BRAZHQCOfsByMD8Eo8GLhJNP+BMV0/EVQ==
            =CieZ
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
