apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:ssYmTEsIETDoj766Mw==,iv:NtQ2gSmlAlc3mCp+SCPlDdfn2MkY/tvM+syrq/Al4uQ=,tag:Kctz5NITxLG/I8PuJQ8RPw==,type:str]
    namespace: kube-system
type: Opaque
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:+BnpbJBbw1ehby8dMhLYDcatzVv4VMYPM4jlrw==,iv:W06RU3eFs5RZ9rqRoE4pzaPH+V4Lg8N9S5xSdIerkJI=,tag:pd6Mj3HyBaQftN8nWzAD3g==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:FMNn6oH27h7hrOAltxDoRFDUbmTiHTjCzi/YYMBCfZ8SaL7aauc/UAkscTHKfQF9P4x+MKrGCVo=,iv:DeB9gcLCqKeykDqblCL5yI1T6NVb1vPiqBnJOuoes0I=,tag:0AEKzs2HUADvIRgT8Jq7Ug==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:x5vEyQ+8lbikp3hLHFwmMFPP/aVF2lDI51G57a8exfKZenhgPY4sZ6n3F8g=,iv:aQ5S1A8EP776ucwx0ZEaaVx4XPGa6aRabQrYqf9pXI4=,tag:DDzj9yYO7z7aTcmSI1bYFw==,type:str]
sops:
    lastmodified: "2024-01-27T00:02:27Z"
    mac: ENC[AES256_GCM,data:w2r8r0oCWxdIDONAvcbe97fRzsgobu57zesUaZIQ6lwR5UPJ6vealdke1VdDycuBddq3eOUUL1D78otvuB8DbB/ZRwHG3M07NbcSoj0JVqT3Q71KHG32hTG8bdsRgbecsL0V/4GfpW+4KMc9QTfZDlFODJMwRAoHc8pcqDyNO4I=,iv:ynb74gp8X4BJ5dDzQPj0Km9MhWgpHSbLaIhb+VC51BY=,tag:HodNlq1xRtLIfQLp8cBkBA==,type:str]
    pgp:
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQwAoXOLzD9If0mT1uzK7x5m/T/HjRSkQWs9P8ig+cqZ2ilQ
            LNkoTNEY4id68AMAER70OALxovFunXb0HzmdXobU8niEAc9sHCjMjfhcVAdP9dKm
            Q4VQaL0mnViAr4eBH24VBuH704GIr3mXzJkpxNFj05RRawhzW3Jl61xGOAegPVp+
            gvCc9VLdKj3EMA8p8v5Uht8ojuGbS4uQyOGarqRfe6q+p32xCr04SvFSn+bStxfC
            344xMskC13l5MBG3fcc3KWSmQMupp/0vjsaOQz40HuznDVr02kJaaPtsXHasrUST
            IdeJeUbncMaze9FFygiPRYtN3+s9e7qpCteRO2DhI+NRZ2Ao4YHpfQVJ/log36dh
            ruUZKNYPf2RbmaUhFeUuuNSldaKONYAq56NrOyCHl8Flzdf7A+g0mkVFH2ojWOhZ
            15RyRTXNjWBVJaE84Ei+Z1P7uaGmtkTXMCA+v73attaDfzCnGCWAMRLSS2VCyoXy
            tFj8bAZyCWVWnjInVGWi0l4Bb1UH9tDp9qUYrJWR+/SU9IFoSU/YJvn5JE1H9pZw
            yKLKuSJ7tDaAMdiSKpHCdjdjE6/2uGpf3Iu8v5N66fPP6W8yEpLa7eZr297Ccg89
            GZjvCb9yjmqpjEl5Kgt+
            =EckQ
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
        - created_at: "2025-11-18T16:35:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/RMHDoal9YMvr/jdSMaRARHLs3iWbkAhBgg01BS3tf8e5
            778CRvC0f7GAmStshSnScAi3Vpl4eDqExDoPC5ki2a/D7IIHBkeY8xX01vVGFbcr
            JbR/zG2Z4bEHOR3+v26tQVEnknI02wt26c1wcM5hBVudCC2vT9DMgPttus28XmT/
            imT6AnR3HHz9sBSYZ3DOhizy+/Wft7CDnSWgGjdJvDFI1f/vstIUBT6DF3gw1jhT
            mE7cPMfAxGJ0cxqXkJDMh1k4HPBOtzQj6w4fRyOa+oSG5qAw9ERMfak27I+qLwSH
            DETXY5YGxcQ8/eiCVZmPDwjh4zIuUUstJQoejL/9UNJeAeyGKYu5jn+8PbsWcmLP
            cJBzS6RJdSapkUfhfWMu+uu3EX9QakiVHo/PBOwJqIiKzCwEiQKeCk1EfzMLWjg/
            lF7WUo/Z97kjDMwIoJHBdpy6Y5Juv0Wg8bIqPIpgMQ==
            =rnyN
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
