apiVersion: v1
kind: Secret
metadata:
    name: oauth-secrets
    namespace: kube-system
type: Opaque
data:
    OAUTH2_PROXY_CLIENT_ID: ENC[AES256_GCM,data:akM9yETHJAZCP3VbcsMzWvMfTN2EKuplTdbAeuoXpENg8ZR3+zuW6KOdrlcsNFtj189bR+BQTGLKDZ/MiDWnTI8OZs4T3wGXOwfgs2naAKMAic8Dad08TfAu2ZwvD+cs,iv:J2leM+pXy9H6YDDznEark2EVKyY1guDZgaKnuZT4bF0=,tag:6dUkfXC2zsRHCbi8XeUJEQ==,type:str]
    OAUTH2_PROXY_CLIENT_SECRET: ENC[AES256_GCM,data:aO/h7jPS4bR4xVH582GGH7WML5VyhiCU1ucSNR60NNY=,iv:STGLc6kD6Oykxt2COE+0A0yvDaSgT4kyjpEcbMjXzvs=,tag:Eo1662FlzymjrVINocuztw==,type:str]
    OAUTH2_PROXY_COOKIE_SECRET: ENC[AES256_GCM,data:HfJ0wu5sJZf+aZaXzwk3vntsU9FF3jQlPiHo3nABBDEfwMGlq2uWfBY0/zHeBrC0bmHEzNRlswhhGQSTZCP8M5YO10Bb3CUvD6hpK+JWQkA=,iv:rKMks9/knvRdJj5j1ZL6bc0O8tivj+4aC1UfG6bp9fc=,tag:yRl0sWKLJavTNzwihJ3Rfg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-03-30T02:14:03Z"
    mac: ENC[AES256_GCM,data:1N/JV7B6DXdUtL3U4s4y8ggsoebYzd4LvQsO63oCpU1CSmsMh8dR7nj7sz3JXllW9V8x7lCoZWmiTE/Ho6JSn08jtga0bjsPYMPs3Z90X3lH9ysi/MnvJI0MPzR8cIRgOddYtSgrkQ3xjorrH7uBSnArKuulVSog8l0Lh5JbNS4=,iv:o+8DsEZ8aytRfFso59MLYsj/ZXwxfN84z1mUiGDI/xw=,tag:LxCjdbHKW/MwzozvyJCEBg==,type:str]
    pgp:
        - created_at: "2023-03-30T02:14:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf/d+H5qkMxk4AN4wNT648/zvj0Jed1H1bw82V0Q/lT8AjG
            LbLGeMKug7QiXRhR/P5M3m51qJLtHeMKnSWOLQEJANXijoPpohEYrU4cT/vahOTr
            6DVhbeXMKk5ceenelHEjLhUT5uG8YRSy5qxLoV/pEB/f608MZQSH0N/rqJhfsUkY
            QdcJ0u8mDn9J4JlT4KjUA2sVeBOG9aMJpOEvaaO+n+P0zv3Lv0fYTwDD500SGTrJ
            lrYlHKQPaevVp6GxiiLYnyN7KiQdHBG67OBSY8T4onmflGE5+N1E4ca8uuNR4ZCr
            /tUAFkMKuYG4nVdD/O9780OS76/4O1jBax12oknFJNJcAdWELlcR147WqDIoMyuE
            fT5CvxJk9Pu7gVqekRkb/sd6NZClE0IfD2cvRz1RN2QhwDs+DRB9UZbvz95vZoC2
            3Ls3h2zBwoBZVJ2sqAkcRgxxdoK2j0Ptr5zGyic=
            =l9i9
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2023-03-30T02:14:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+Pd0j2w264FKiJ6FdbQaL6IBCDglT5l8Da4NcgOa30Zlt
            bswhsvtjsZVdS3W2R0xobw1tqnBYh6zZqOX51CukJi7DdgNQsqbMD91mrn6JR7QB
            /UrpigXpP9T+e3BKTLU37Hmp0A4417wFui6dElySSXitGaiVKfoXjIRMKigF0U6N
            3X/VFnpcOOxwBUAeGGYq6Wks3UpOKbfVL4SkL2vR+9UrrycYnEU3Zn8JUbORZ9gp
            MuzlHxgxAO75sFVNc/l/L1iumy8JmsTNogP+NdeQpGr2GqkWhGYmjo8ZBdJ/uFwF
            EyNFZWncs3NSdiY0rX4H2eAt05PRfrFFslBhySiQhtJcATdRN4nRzMGvOfxWS/HZ
            MxUuRh/GREilP86faEYQPDvMymlGi7KlWBTEoVif+A2nPFM81jMTwbg4QBx7Zihu
            IDI+mQoshE+BgiFEBcwbacFZmUAMG4D9bEzw3AQ=
            =br9H
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
