apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: home-assistant

resources:
- resources/namespace.yml

images:
- name: ghcr.io/home-assistant/home-assistant
  newName: homeassistant/home-assistant
  newTag: "2024.11"

helmCharts:
- name: home-assistant
  namespace: home-assistant
  releaseName: home-assistant
  repo: https://k8s-at-home.com/charts/
  version: 13.4.2
  valuesInline:
    env:
      TZ: America/Toronto
    
    # This is required to access the host machine's USB devices.
    securityContext:
      privileged:  true

    persistence:
      config:
        enabled: true
      usb:
        enabled: true
        type: hostPath
        hostPath: /dev/bus/usb/001/003

    # TODO: See if this is needed?
    # addons:
    #   codeserver:
    #     enabled: false
    #     args:
    #       - --auth
    #       - none
    #       - --user-data-dir
    #       - /data/config/.vscode
    #     volumeMounts:
    #     - name: config
    #       mountPath: /data/config # TODO: Validate that this works

    # Affinity rule to schedule home-assistant on capable nodes.
    affinity:
      nodeAffinity:
        requiredDuringSchedulingIgnoredDuringExecution:
          nodeSelectorTerms:
          - matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
              # Nodes with USB devices attached.
              - worker3
              - worker4
              - worker5

    ingress:
      main:
        enabled: true
        annotations:
          cert-manager.io/cluster-issuer: "letsencrypt-issuer"
          nginx.org/websocket-services: home-assistant
        ingressClassName: nginx
        tls:
        - hosts:
          - ha.cguertin.dev
          secretName: home-assistant-cert
        hosts:
          - host: ha.cguertin.dev
            paths:
              - path: /

    # WARNING: Find out how much resources are needed for home-assistant, might remain empty.
    # resources:
      # Warning: No limits.
      # requests:
      #   cpu: '6' # take the whole node, so that only sabnzbd can be scheduled on it. (there are 8 cores, but let's use 6)
      #   memory: 8Gi

patches:
- path: patches/home-assistant-hostnetwork-patch.yml