apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: tap-role
  namespace: kube-system
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: tap-role-binding
  namespace: kube-system
subjects:
- kind: ServiceAccount
  name: tap
  namespace: linkerd-viz
roleRef:
  kind: Role
  name: tap-role
  apiGroup: rbac.authorization.k8s.io