apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:+Whnv4jOaMx1Ssq5r4om3wbLQazRUg==,iv:dvm1oxrHRDr3m34vP9cGM3P9PnZEHdojdprW7kpL/kI=,tag:pQAWe0htJqwR8Id1lg143w==,type:str]
    namespace: paperless
type: Opaque
stringData:
    providers-json: ENC[AES256_GCM,data:Qx6CvGEgwyMvnF+vTHdBFN7H7G9DVr8YpSs7qRaP4jQTkeS7qxt2npfEdy4wYIMO8ReUGoL1jQQyT5cc2fl3sgrG6FeNC1cdtRZnyHfn6ic02/KkK/GthLijAw7Uj9XhHncOfpaEFoYLSSzzeBGM7M3EAUBXvOv6ZdtHe4GZ+b33DI1jQx2j0n6S+iRfb33rFNUMlM5PT5llZHfURfw=,iv:QXHRDD3RwVqkkCH4S86PStHXTHYxE4osdtDymhtw5rs=,tag:AtlP8ylsk2Q+I1Ye7NuVuA==,type:str]
sops:
    lastmodified: "2026-03-02T01:04:11Z"
    mac: ENC[AES256_GCM,data:ZrVRswkMi/ueHMzIaAh+/7LbRW8dVMN4bPkd7WaYhx4Ctmjl/UC8kFtGClH+/A1tiCFuNi8MRgTxFY4GOVTSnnvBUWElWhA523MnpFN+QIJbQLZdohbJZwJihViTf5kahIyZ0DQNGwJ9oI71CmzaJwRcclv9j+apd9AR+Lx13+g=,iv:2PfLY9PHmln06CXY/c0b4ug1VlcDkT1uGvufMQ4O5/U=,tag:izLHafBbpklB/Gr68h9yvg==,type:str]
    pgp:
        - created_at: "2026-03-02T01:04:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf7BOPEqOYBGf1DVbZ/IrdhnFm/vA9EFHGPUZsedi4/amI5
            kbT/2X4hrhFpMdcd+7ZJ4OpuuTt+w8jG/Jxlnk9iq1+HOD9tDr0F89AESsMuj9Dh
            MyGNLrYPzSScrVydscwu9jhIQFmG24OgeZ5MLhhQLQu44szbP3c0N2I/UmVr5DaF
            MijrKaY1wNRVIJ/AWZoe6ujD1nQbcVWZI0Du0YZzhDNVZgxJAJQGBG/8Hhhb48UO
            ELJx29BuT7x/o227t+lOeGT1qZH/mMAtz3+WNiD0YoZ3XZi88MA9dELUF7aNYldR
            dxoVzA125Q1osaJE8DnNrpcBbTr8XP3x06rOef31kdJeAQ4qVVYkwsGNqI+x3Rho
            IULun4UatpgOm34oJMvnxod2BweVf3eprAFCxsDda3WVxLa/CmtpTxvj9+VRKk/i
            qffbk3DoE5n2JwTKFp2eDc5uuOuKWRsBzP83ITgRAQ==
            =8gt/
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-03-02T01:04:11Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv+IPha2QXnnPtErYTjKEB3Yh/m414ZwDj8TnHnrQ6EGHIj
            DG0QfZwrZolpwKYeOPQiJlJL2+sWDocXFoVwTjvk9TG2VpodnPUnxETgb5ttMPFl
            F6l2zB9E1pwdijMPuo71NrWqJ6iXkhdnF/MlnVVRqLpG2qIKvPuqBaPH4Hcyqh8v
            kRBO65Yl/fqFLO3P7SOP7i7c/edugmUC5sRN2dJGoimJCNfv3rQkyUoYrX7lMB9L
            W8wY4Kp4OSFlrGJDHopHh9ppgPfnpTXAfJIEftxZeJk3hsM6GIs/fOpAnr9g+eHk
            mPsw4iwwwczNt7Jl5vpwQu05kz2r3zZb1yXY6oxjQmuTEBJz8zaL8HXbYjfCCZsw
            m+Zl73jtOdHTJHpE12B00EPnCluOpn++QbOqUH8kpkZzV+SIlyvzUfFcNbYcXe2L
            3f2TI3vuzdsE8h/RLUGVbFib+tdumCwsxDTigrEsRvZqUPzTIbTyEptAFbhCzBqA
            5P+6Y6mBc4S/wP7bwmvt0l4Bl/8kZU2NNFBa+aKsO5OFTrkbMlOEncn3dAhVhah6
            raPg0aIoni44KoCFj1+eNrdO9Jyw5LR/WHv6Fa+9n/lxWx/P7+dKp1Pb0enZy6KT
            9Xw5T0AEUUGv62iMu7T7
            =LtXe
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
