apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:LNqamcfsFfb9WrxHDTlopoHGbTQ=,iv:tGu+Vs2pY9YO4RIw9SqMrqEbbE9QlImZmjwmAFRx3VE=,tag:S6DijQwvfv2zjnO4MDpiXA==,type:str]
    namespace: paperless
type: Opaque
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:zXxcWw50G8PK5XsvmXtEcukPMxcSfN33s27tXhGfcUTz5M7dtKINWaH8yZP7rtY+C57DLGozEFyPw9/ciaMevTgvmU6TkF6aEH1ss7A0udj8E3RCOuI=,iv:WvknSYODpFI84dgqCETlTrbTcdvfIgzWog4FHVipdFI=,tag:/uiEMwrA6dRj02cKhd7k8w==,type:str]
sops:
    lastmodified: "2026-07-23T12:41:14Z"
    mac: ENC[AES256_GCM,data:iQOyYGLbFq4HJRNpCwT+eza55KTQiA920+KDRAlRlTagMy40M0PkR7skkLMAUF0GPwT1ZJ1uwKZ0qOqWjd2SWaVp+JnNGgtPfzYbUz9FdlAdXJ8VOfa/8Btspo0mc9JuoHTxACrEtbBgrdJoGcIkkCpQsoqwsCLJPvBEtxmfzdk=,iv:VFezUxNQyjyJRUerzgU5LmFmRxUpd/lrUIU0J8vPmJU=,tag:rDmtpVoXgfIY3vP2ZIz63A==,type:str]
    pgp:
        - created_at: "2026-07-23T12:41:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf8DMLvWyzrz7kL/Hyk5qln1/QlXNHmbF/4Se/5kDMlsVDn
            6seiGK70EKgQMWZVr6bHNkU0R20gFlD2cP+ZgeiJXqPnh5nfjUbm9vekKUra+0h2
            hGZYMxVB2dxoSLrT9ddXpWEUFchDm46mVyvrJZpLDDw4h4kN09HB8sAwd3nKzfSR
            cerEh+3eQKmgEH1O3TBfWHJT4sjUhXWwFTa9VRC/AQxqzIvSiGbd/RKXcqp+ZWSl
            GZBMyJaqG3F7UjthyZD9NDLROIf/Cnywz7i/ra4yBMkcZjN3vP8gMiSQ4WN9avhv
            ibzPaQRw8aXgyxOQ13oy3sEu+F//xhIPHtV8DiBNYdJeAW9nEiCia77swo15Exb9
            YffwcGh1AodGJMThypR1DxNg1/JTJz12cB1W1pzSO5X97Tm9CpPFXeWAGbF6cCpX
            KyLIweUd5HTS/q5KDdJmHj5PgPMhVQJYZvbk6+GZww==
            =MBwJ
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-07-23T12:41:14Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv/YjekVbH1t2BDVQCyGWm6Z/Qf1YZJUeQVyUZuUl+oURaM
            FW3c44fTnAEufrJ0Me54TA2Y3eZmKU4hsgpz7Qnswlapa9vomESa8XKAF4X5ky19
            SqxMHeqioU5rCg/HRvHi8qmeqksSwwurPlTpHnnG1w79BjZZDIXmUmacN8e5lmcQ
            73xTIS7gEY+TSqugpSB6caLbnlt8sWWRiYlvv96Kq0EQR8dqmYMvuW7f27afWikQ
            GEEx3HhwUWbuuBX+vmCDc2e5U7kdlENhEt9ILvZYEZzL4GPDQO1WuqFSGBkavpAt
            Ksd39lCqy1MU9gJiYCcZNkn/DyvJhS3NesaZUVPjQMfYsEjhQUONGjR/iOpKZ0pB
            KIcMW+nQExZQ4y+kme3Cf/Ng+5A2oKJRJDniUjQFbVXE5R/7HmuepMr8n1tXyXv+
            A3Cmmy/RIKHxtsRWIzZJIWw6QeC22ccuALGljQ+n3pitEP1KFQdEhGtYZi5BEZVF
            7hFiIxm+LxpMR3n5yRBw0l4Bs5ci80ceW9Uuv0oH6R/qayrghOynB/Qdp4jkpCcU
            rXkosVMmbEk8EpzsXLfFx0N8MTX/U98CHFgOeMR3amk6FL2Kap4u50FtmxMP50uF
            19SAIjJXQ8h+rRWx5VpU
            =bylb
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
