apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:TIAWKg48sXKoN9UN8gpwt8OXLqI=,iv:DR4ipTR6MJpW70FiYoryCec/qzFsDjcFHnqmqts3hKk=,tag:FAePfDE7olf7b1NuoGJCIA==,type:str]
    namespace: paperless
type: Opaque
data:
    PAPERLESS_SECRET_KEY: ENC[AES256_GCM,data:RTRp/Hm2mM9qa2ZgDlXPKmMvFfg+l1meFmq01DPVptDgejhUt5vgD53ex6hMl7rX9EvynZ+FTEmZgbHdj1hKGU9DNJNHmDQQxsFuir67jEKXsRn0HXAEQMchimhqAIdM5HhI4aaWmB+1G/GRp9FxbsnJgvQ=,iv:78KzfHq8YeafOrmNhm3N8VPHoti9QKLhULdERMsoZDE=,tag:76QSR1M77s7SF0upWL9WGA==,type:str]
sops:
    lastmodified: "2026-07-23T12:55:51Z"
    mac: ENC[AES256_GCM,data:kxOGXQqZL2oCLLPYkHAyjbvSszQuctnZIL1bY21U/PFsY+1o7l/dRGUXFi19+BynhE22c8Ivjgqwc3bL98aSL6TJ1a3Pc5euFcerWZyujSD23OknzhTVCWukrQalT1mP7c0NBaeSpNIZXu5uOBK8+rkIbjEZep1w3i0yfwq4kj4=,iv:/7shgTAqLUVMcmPCNn8DPuy76q0W0L1oOk2v1UbEoV8=,tag:5ODpi0hjBeGJ3KUnDWppdg==,type:str]
    pgp:
        - created_at: "2026-07-23T12:55:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAi8dd53Gov2N+9iQw4zMirfOmKt2LDpY8KVfN5nbrP7nU
            aiBAhVxE7KsiLECFRsCFHwDGEb5c6iTE3UEyZeLMMKNNTuom0QI/4IBCpVw7hjlT
            ozyvI/TolABzA5WFM8Su9aA8lFJkkig8LnOR8AcCVUs6QwPGR2rHxgV2HQzOj9gt
            F07RaW0zVfV3g0to8m5UVCURKSjJpkURE+DsO0JUMz42PomKzaRsQu4qB9EMhx+0
            zyAdUvl6yHEhEUpYvyi++Zeomcqy8hxw6KXtur+FP2BRAGubGYezkAijI9O/7tbA
            op1mwZd+1BI93N6bS0cp7y8rgVl38WUp3d96//Z1SdJeAUHCq3VvR6lchp2Cyh2q
            hIhsqwbQoKGX/LWx8LtnMuPM1P6XJ+keiCjh4VXE+ocPKbWzkfIswRYaikhjnjkr
            jhDFUtUIGdCXdWlhFbLE4sct08QHXzM5RPyDDP4NqA==
            =nZ1Y
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-07-23T12:55:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv+MKU5FbETZfQF42xHp+E25+jr7byBOLRCsf4JnIqfO4id
            ho3YyQL7QuSDK9bUAQvtwrr2A7haZQthehROauDxd/QMtI1uhir1dQB2eh1P/66M
            yEi8D1N9xGCJXK5codxdlB1dsHP2qQKiZd1UEcVmfgySH/+8zodRzsnrmP6zkZfz
            /kRyRKVo0+PkbLyDx9VzqO6RLRUNLLuh36lo8hCrSeDS6vxFLcsq8IdkUQ0+tGkR
            MIqSsGjMZ3bJccUgD/AvQxwRdnbN88yy0SzG8gAAfd9Nvyq8keIUazKse6ZdxC1T
            KTORDGZuM/12S/fJ7SPCHgV8BnSd5ADKCHnaqEZJrPRHiysu/AFVz0QlR9+igLKK
            zPhYFEa7LATEXXOfLioSy+YqVfLRr4mJVYfCHTqAAKG72QCOF04ZyUdhRvE+QXD7
            wpWbw0Da2PXWbedL4pFLyHAI70uX7W+B2J3BD+DisI3LI8X7CQk5QT9EgrGZmJEG
            tolwfggFeLWPr1bV7BOG0l4BOCsnln7IuhpY2ggOJSLRgSlpkSXMrgpe9tuv/ni7
            ZD0GCDa4qVK6Oys83b+dMm+am+o5o7V3X3LgquQbguzY2chqg4LejSY0IYReakVp
            xKEQLx2FXS5S2hY0BtrK
            =Uuq/
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
