apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          env:
            - name: KURED_METRICS_PORT
              value: "8080"
          envFrom:
            - secretRef:
                name: notify-url