apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          envFrom:
            - secretRef:
                name: notify-url
          args: []
          command:
            - /usr/bin/kured
            - --reboot-days=sat,sun,mon,thu
            - --period=1m
            - --time-zone=America/New_York
            - --ds-namespace=kured
