apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          envFrom:
            - secretRef:
                name: notify-url