apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: kured
  namespace: kured
spec:
  template:
    spec:
      containers:
        - name: kured
          envFrom:
            - secretRef:
                name: notify-url
          command:
            - /usr/bin/kured
            - --reboot-days=sun,mon,thu
            - --time-zone=America/New_York
            - --ds-namespace=kured
            - --prometheus-url=http://prometheus-k8s.monitoring.svc.cluster.local:9090
            - --alert-filter-regexp=^(RebootRequired|Watchdog)$
            - --alert-firing-only=true
