apiVersion: v1
kind: Service
metadata:
  labels:
    app: promtail
  name: promtail-metrics
spec:
  clusterIP: None
  ports:
  - name: http-metrics
    port: 3101
    protocol: TCP
    targetPort: http-metrics
  selector:
    app: promtail
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: promtail
spec:
  endpoints:
  - port: http-metrics
  namespaceSelector:
    matchNames:
    - logging
  selector:
    matchLabels:
      app: promtail