apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: mediaplatform

resources:
- resources/namespace.yml
- resources/volumes.yml
- resources/ingresses.yml

## Important: Storage logic
#
# 1. each service must have its own PVC. -> Add 'persistence' to each chart. -> DONE.
# 2. radarr, sonarr and qbittorrent all use the same PVC as Jellyfin.

helmCharts:
- name: jellyfin
  namespace: mediaplatform
  releaseName: jellyfin
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
    resources:
      # Warning: No limits.
      requests:
        cpu: '6' # take the whole node, so that only sabnzbd can be scheduled on it. (there are 8 cores, but let's use 6)
        memory: 8Gi
  version: 9.5.3
# Below charts live here -> https://github.com/k8s-at-home/charts/tree/master/charts/stable
- name: radarr
  namespace: mediaplatform
  releaseName: radarr
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 16.3.2
- name: sonarr
  namespace: mediaplatform
  releaseName: sonarr
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 16.3.2
- name: prowlarr
  namespace: mediaplatform
  releaseName: prowlarr
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 4.5.2
- name: calibre
  namespace: mediaplatform
  releaseName: calibre
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 5.4.2
- name: calibre-web
  namespace: mediaplatform
  releaseName: calibre-web
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 8.4.2
- name: readarr
  namespace: mediaplatform
  releaseName: readarr
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 6.4.2
- name: qbittorrent
  namespace: mediaplatform
  releaseName: qbittorrent
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
      WEBUI_PORT: 443
    service:
      main:
        ports:
          http:
            port: 443
    persistence:
      config:
        enabled: true
        size: 2Gi
  version: 13.5.2
- name: sabnzbd
  namespace: mediaplatform
  releaseName: sabnzbd
  repo: https://k8s-at-home.com/charts/
  valuesInline:
    env:
      TZ: America/Toronto
    persistence:
      config:
        enabled: true
        size: 2Gi
    resources:
      # Warning: No limits.
      requests:
        cpu: '0.5' # take half a core.
        memory: 1Gi
  version: 9.4.2

# Setting proper image tags on each service.
images:
- name: jellyfin/jellyfin
  newTag: 10.9.10
- name: ghcr.io/k8s-at-home/sonarr
  newName: linuxserver/sonarr
  newTag: 4.0.9
- name: ghcr.io/k8s-at-home/radarr
  newName: linuxserver/radarr
  newTag: 5.9.1
- name: ghcr.io/k8s-at-home/prowlarr
  newName: linuxserver/prowlarr
  newTag: 1.21.2
- name: ghcr.io/k8s-at-home/readarr
  newName: linuxserver/readarr
  newTag: 0.4.0-nightly
- name: ghcr.io/k8s-at-home/calibre
  newName: linuxserver/calibre
  newTag: 7.17.0
- name: ghcr.io/k8s-at-home/calibre-web
  newName: linuxserver/calibre
  newTag: 0.6.23
- name: ghcr.io/k8s-at-home/qbittorrent
  newName: linuxserver/qbittorrent
  newTag: 4.6.6
- name: ghcr.io/k8s-at-home/sabnzbd
  newName: linuxserver/sabnzbd
  newTag: 4.3.3

# Patches to add standalone common PVC to each service.
patches:
- path: patches/container-auth-patch.yml # add env variables to each service
- path: patches/jellyfin-intel-quick-sync-patch.yml # configure Intel Quick Sync on Jellyfin
- path: patches/jellyfin-affinity-rules-patch.yml # configure Jellyfin to run on the mediaserver node
- path: patches/sabnzbd-affinity-rules-patch.yml # configure Sabnzbd to run on the mediaserver node
- path: patches/qbittorrent-affinity-rules-patch.yml # configure Qbittorrent to run on the mediaserver node
- path: patches/jellyfin-load-balancer-patch.yml # configure Jellyfin to use a Load Balancer
  target:
    kind: Service
    name: jellyfin
    version: v1
- path: patches/pvc-mediaserver-player-patch.yml
  target:
    group: apps
    kind: Deployment
    name: jellyfin
    version: v1
- path: patches/pvc-mediaserver-movies-patch.yml
  target:
    group: apps
    kind: Deployment
    name: radarr
    version: v1
- path: patches/pvc-mediaserver-tvshows-patch.yml
  target:
    group: apps
    kind: Deployment
    name: sonarr
    version: v1
- path: patches/pvc-mediaserver-books-patch.yml
  target:
    group: apps
    kind: Deployment
    name: readarr
    version: v1
- path: patches/pvc-mediaserver-books-patch.yml
  target:
    group: apps
    kind: Deployment
    name: calibre
    version: v1
- path: patches/pvc-mediaserver-books-patch.yml
  target:
    group: apps
    kind: Deployment
    name: calibre-web
    version: v1
- path: patches/pvc-mediaserver-downloads-patch.yml
  target:
    group: apps
    kind: Deployment
    name: qbittorrent
    version: v1
- path: patches/pvc-mediaserver-downloads-patch.yml
  target:
    group: apps
    kind: Deployment
    name: sabnzbd
    version: v1
- path: patches/update-qbittorrent-host-header-patch-cm.yml
  target:
    kind: ConfigMap
    name: qbittorrent-scripts
    version: v1
- path: patches/update-qbittorrent-host-header-patch-depl.yml
  target:
    group: apps
    kind: Deployment
    name: qbittorrent
    version: v1

configMapGenerator:
- literals:
  - PUID=1001
  - PGID=1002
  name: mediaplatform-env
