apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: metallb

resources:
- l2-loadbalancer.yml

helmCharts:
- name: metallb
  repo: https://metallb.github.io/metallb
  version: 0.14.9
  releaseName: metallb
  namespace: metallb
  includeCRDs: true
