apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: logging

resources:
- ../../base

patchesStrategicMerge:
- patches/promtail-metrics.yml
# TODO: Uncomment when loki network policy
# is stable and working
# - patches/loki-network-policy.yml
