- op: replace
  path: /spec/groups/1/rules/7/expr
  # CPUThrottlingHigh patch
  value: |
    sum(increase(container_cpu_cfs_throttled_periods_total{container!="", }[5m])) by (container, pod, namespace)
      /
    sum(increase(container_cpu_cfs_periods_total{}[5m])) by (container, pod, namespace)
      > ( 95 / 100 )
- op: remove
  path: /spec/groups/7
- op: remove
  path: /spec/groups/7