kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: envoy-gateway-system

resources:
- gateway.yml
- educs-certificates.yml
- client-traffic-policy.yml

helmCharts:
- name: gateway-helm
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: 1.7.0
  includeCRDs: false
  valuesInline:
    replicas: 2
    podDisruptionBudget:
      minAvailable: 1
