kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: envoy-gateway-system

resources:
- gateway.yml
- educs-certificates.yml
- client-traffic-policy.yml

helmCharts:
- name: gateway-helm
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: 1.7.0
  includeCRDs: true
  valuesInline:
    config: {}
    replicas: 2
    podDisruptionBudget:
      minAvailable: 1
    deployment:
      envoyGateway:
        resources:
          limits:
            memory: 1Gi
          requests:
            memory: 1Gi
            cpu: 100m
