kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: envoy-gateway-system

resources:
- resources/gateway.yml
- resources/educs-certificates.yml
- resources/client-traffic-policy.yml
- resources/service-monitor.yml

helmCharts:
- name: gateway-helm
  releaseName: envoy-gateway
  namespace: envoy-gateway-system
  repo: oci://docker.io/envoyproxy
  version: 1.7.0
  includeCRDs: true
  valuesInline:
    replicas: 2
    podDisruptionBudget:
      minAvailable: 1
