apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:PRs8GaiMHh1vPJHtwFY=,iv:ty5RPlQY6Ian3vMegobjGnfli7QFuDDqqBDsol1aZvw=,tag:FzrxAfCVzV3XNi7Erj+J8w==,type:str]
    namespace: pihole
type: Opaque
data:
    password: ENC[AES256_GCM,data:f8Z5YkWlH39hwWtkqIWmfsMVAwKrOYLKYHkcZu53/BNWbrBrhxK29rYlcWA=,iv:/VP3kpuAfmbkJgw36Ryeg7ZzUvnEMY3YD/ZsodjVefg=,tag:btSgS8y1wGjPfDJkT4KvLg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2025-03-03T17:34:40Z"
    mac: ENC[AES256_GCM,data:VBOnfHDpb1RwmE9g9OhSLUdsEmgeHpaBbUdh/vNRnaZMy0/yhtw9cLMLxzMI6qa74A24usRkP+69UGazedbLCAj0ZikE/ifOx96PrjdgzbY2QNYvbUfpWo6xH+Tb7eHvGyshNIH4aknoRzj3zj7Ebf7jQj+cgRKNHxEp7BakSVM=,iv:+IVAq9yCzIwStQad3HlB8iX6TeVPMWXKTTiL4L6r3lM=,tag:/4O0BiGEcfa4VMWb/80V/Q==,type:str]
    pgp:
        - created_at: "2025-03-03T17:34:40Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/YGW46FrqYr9UkV55yhP/MrjxkS+donXOBujb3sXlVHkX
            +xqTvRoZbNbLcuBGoRXVLA6AFABAKUCvDrrP84yfq0T8afFfHVsd6SGRfomSzT4J
            akdwDjiui7n4L30rsCppZYC/xh1FqejP6282TilLOZzWfUDjtJixV4mBWO1ngdWj
            94z4Dhz0elkC/h7vZ3gvno0xpNuITd8600sSE+ozfnMuozR2dqEZRP2EYWzKriZx
            PjeIkpwivdhwC0Up5gIPbqGC7xC4currvorOWwyJ/XpHg06i6cESCy729KnCQK+s
            XG3c/V5jSjYbpnzMJ5j/KeRIM+qbP2kQcdxBZDVl/9JeAQdzVs71jSU943FCv9oz
            +R6vvW1dUX4Om9TwmlI+iw5SuOKPPKg/Qg95Y6Mjahyt5dGPZCFGHYBfxI57TjF6
            9Z6BhnYl6cwS259WhlFfYCMvj+cYdzlwnUWVkyBamA==
            =6jMj
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
