apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/namespace.yml
- resources/ingress.yml
- metrics/service-monitor.yml
- metrics/service.yml

namespace: pihole

patchesStrategicMerge:
- patches/deployment.yml

commonLabels:
  app.kubernetes.io/name: pihole

images:
- name: ekofr/pihole-exporter
  newTag: v0.4.0

helmCharts:
- name: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  version: 2.28.0
  releaseName: pihole
  namespace: pihole
  valuesInline:
    admin:
      enabled: true
      existingSecret: pihole-secrets
      
    resources:
      requests:
        cpu: "20m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "896Mi"

    serviceWeb:
      type: ClusterIP

    serviceDns:
      loadBalancerIP: 192.168.0.21
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    
    serviceDhcp:
      enabled: false

    ftl:
      MAXDBDAYS: 15 # half a month

configMapGenerator:
- name: pihole-config
  literals:
  - TZ=America/New_York
  - FTLCONF_WEB_PORT=80
  - FTLCONF_VIRTUAL_HOST=pihole.k8s.cguertin.dev
  - FTLCONF_DNS1=8.8.8.8
  - FTLCONF_DNS2=8.8.4.4
  - FTLCONF_dns_upstreams=8.8.8.8;8.8.4.4
