apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/namespace.yml
- resources/services.yml
- resources/deployment.yml
- resources/ingress.yml
- resources/pvc.yml
- metrics/rbac.yml
- metrics/service-monitor.yml

namespace: pihole

commonLabels:
  app.kubernetes.io/name: pihole
  app.kubernetes.io/managed-by: kustomize

images:
- name: pihole/pihole
  newTag: 2022.01.1
- name: ekofr/pihole-exporter
  newTag: v0.1.1

configMapGenerator:
- name: pihole-config
  literals:
  - TZ=America/New_York
  - WEB_PORT=80
  - VIRTUAL_HOST=pihole.k8s.cguertin.dev
  - DNS1=8.8.8.8
  - DNS2=8.8.4.4
- name: pihole-custom-dnsmasq
  files:
  - config/02-custom.conf
  - config/addn-hosts
