apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/namespace.yml
- resources/ingress.yml
# - metrics/service-monitor.yml
# - metrics/service.yml

namespace: pihole

patchesStrategicMerge:
- patches/deployment.yml

commonLabels:
  app.kubernetes.io/name: pihole

images:
- name: pihole/pihole
  newTag: 2025.02.7
- name: ekofr/pihole-exporter
  newTag: v1.0.0

helmCharts:
- name: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  version: 2.28.0
  releaseName: pihole
  namespace: pihole
  valuesInline:
    admin:
      enabled: false
      
    resources:
      requests:
        cpu: "20m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "896Mi"

    serviceWeb:
      type: ClusterIP

    serviceDns:
      loadBalancerIP: 192.168.0.21
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    
    serviceDhcp:
      enabled: false

    virtualHost: pihole.k8s.cguertin.dev

    ftl:
      MAXDBDAYS: 15

    adlists:
    - https://raw.githubusercontent.com/StevenBlack/hosts/refs/heads/master/hosts

    whitelist:
    - raw.githubusercontent.com
    - github.com

configMapGenerator:
- name: pihole-config
  literals:
  - TZ=America/New_York
  - FTLCONF_dns_upstreams=8.8.8.8;8.8.4.4
  - FTLCONF_dns_listeningMode=all
