apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- resources/namespace.yml
- resources/ingress.yml
- metrics/rbac.yml
- metrics/service-monitor.yml
- metrics/service.yml

namespace: pihole

patchesStrategicMerge:
- patches/deployment.yml

commonLabels:
  app.kubernetes.io/name: pihole

images:
- name: pihole/pihole
  newTag: "2022.10"
- name: ekofr/pihole-exporter
  newTag: v0.3.0

helmCharts:
- name: pihole
  repo: https://mojo2600.github.io/pihole-kubernetes/
  version: 2.9.3
  releaseName: pihole
  namespace: pihole
  valuesInline:
    resources:
      requests:
        cpu: "20m"
        memory: "512Mi"
      limits:
        cpu: "250m"
        memory: "896Mi"

    serviceWeb:
      loadBalancerIP: 192.168.0.203
      type: ClusterIP

    serviceDns:
      loadBalancerIP: 192.168.0.203
      annotations:
        metallb.universe.tf/allow-shared-ip: pihole-svc
      type: LoadBalancer
    
    serviceDhcp:
      enabled: false

    ftl:
      MAXDBDAYS: 15 # half a month

configMapGenerator:
- name: pihole-config
  literals:
  - TZ=America/New_York
  - WEB_PORT=80
  - VIRTUAL_HOST=pihole.k8s.cguertin.dev
  - DNS1=8.8.8.8
  - DNS2=8.8.4.4
  - PIHOLE_DNS_=8.8.8.8;8.8.4.4