apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:uLYiwWux,iv:ePanr+EEzLYd7kkmDKluJzZ+rBtGMi43LwWdm4sfvcE=,tag:SBMfM5vPmS6swEtBCtVA8Q==,type:str]
    namespace: ddns
type: Opaque
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:kQUt8mMq9Vt1XTVbkZrRJh112CfsGPVPftD/iKT7g6y+IjpCsJTL0OyY6RZ+eRoBQ4SXzeBYfYA=,iv:gn/qyTIrfjOX1UFWAp90W32xD/WDbZUFIQibM/nYeKY=,tag:BuwOXtpn9zDYq1O0meBGjA==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:AxjWUVRZbiDTitjw3JLic+ak0ueZ1fHRc+/A4Icvs9V7p4HNiU0VSWF3hDkqjdSy7lIobiQqx4o=,iv:s0IZusJ4uNWwTnlF+Ft6HP3/P3QiBWgQ7dg8Cv8a/zQ=,tag:XlqAJ3uTjRuCxc8o0zP9vQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-21T02:03:19Z"
    mac: ENC[AES256_GCM,data:tadVrXhVfzF/qykdDTF5TQq5Viz13ctpvdoXPr+66r1x5yownLDID5n+vRYPVhnSWLg0M8TOyf4OgbQ1mpb6eRROijtc69GOxg2PkxtYYZmAEYk0OeV3AYS+ngigZFztoP10MUh1F68m2jfaUgkZeWiSQgnEbHtkwfC1LSKbpEc=,iv:2TftwWq0guWQlp8b50fldUf98cbw7xk7zCmoMYAJR24=,tag:2U+hvnfjPc+5meuJp0/cbg==,type:str]
    pgp:
        - created_at: "2024-01-21T02:03:19Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+LT4S+3vRfOzDoRhhD2zKvF4w3JlciNSpIWZwzwf04xyi
            oKq2XCXAAEcfZ8GM/ZWKqA3rle/OK7tY8pfjLFZf96WdLmrylyUMmdWKVLT/YIkS
            31AVq/BwV7cr37V1RkaorjqSgD8LbenK3KCwG1rXIBodFBEnrVN9f1ZRk4j92+yR
            x0Qf2NOpwGThUN/paK8p8sIXhL2kj/kORqdJYpJN3rMrWCdBG0f1pZdXbj5AlQ0k
            isiEc+CJHbTEi+UQCv9A8v/GPo722RSyqc8p3IsUE1hTIaeMyPMOo1U5tqO8vaTG
            3vDmTi0oFit+QczI4GiDeILsVUXTMWBG9DTYeI9jH9JeAXzuWXGrFJrACvnuzQ2o
            9AgN+U47+yc4HeBFSTEOqUm9fRuneSDkQFRvkA7i1ytG6E/bimERtXLfthUZXboa
            H9F7Z7FHblt394gX3AYcNXj28LDuL1M4zuoBpUXnow==
            =M5EN
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
