apiVersion: v1
kind: Secret
metadata:
    name: tokens
    namespace: ddns
type: Opaque
data:
    GITHUB_TOKEN: ENC[AES256_GCM,data:DjHrB1MT7uKpUkTrHxHlhen35aJzIj3YBAfBCgTCvWmNzpU4z/NZ1/7fsE+G2SMoX/LwWUmGFys=,iv:MOfe9k79mrmWOvpl1PJczsCxmLiPVJHQ3992IVuoQIk=,tag:w2dUOmNzioU5ZStZ/odvGw==,type:str]
    CLOUDFLARE_TOKEN: ENC[AES256_GCM,data:ACOvkJA90xKT2H9jveWkBnQOpqjJgNzozqYr4Vw7zAj7NX3Yg4IazBU8vMvMgpVYNHzmJ/txS44=,iv:Yr5huE0/d730cT//bmA0FbLCZfZrkkHbRE247AKFtZs=,tag:CO6MEDA3JPJVYk5C9LwZMQ==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-01-17T04:47:09Z"
    mac: ENC[AES256_GCM,data:kJdT9G4uQYhexVVaz4SwsNcIdKiOYnZJFH+PR1PGkSLuQg4KP0BEGALr17iobco/TTiEdyUh6dHDjvnzO5dX8aPjoi4Ow1SDgNV9SZNQeAOhJ7jgVLFXn0yEXOFZGgR/EmDGKXCRYNbrfG3KyCD6APTdGkT5NgfRDXpneCCb2NM=,iv:I0/P0W5Y08TPlDEruPKF708SXclE9utnDCjkAd4Jh9c=,tag:8bF2hkuTba9XCZzqq8JttA==,type:str]
    pgp:
        - created_at: "2023-01-17T04:47:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf+NmcCFLl7eHmBrPyr3PYUPQT07Uw4ROLhq8qXXeUdK5yf
            SQEYnIhWeoR7sHvSTsnFXSqPDMwqoHLgoVVH2s9U5qTe697BtCCjcvLxbNUwqiAu
            9OgG9N0fXezTTUN30VcTKtBbsw5F9omhXVs2pg71xd2qe5WWzNPMCiNdSBA+co84
            FWjgN56SJxY9i5s7kBK6D5t16778Rn2C8BYTVD+NhFXo96V0FV+TA1FLQZQCueL7
            5MhkDonvXaiJn8E1puD9neoxGL4irao1JY9P/T7w+9ExU1bRvNAPJVb/r3i615LJ
            fz1MpMChAGyyXj2MeYKlvsGDKez/eoHCFof/FV7olNJeAeHni4qJKfyyBTPxLV8S
            mnn/mELkI640m/ClMMnlVZperEovp66tAj55Fl7P0e+BhbsPBGUz/V3UWrTsCwVe
            Md56gd9g/1/qSjfdGtPze0C+6JK8HttSn5ektlNeTg==
            =unEC
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2023-01-17T04:47:08Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf+IP9sZQvS5iD438qN5Ab0ko61H7OXSb3BRLjtLfibqNIr
            vcmCNQv/iciuS8mIjL+Y7jwj7ygUVL3/prJsuUJAFIi0nCzv4Qb3rAvER5Ty+wHO
            Fyr9D0X5sxwJF+GTvux/FbnR0eHNpRl3X8SoQ+4OKHl34JSjRQgyYBvuJhQC2548
            fL00FC/aoxIXlRpAGQ/e0bzyGBQ3TRLRBO6RMx5FbIOTXwVTBjzpIvHHDH+y6ULw
            Y1l1F93UVIHffg9gbWGbfnY6N9K8Ib9dHB3xQbM9z+A/v4x7fc6sZsBYdURHg0JG
            uNeN43a8ilHYxVIwgTMeddYAxXmiL7lVIj9Z37d1htJeAYA0h5EPXDdfxO6qiUm8
            jXXushYVGVgZPC03eSOxkWhLQ6qj0+cJWe+SeI9hwawhhsVhMYvanGu3xyZNtosl
            5CCFPOz/6XxCSUYuHnMv0aK3cDWYRrGr4aYjzAkAmg==
            =r3EL
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
