apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: replicaset-ready
spec:
  metrics:
  - name: replicaset-ready
    initialDelay: 15s
    failureLimit: 5
    successCondition: result[0] >= 8
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(kube_replicaset_status_ready_replicas{namespace="blog"})
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: traffic-generator
spec:
  args:
  - name: service-name
  metrics:
  - name: traffic-generator
    initialDelay: 15s
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: load-test
                image: alpine:3.14
                command: ["/bin/sh", "-c"]
                args:
                - apk add curl --no-cache && for i in {1..60}; do curl --max-time=2 --fail https://{{args.service-name}} || curl --max-time=2 --fail http://{{args.service-name}}; done
              restartPolicy: Never
---
apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: slo-success-rate
spec:
  metrics:
  - name: availability-sli-success-rate
    initialDelay: 45s
    # 99.99% Availability SLI
    successCondition: isNaN(result[0]) || result[0] >= 0.9999
    failureLimit: 5
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(
            traefik_service_requests_total{code!~"5.*", exported_service=~"blog-blog-active.*"}[5m]
          ))
          / 
          sum(rate(
            traefik_service_requests_total{exported_service=~"blog-blog-active.*"}[5m]
          ))
  - name: latency-sli-success-rate
    initialDelay: 45s
    # 99.95% Latency SLI
    successCondition: isNaN(result[0]) || result[0] >= 0.9995
    failureLimit: 5
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(
            traefik_service_request_duration_seconds_bucket{le="0.7", exported_service=~"blog-blog-active.*"}[5m]
          ))
          /
          sum(rate(
            traefik_service_request_duration_seconds_bucket{le="+Inf", exported_service=~"blog-blog-active.*"}[5m]
          ))