apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: slo-success-rate
spec:
  args:
  - name: service-name
  metrics:
  - name: traffic-generator
    provider:
      job:
        spec:
          backoffLimit: 1
          template:
            spec:
              containers:
              - name: load-test
                image: alpine:3.14
                command: ["/bin/sh", "-c"]
                args:
                - apk add curl --no-cache
                - for i in {1..60}
                  do
                    curl -i https://cguertin.dev
                  done
              restartPolicy: Never
  - name: availability-sli-success-rate
    interval: 5m
    # 99.99% Availability SLI
    successCondition: result[0] >= 0.9999
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(
            traefik_service_requests_total{code!~"5.*", exported_service=~"blog.*"}[5m]
          ))
          / 
          sum(rate(
            traefik_service_requests_total{exported_service=~"blog.*"}[5m]
          ))
  - name: latency-sli-success-rate
    interval: 5m
    # 99.95% Latency SLI
    successCondition: result[0] >= 0.9995
    failureLimit: 3
    provider:
      prometheus:
        address: http://prometheus-k8s.monitoring.svc.cluster.local:9090
        query: |
          sum(rate(
            traefik_service_request_duration_seconds_bucket{le="0.7", exported_service=~"blog.*"}[5m]
          ))
          /
          sum(rate(
            traefik_service_request_duration_seconds_bucket{le="+Inf", exported_service=~"blog.*"}[5m]
          ))