apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blog
  annotations:
    linkerd.io/inject: enabled
spec:
  strategy:
    blueGreen:
      activeService: blog-active
      previewService: blog-preview
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      scaleDownDelaySeconds: 30
      prePromotionAnalysis:
        templates:
        - templateName: replicaset-ready
          clusterScope: true
        - templateName: load-tester
          clusterScope: true
        - templateName: slo-success-rate
          clusterScope: true
        args:
        - name: service-uri
          value: https://preview.cguertin.dev
        - name: service-name
          value: blog-preview
        - name: namespace
          value: blog
        - name: min-replicas-ready
          value: '8'
      postPromotionAnalysis:
        templates:
        - templateName: load-tester
          clusterScope: true
        - templateName: slo-success-rate
          clusterScope: true
        args:
        - name: service-uri
          value: https://cguertin.dev
        - name: service-name
          value: blog-active
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
    spec:
      containers:
      - name: blog
        image: cguertz/cguertin.dev
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "128Mi"
            cpu: "250m"
          requests:
            memory: "64Mi"
            cpu: "125m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
