apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: blog
spec:
  strategy:
    blueGreen:
      activeService: blog-active
      previewService: blog-preview
      scaleDownDelaySeconds: 300 # 5 minutes
      autoPromotionEnabled: true
      autoPromotionSeconds: 30
      postPromotionAnalysis:
        templates:
        - templateName: slo-success-rate
        args:
        - name: service-name
          value: blog-preview.blog.svc.cluster.local
  template:
    spec:
      containers:
      - name: blog
        image: cguertz/cguertin.dev
        ports:
        - containerPort: 80
          name: http
          protocol: TCP
        securityContext:
          allowPrivilegeEscalation: false
        resources:
          limits:
            memory: "256Mi"
            cpu: "500m"
          requests:
            memory: "128Mi"
            cpu: "250m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
