apiVersion: v1
kind: Service
metadata:
  name: blog-active
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: blog-preview
spec:
  ports:
  - name: http
    port: 80
    targetPort: 80
    protocol: TCP

