apiVersion: v1
data:
    secretkey: ENC[AES256_GCM,data:dZXXn6QHvwVbjQOfih8vo1fzkvzmP0+zmIjSDqbcuoGtKJpbmDu6zO5mBuwF0K5PM1Z4Neg+Wo8KoVMY4bX2RuozgmNCHtVmIR2ExqlNOKNaqLz5ImPxHke73tUc9haUrg+Veddh7Lr5TQoTNKb3bunNICpOHEtxJwbdSvnfvzivZ/Vccw24KEAP9U39IMVRYPsfiSE4rZEZQ11aczhE1DGyS4bUW1gaS2/eZpweW4wwXE4sHG8TzhFEOSI1WlI1X1vA8eguvbIMVI8kGctuw8G4M0VateZSsNgF3gIZr417OjW6ighrdQ==,iv:IWGUmZBuL2FhyJWALA8au/I516FK8INM3Qgj28XCJRw=,tag:TSW8BMSqO7tEN4fYB+tgJQ==,type:str]
kind: Secret
metadata:
    name: memberlist
    namespace: metallb-system
type: Opaque
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2021-03-27T04:23:23Z"
    mac: ENC[AES256_GCM,data:d1z4t9KVN6pz+s5oCTbqf+v6VfZKjFr1KReAl3vCsX5WvACDGhNZQ3drtPYSJA6IJM7qZF601HXKjZOBOjnLKlMhsubvIU14Q9OSOnfq2abyU+eYvfINQDzIswWwOzxMA0Owh6pBZXo3mPACzSdENKnn1RilLSG6Z9TP1oeeRqY=,iv:zHRdf6yBm0A0koFAePUROQVA2MrDsFLYiOio7II7QNc=,tag:p4Y53wUOHT+/7HxRX19Fxw==,type:str]
    pgp:
        - created_at: "2021-03-27T04:23:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQgAqJWSaTu25dcGfbbJ2RCjQqlFQKQ0EKif4yzOZDTtE4E9
            EgaNVsK42k2LqOuFP8idncaos27tYGDNRTEY33zMcZr5b/VeSQcmCaDxBIu00Q+l
            XAxl81DcG58nz0Y38txs1DNhcuODakjvOPMJBS5+r0i7R4XQ9sYefYGyyEYL1FXK
            yiJ55A17ysBCxMBzfGPciWYZKc4KjaDVzi54VyNjAUVDnkiqXOcO5Zat5APQeXco
            qk39GAfFLSUFp3evfuQ8javGDgJjEGLbiH5ixVy+mmi1PzI7IPgW6304+Q2a6VvY
            Id5cV3om/UAzKklQoYAmRoHlPnJfGDMZqfPNnwoW5tJeAelvZ5vA6KSRKHhMkgOq
            7cCwyKplfH714zWC6KWGFApO8Lttuy9aMVA+WfcABYlrZSJj9SaGhRoQTO1SraJP
            QfofMkOk1paniaxK7OsW82WkeYXhjtZgBjkoea6TwQ==
            =ASlG
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2021-03-27T04:23:23Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf/VWz4GfACVMrozTL+qoIaCgIUcK4CRhr97GrO4e2safKb
            M4daE681SuJ5JCUzC+gtpPeq8MKqe6lFYpUUwK/AiNRCxlNZqQeDLRYq+hZJ5+Vh
            xg160bkK0szIQU+9kq8W6uieLd8W+fHna6E3Q8Otb19+TRrUvZgAbk0+3qj9YApq
            5hX4wi8I4XFkjyAHMlB6MST1NRTBX2utGy0UINIg8aAvVG6ECzby5FKxbih6Dvfp
            UDNP1g4g56dYQIY4vjWPLgTBtwd5AS6DJGKCnDlRsQhOFZGuZBfp4R9lYA1Twfay
            1C2PptmFUA8nUARDSiWu7wnyC+jSavuGOdXUEz5n3tJeARcfSuY4pwhDGbVIuEs/
            HiopNo7wjhgLZwxvUt7W5EPUQL6fGHpJhGWOHdd2aSnIT/4CaoOLl2TOTSVvdTCZ
            jqLC8J1NiTyLg6wvqxkrQVgftsqL9vUdRiwDHDgqpQ==
            =uQTv
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
