apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../../base

patchesStrategicMerge:
- patches/set-product-to-observe.yml

generators:
- secrets-generator.yml

patches:
- path: patches/suspend-cronjob.yml
  target:
    kind: CronJob
    name: lululemon-stockchecker-cron
    version: v1
    group: batch
    namespace: lululemon-stockchecker