apiVersion: batch/v1
kind: CronJob
metadata:
  name: lululemon-stockchecker-cron
  namespace: lululemon-stockchecker
spec:
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: lululemon-stockchecker
            env:
            - name: LULULEMON_URI
              value: https://shop.lululemon.com/p/bags/Dual-Pouch-Wristlet/_/prod10920248?color=0001&sz=ONESIZE
