apiVersion: apps/v1
kind: Deployment
metadata:
  name: cert-manager-cainjector
  namespace: cert-manager
spec:
  template:
    spec:
      containers:
      - name: cert-manager-cainjector
        args:
        - --v=2
        - --leader-election-namespace=cert-manager