apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:FujuvYVrf0QUURkF9Z1a7GVLcl0=,iv:fLsnRGIvWnRxyWhYkjx73Uo6kVuq4MAvuCKyKPJMIuk=,tag:OST4xbg3IbZISEfT/EmtaA==,type:str]
type: Opaque
stringData:
    api-key: ENC[AES256_GCM,data:Wo5s5cpx/IOHKbdwJENfu6Y72jS02B6sWasLjIldMLt+ZK1jm0TcCSjEhWHGrLBIvleZsHtWVVA=,iv:6T9uSJiMh1jCETk5N3Rz00Whjq8v17amf+IzFKBk/TY=,tag:ywirTCbk6iACtRyzTvWfrQ==,type:str]
sops:
    lastmodified: "2026-03-11T19:02:45Z"
    mac: ENC[AES256_GCM,data:KZ8seJR4b2OaUWh4fEQthd/36pEmG1MWuYuJ1d8bLgvT5ZUGAKSWDsWSopAPKU/hRaEydtN/8lxAk7siVYieWnWbOuNRM4njfG6EsIJB/n/UO0FKLvs00U29x4+C8yKY7qk4hCmycBizu03LUWZnen73xjf+YbGCWPZUuoDBqKU=,iv:F3vGk20jfk4e/2x6vzFWUJHrRbhrEPL1POX2zRJSwko=,tag:vMiMD4AIL9jb80H5YyGaXw==,type:str]
    pgp:
        - created_at: "2026-03-11T19:02:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAhHp3B3tJXH5/RM8RbK38QlVaFlf66gPhOcGNYilqkh1x
            Ef3oUKYOdTsB30N7wK8fJVRzH/IPg84iYhFuEiFRise/quAtJ9Xd537j8K11c+Zw
            ORJl6fyO2xMs+gK8E9iu5yr4lpTQPHQs0+18kYeuIDZ2He1VtKTgxoaX7fBRW7Wx
            EM0ugHilIgGVSnQESGHHYXok2nQJCJuICkSVxJiz+NykqpZtO0htA+dtObX8ZRHX
            o7uBtgJZsvPQQzMUgnPHqIVoPSbUffe3N9ThqrBnIbKxdLXPBFHdt6h8a2EAZbyr
            Cle0OPIsSwfolzVxtklcLXNIvTcuRXepRPolNtXHoNJeAfpEhxB8WqnQxRAeoG3j
            bdRIaGWLQ5pNkhznc1nZU7L27O+6AcvpzTZrH84hxBMtpiVVLHrPRC7tfTVg7P+w
            RlnarvpYP4h3YPwh3ot7Wk4kz3WXEc6Ar7T4G6+ccw==
            =rrjc
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-03-11T19:02:45Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv+IEkWkwDsIyIRnlUS0SpJhRASWxdBJ53yAIstFVfcSxZd
            PCHlC1wQGOTXgjgHHAp+Y0em2bvYnTjvISBkUAGOxikHG3xR4zzaBoMrfI8XQLYk
            DV+C693nsfCdGAv6dALC0mU034J4rS1sXBxQQYva0vHJKoru/e7+lyMJtl+pQJyX
            WtuVMi2r5iztxwOibmxugxpNnBCBvMktROsMGgz18AX+ODQu8XkoyRuSrEiv/GHs
            X73Fu9uHWLhDzFid4zDvYytbVgakt4N7iMApGzHepfOkVuvDU4KhsLBd5FrFkbVG
            mkksQLpKqn0+qqkXb9FBWUAaw+J8x+9WvK6bnVzrQuRoKhJKJm5HAZ9Q9NNxk2kO
            Git3PggFw+R+WxyG/wEJDIHPjMpqjJTi9BkcOSLWFpiVKxhsj3n3+JoFvyaPTpEa
            lx1Iwbjgg6hd4ASQ+hqJi6z/1pftAyAzUPuKojgoZ2SBmJ0nzh7bdFevdNSXGe5P
            mLPCPjcRt4alGq+iJirn0l4Bu1wT5MnN06Gm2h5T3CfhrrkliD1G5qbnynv+2jAa
            GFbjQ2A3Myk6AF7c6n6HDUr6HG+hZ2iw/1aQ9LUPZ6HlCrzzPt2bBnKvc1grKVlm
            viDs/42zUgthjquUf67L
            =YMqA
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
