apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:8SyamVlWPsMPwijdCOiqzfFYl5w=,iv:kDtzvue6yTqLdxd5wyrlGOwQabgrF1ZasEQzMoN1VaA=,tag:WMuKZpspGIvzKBmqaZwWqA==,type:str]
type: Opaque
data:
    api-key: ENC[AES256_GCM,data:Ix8nNYfOhfeKD8AAgx+Gos/Ew3Z0bFwVlYe5qNFrW3o64fqMPku5lVj1XGgK7nLyJRSxl9xPHWg=,iv:f9wW8E9VqVXqe2F20x7zWbpOcr0mhWcXfG1xBuHu98s=,tag:W0QhPUCoOUza3AcLx1OgCA==,type:str]
sops:
    lastmodified: "2026-03-11T19:10:02Z"
    mac: ENC[AES256_GCM,data:SOmBwJlMW9raHQDz3OYJyH2pRaHJ7rKtxAsgMsUO0k9+aqVqI83Z7XWVaxIF0FR5d0DjX0b5obqmVWDO74ax5kWY/c8FtVMiMOqIL1CDRj/RSLuhI9Na8mxtoYub0lldBObWKIONZOoM3Eq9qM+UCAuv+RTZhCoP4mYrW08dJoU=,iv:guqwioRtqG/dl/FhlrS+OjRqNpoRmjWSGZz6z6l6wWc=,tag:XkZH9xYB42pLy5dk5V+Cbg==,type:str]
    pgp:
        - created_at: "2026-03-11T19:10:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9FAUzt85PTmXY2RL3bg0OtEBlzrMJV5Fql7KS43uMRykD
            ym91mzVnVbvjLjkXMN7JgJ7Th5iHQOZeVuI/Bi3sVlRTYyN7fdgNi4/j9+m3SRzI
            O3bryKLJlzDx3Wt/gprwKnbuKcCH/RrDoqK6LKopXbd/BYrGapuLNqKNWp5fm6Nn
            fyIn7Nz9d/dQgINoVXv/8Y5CbYpYLbaau3aJJn5Qvgzo84s8f4zUNpLWMHWCWUdB
            iFAV0oiVgo610bUNFo+/X7DITeTAwEdhBlEh6xxpJBkXVytGsWUFTHhNrAJIygOH
            GhS6OMONSlmausYlA21JJr/O0fJ6/238faM3Jmo/ctJeAVxezneT6DnJnqXuk2sk
            K7jfyw7t7n2lsZEu/QoWcGbj3F9T6wL8z+Biqg0ePu/ZUlonJAR99QpKvRtm2dqb
            PRDAQO09jJhMjVqoQcW7oAf/PfjrQb7Hwosieu4M0g==
            =iq/B
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-03-11T19:10:02Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQv/ZwBrOI5fpWdbh291oJlVjmM80iwMNINeLl73RCqcvydy
            X/8n0mDGKnbF5K/doMDGNey67bpPbI21uTHY5tc26cGGFAR7aANsLChUVA3T8Usi
            GmuGSHm1HCX36+d5sAjd5rXyco3/cy49p3Tktcl2jtknIcMHM2Wa3MksUFF0yRhr
            +0X5Qvjc46pKMeTfnHQPGo/W5WeoXcsC9k8z7WFqNTT+B4MXD3MQJUSyYLK9xxjj
            lb98MT50scW8VEAacHSszrwm/0TCNi4VtNjiFvumWqiO0dJYDoWbvZzb9V5F/uam
            mbvlEURbekLdnkip8SeTdWJqyR2/DMn9jMKlpqlj3mz1VBh4JGpNUuJ7AEk7BpA0
            ehIjKhnCnsa8BPoz25mo/3KelizYeCbbW5XAakqa5Dr7TCg2EW+0NqBe/7mmEZfv
            OdoUg4582da+pLnm/SLcjBCjANf6MBuxx5sKXUvQPFKY/Tpa5+UjN7i0V4wtCM/G
            EFSdST5dyVk8TVE8z6ve0l4BD3oOJ1JHIZVMxeMnU5uhjrul++jmygkVWvN8leuH
            k59UBzpvfVQBMVFRloBbH56egfWOlEXlxNUak3sPeJjiivn5NPjUmft8A9mHszHL
            dQ6f7jRYK4/FKEiRK3Ja
            =aCsU
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
