apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/other: metrics
  name: argo-rollouts-metrics
spec:
  ports:
  - name: metrics
    port: 8090
    protocol: TCP
    targetPort: 8090