apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: production
  namespace: argocd
spec:
  sourceRepos:
  - 'https://github.com/cguertin14/infra'
  destinations:
  - namespace: '*'
    server: 'https://kubernetes.default.svc'
  roles:
  # A role which provides read and delete access to all applications in the project
  - name: read-delete-only
    description: Read and Delete privileges to production
    policies:
    - p, proj:production:read-delete-only, applications, get, production/*, allow
    - p, proj:production:read-delete-only, applications, delete, production/*, allow
    groups:
    - homelab-infra:SRE
  clusterResourceWhitelist:
  - group: '*'
    kind: '*'