apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: linkerd2
name: linkerd2
repo: https://helm.linkerd.io/stable
version: v2.11.1
releaseName: linkerd2
releaseNamespace: linkerd
includeCRDs: true
valuesInline:
  installNamespace: false
  identity:
    issuer:
      scheme: kubernetes.io/tls
      
  # Public trust root certificates,
  # no harm done when exposing them.
  #
  # See:
  # * https://github.com/linkerd/linkerd2/pull/6455#issuecomment-882765601
  # * https://github.com/linkerd/linkerd2/issues/6108#issuecomment-842653274
  identityTrustAnchorsPEM: |
    -----BEGIN CERTIFICATE-----
    MIIBjTCCATOgAwIBAgIQH8VVdG+xjxrY54MzJVkrDTAKBggqhkjOPQQDAjAlMSMw
    IQYDVQQDExpyb290LmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjAxMjcwMzMw
    NDJaFw0zMjAxMjUwMzMwNDJaMCUxIzAhBgNVBAMTGnJvb3QubGlua2VyZC5jbHVz
    dGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAE0269CsfMVt9YDO7o
    JWlY25uLKgoxJG+qpcemApOlry+NPqP/4hsRvVAwZOlSRmCRxnTxVii13xZSFC2v
    BE0g4KNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8CAQEwHQYD
    VR0OBBYEFKD2KoHYTSTtlDeSq9pkibXpJVxFMAoGCCqGSM49BAMCA0gAMEUCIELD
    HId9IY5BpmbpKvoGWrPDpJaPvX+w8CseD8HVa/KOAiEAphLeZDP7QHuauakGDCeW
    dNeourPm0TkurhOIMOEDvgA=
    -----END CERTIFICATE-----

  policyValidator:
    externalSecret: true
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIBkzCCATmgAwIBAgIQCXsh5oTxvji06VcEPx0UcDAKBggqhkjOPQQDAjAoMSYw
      JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjAxMjcw
      MzM0MTRaFw0zMjAxMjUwMzM0MTRaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
      ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQsgjAJ9L
      eMH0EGK6+5IkYSbWJOb0g4XbU0Wy4TUlD4MN/XmeY3Ks4OpIcUXwXZ/L8x5ABWUZ
      RNJfx/fSaKCpsaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
      AQEwHQYDVR0OBBYEFAsiwIPXzZtAem5r7k2M93vMsnf4MAoGCCqGSM49BAMCA0gA
      MEUCIQD7nFDGD9rE7BKBvniRc++BTVbanOSRGygg709fiLJLWwIgcHQ3Mu2gk5qx
      +zWYQXkIcn9kLT4XV5WSa0sSzUfAxrc=
      -----END CERTIFICATE-----
  proxyInjector:
    externalSecret: true
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIBkzCCATmgAwIBAgIQCXsh5oTxvji06VcEPx0UcDAKBggqhkjOPQQDAjAoMSYw
      JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjAxMjcw
      MzM0MTRaFw0zMjAxMjUwMzM0MTRaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
      ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQsgjAJ9L
      eMH0EGK6+5IkYSbWJOb0g4XbU0Wy4TUlD4MN/XmeY3Ks4OpIcUXwXZ/L8x5ABWUZ
      RNJfx/fSaKCpsaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
      AQEwHQYDVR0OBBYEFAsiwIPXzZtAem5r7k2M93vMsnf4MAoGCCqGSM49BAMCA0gA
      MEUCIQD7nFDGD9rE7BKBvniRc++BTVbanOSRGygg709fiLJLWwIgcHQ3Mu2gk5qx
      +zWYQXkIcn9kLT4XV5WSa0sSzUfAxrc=
      -----END CERTIFICATE-----
  profileValidator:
    externalSecret: true
    caBundle: |
      -----BEGIN CERTIFICATE-----
      MIIBkzCCATmgAwIBAgIQCXsh5oTxvji06VcEPx0UcDAKBggqhkjOPQQDAjAoMSYw
      JAYDVQQDEx13ZWJob29rLmxpbmtlcmQuY2x1c3Rlci5sb2NhbDAeFw0yMjAxMjcw
      MzM0MTRaFw0zMjAxMjUwMzM0MTRaMCgxJjAkBgNVBAMTHXdlYmhvb2subGlua2Vy
      ZC5jbHVzdGVyLmxvY2FsMFkwEwYHKoZIzj0CAQYIKoZIzj0DAQcDQgAEQsgjAJ9L
      eMH0EGK6+5IkYSbWJOb0g4XbU0Wy4TUlD4MN/XmeY3Ks4OpIcUXwXZ/L8x5ABWUZ
      RNJfx/fSaKCpsaNFMEMwDgYDVR0PAQH/BAQDAgEGMBIGA1UdEwEB/wQIMAYBAf8C
      AQEwHQYDVR0OBBYEFAsiwIPXzZtAem5r7k2M93vMsnf4MAoGCCqGSM49BAMCA0gA
      MEUCIQD7nFDGD9rE7BKBvniRc++BTVbanOSRGygg709fiLJLWwIgcHQ3Mu2gk5qx
      +zWYQXkIcn9kLT4XV5WSa0sSzUfAxrc=
      -----END CERTIFICATE-----

  ## HA configuration
  # 
  # The following values contain the values needed to enable HA mode.
  enablePodAntiAffinity: true

  # proxy configuration
  proxy:
    resources:
      cpu:
        request: 100m
      memory:
        limit: 250Mi
        request: 20Mi

  # controller configuration
  controllerReplicas: 3
  controllerResources: &controller_resources
    cpu: &controller_resources_cpu
      limit: ""
      request: 100m
    memory:
      limit: 250Mi
      request: 50Mi
  destinationResources: *controller_resources

  # identity configuration
  identityResources:
    cpu: *controller_resources_cpu
    memory:
      limit: 250Mi
      request: 10Mi

  # heartbeat configuration
  heartbeatResources: *controller_resources

  # proxy injector configuration
  proxyInjectorResources: *controller_resources
  webhookFailurePolicy: Fail

  # service profile validator configuration
  spValidatorResources: *controller_resources
