apiVersion: v1
kind: Service
metadata:
  name: linkerd-metrics
  labels:
    linkerd.io/control-plane-ns: linkerd
spec:
  selector:
    linkerd.io/control-plane-ns: linkerd
  ports:
  - name: metrics
    port: 4191
    targetPort: 4191
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: linkerd-metrics
spec:
  selector:
    matchLabels:
      linkerd.io/control-plane-ns: linkerd
  endpoints:
  - port: metrics
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: prometheus-k8s
  labels:
    linkerd.io/control-plane-ns: linkerd
rules:
- apiGroups:
  - ""
  resources:
  - services
  - endpoints
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - extensions
  resources:
  - ingresses
  verbs:
  - get
  - list
  - watch
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: prometheus-k8s
  labels:
    linkerd.io/control-plane-ns: linkerd
subjects:
- kind: ServiceAccount
  name: prometheus-k8s
  namespace: monitoring
roleRef:
  kind: Role
  name: prometheus-k8s
  apiGroup: rbac.authorization.k8s.io