apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: pihole-service-monitor
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: pihole
  endpoints:
  - port: metrics