apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  name: kured-rules
spec:
  groups:
  - name: reboot-required
    rules:
    - alert: RebootRequired
      annotations:
        description: Machine(s) require being rebooted, probably due to kernel update.
        summary: Machine(s) require being rebooted, and the reboot daemon has failed to do so for 24 hours.
        impact: Cluster nodes more vulnerable to security exploits. Eventually, no disk space left.
      expr: |
        max(kured_reboot_required) != 0
      for: 24h
      labels:
        severity: warning