apiVersion: viaduct.ai/v1
kind: ksops
metadata:
  name: immich-secret-generator
  annotations:
    config.kubernetes.io/function: |
      exec:
        path: ksops
files:
- ./secrets/immich-postgres-user.yml
- ./secrets/immich-kiosk-api-key.yml
