apiVersion: v1
kind: Secret
metadata:
    name: backend-secrets
type: Opaque
data:
    SESSION_SECRET: ENC[AES256_GCM,data:H06bEw959D35RtM1N//2ea6bz6+a1sZz1aeB82KW/yM=,iv:fEbbeZMEWuvMi/+6bMfayuHIDM6YPcRrQaGO35OpSlE=,tag:hv4PM1pssEJ/rTa79mBvMg==,type:str]
    JWT_SECRET: ENC[AES256_GCM,data:BRv5rdrobOBbNHbsCXW6x9pq7Vf469Se6JbSvS1JVngERyBB2V9b8kKKXF+VCkXF,iv:NTvYJomxWeul+JfGJFAdxhuk5zfoEISnrYZJbN4a+rQ=,tag:rNvVmfnt9aDQ6AhYb/Ag6g==,type:str]
    JWT_EXPIRES_IN: ENC[AES256_GCM,data:U/EzbuQle/cYkpVT,iv:wu/sMTF/b1XQNMUF1tidzcpW5Z5FIxxfzv+YoBovm5Q=,tag:jbuZf60ZQTAVsU/sVMmGqw==,type:str]
    REDISCLOUD_URL: ENC[AES256_GCM,data:GiRaVxRbltmTrjWsloGhJO7MwPIalLvmBYG0Uw==,iv:nE+Fa5wzreEd1W6pcrO0aZiGYpC4WF1a0s2U07RAzlg=,tag:2jKcwLN41xVDTMQifKZbMg==,type:str]
    MONGODB_URI: ENC[AES256_GCM,data:uwqYDReOkSEbYPA+tvN//absxZwOEV2OOubWrP7Dt9Cfmrv/XweV7Kffu0K1I0rgYeYjfckHxxGX7zC9LMb2XylIYVaoudn/EoVfm33c9s/m6gWZQGLLIb+/DUKr0+hgbYdJM+WTty1foVT4gF/He71omH4=,iv:5/xb5KQz2v7wHILq/c+WlCIxhjDFxu6iM3VBjfWFY28=,tag:tGCAPVha1TGmK/EfvT05uw==,type:str]
    SQUARE_LOCATION_ID: ENC[AES256_GCM,data:H9B9qXbk9kj5q9JNBzrxQebr9AA=,iv:moawQeDUhfp1F84LYOzrAf3xsLBPUooLgPv8dU76NNE=,tag:hdPqcktwN4pcVz+4R6w7mA==,type:str]
    SQUARE_ACCESS_TOKEN: ENC[AES256_GCM,data:pyAkQXrVv7FDuyiJWS2+CXd8mldrnOlz2y+CYnmhOEGuIrl4d0mGkMnMUDO1bgZWr1AvisPqS4/uAVp77EMcsa9jH6Ejyi9OfhtWgBXD5ZKF9m16F5dgnA==,iv:d69FxzNJWaf9qHJ63MHaWv8miBmyxUtvcrOhb/YSk48=,tag:U545iieYRALiCQxEjpVXHw==,type:str]
    SQUARE_APPLICATION_ID: ENC[AES256_GCM,data:rjHYOIIxS/uZEOIxW0zG8j4H+cTl4r7B9O/73eESZwXZOi9TEBX3Jg==,iv:sqlNXHk8gyeHCr5n8BZ15tGNk+fkkHPrm98zxxlgUgs=,tag:VUXIkNo1QL/IOsyKU38iBQ==,type:str]
    SQUARE_SUPPORT_EMAIL: ENC[AES256_GCM,data:M93571KjpILUtPzAn4GpZ87JQZZcvZeM8Q8bdA==,iv:dlNDww/Tj3EGCoagnJOgM9ZFNPDsC2tibN8kKAGxl5E=,tag:EAz7G9O1Nwx/29YtfkOXTw==,type:str]
    GOOGLE_API_KEY: ENC[AES256_GCM,data:AHD9efr7N2T/swRxdy8Ln0Wl4NaqS3iTl9V+MdJ/UeKpyzqv/LyuDWES2rHyVY5OC/XfFthDMRA=,iv:3aOugiGblVqg1QbeOYkOesPxxEvMxsl40r/SZhIFyXs=,tag:IYhjQEsCINHmmTr8Nj6rgQ==,type:str]
    MAILGUN_API_KEY: ENC[AES256_GCM,data:Q03MP2RDqD3zs0VY/jCqktpUOTRg2LJJfBtuE1LG1so+jl6n0MlI8CllVwa631BGQA1zfA==,iv:nGKATiWTRIhySFGBh9AtCuNcG/2GSQwWN85A2okbNWw=,tag:Ac39cBccAAJmo9w9OezddA==,type:str]
    MAILGUN_DOMAIN: ENC[AES256_GCM,data:mqJPQ4hDufzFCiSyN2yDPCCrpGPfeiWrUN0hwW3gtojF2Ay8olWNhQ==,iv:sZ22z7TbaSrTMmtWUNpDRruHsjw+nc4Iu6eQ9eRXCos=,tag:FXJidq6RW3Urp/Ml3tK/0Q==,type:str]
    MAILGUN_SENDER: ENC[AES256_GCM,data:+Fl1KzBUR8MkQQ0GZpZTKCkgl1+mTAJdjXZM2ExyPdara8Wckct8W/mkk1u63cgt,iv:e9AziT4hUds0AlfJXJcOLCmR9okw0o2GQ5aObo8vY2Y=,tag:ePL9AY+5PbSCusCRDqCdLw==,type:str]
    AWS_URL: ENC[AES256_GCM,data:FqU08I97zPpC0hYjJKomW4ZDtdiBkNoOFPVWlw1HIBnI5Khkh3FCakjIsZh6VBZ1JD+j+kvCxPvN6+xZ04GuCqZ0YRo=,iv:vpWMLF0X8ik1V4yZHd3iTh6PBFpObxaYhgCWziGTChg=,tag:0ZIjijZF7j5mzz5iXWr7ug==,type:str]
    AWS_ACCESS_KEY_ID: ENC[AES256_GCM,data:OoqGWw90anxBRGEWlIK88iCR1i2eA8pvBDeJ4A==,iv:Erz+cwF21gjXwG6wAeouquCo8WkXQkhSM56TeGeY+Tw=,tag:kjpY7VZLloK3N5seYzfk7w==,type:str]
    AWS_SECRET_ACCESS_KEY: ENC[AES256_GCM,data:uyZ8pspR2P3Nk3Wvcdik6HCVXpFpZDK7qwh8isqZP1Zi98gXzAE2OMYEb3Ixen/752fiCU6hpLY=,iv:sIwnLRC5qD6pl2w6h79igvzsm7pvzZ257f5iYgeJwVQ=,tag:/pYf9AyXIowH0PAny+qjHg==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-04-20T16:22:36Z"
    mac: ENC[AES256_GCM,data:06PbyS2lZsKo7F6AUsKgbzrOR7LN6kOT20dVPnZzio5gtcI3U4Rq9MZxETZb7GlXVjORweUje2vh8m2vreqo9Kga1lTMr4mJWHz1VvceXRzQNLWh7cLMZcyXAoRn4qtCZ4VNDqYnPdOnI2ytG+hy9LzFUGCvMVW2VQqXGY6Phxw=,iv:7PH1NpKBhqALDp7TthYQxao/QSSEynaSXbo13HRan0s=,tag:bLginzfSP87b9JKJ2c9J9A==,type:str]
    pgp:
        - created_at: "2023-04-20T16:22:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQgArPMMIfG2iFF0gge9YZU7lHB+x9iVNt/LKFuAWZ+IbhLX
            WXmldc/yt0hzv7+EaWVCapDakih1v2kAFpRiECd3wHaZjb2mMNVjmaPp/w3Kur9F
            u58BY0bVhjr+ERRVcSYYZhSQLEcALm1wba7NZ6XWhs2rT5ieyUhKrGdBVhdN9kDY
            QLSNApdd2WLKMCMnWA3FavE3gMoorRrcCKU3NX+pxwsEpeGoOO9YoYJM5RXOrmfl
            GLTZfZlaMKhar6IpLdlkUWHNCiVH5R0tgR2qoUDxsHRWbBsIyD99QNqTkoD3Pg5k
            rfr0bq9ESqvmST4fWpLCh2xAxwZbLCstHbmeXmQCINJeAeb+2fgwlU0WJ2qGpd7G
            dzgvRPbzj8+ePvJiJb+Gu5QXzG6xWpu0Cn0+6O1q/JNYRotxM/I4y+3ZdsAblgjj
            TTmqqSyzmOmOyOFrimteVWTYv4RjErySr0EiuR/2hw==
            =BdJO
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2023-04-20T16:22:35Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9FFD9QOd3/Vgi2mAaoe+lpOThviEWAeT9I+0C/u/KDdFe
            TWNVKRjfEhHLLhPcIo4W18VRqqfpVnmZ46tbwAZA69QLIRzoOtsY5fbjydICvhCk
            H7IS53KyrIP+e2EFvMm+tbA3Pq/cra1x0eAciCDqxvMHBAUFmz8iu3LV37OvIKxz
            /N0FEjqUy7/kbzCrXP0cSGj9q5XGdfpFi8Vi8ea5iRV0ISshmVHRvU9IU50YqOvr
            WZWNYwfF/U+/KC4WdjL1THAb2QG2SIkY3R2mE1P46aS/QWJFeI/Cpg2MIrkLSaQS
            CBVIPVfPMRNbnG1wad81TQmU0+XVuBixxsg290nNItJeAcKLXz8EKYzUuARmvug2
            jYYISOv7nOucoyAmWAMQhqgKUY9L1K7EcnvN5HBkdidn3TawB31gVq37gF5rWbmw
            cIu+RN07N6aVS/BWnR+Mc2Lb0GwHyBI5awvAdscD4Q==
            =8/Yz
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.3
