apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:8f4jl8p9Zqm9FWoYvxjEEbKz9/YxQjroGexxr/WhO8vuJiYTd9cMn1QeJ97ky9bIpBw6NPZsFGJxwg/sTjIpu42TpqYhO5vqEGOymQ5lXKUDaJos7wAjp1ejjkhbrdm/IuuiRooVp/R/SKX/0YqMkF1qbwAc6kds5Opnecy8ShM227rHWWZWQStIQh2sCd3cUPpExyGUjoDhXmVdsatl4+3uOPOIRH8lgUPDXw2YDciluDVIv0cNT6D/iEkl3aR3Tj62zQizNGoWrhvG1fIfeJl7NjUb/3i7OR0SsULzjuuA+CRlvPLNI26FrLRMOXhGnZ70Q/jZAILvYOB4BIGHoMxwgo/F3Lv4HwvMh9ZftBO2DS7iJhw4C204AFEcO2OEMqomYu71wevr819MNe6jkxvWMeVThMwJplT4hRe56ybPE6TyQ+rpLK441mNKPk6QYPJ8F8Khv4ZXFFZbIcvXy85B38Xat4Cdpvuy6peeLFpIP/sYj76Tvwuqj+sL0hMxWXrHBafWu64dPdWrUnhd2ItyEJZ6a1GFOZeuA2BJfS4aaheOH0AwGsOLpW+4xpfFXUKV3zBdqs1Sg7DqbQ5hGqW5p3iqgy1aKJC+wRYqwM3Ie67OaqAyRA28tEch8h6TpU2JHpCBY2I4/i7sMdH9Qe+DtOEH5OVftjHNdRxwI0Da1APFm9E3c+mQGBVCgRhscsiMV6wx7Cwp6PDl4Clc9rwPtndYp4moV89XgwbROlwkVJ3CG2+rWCjX6n3jCNkmrvRJlU6OFegJOjIZmGJeCzHNa4rr8rZYpSqEoPyBxlL/D5V0wfgHFEgWl+sO2Wobzzg5gXfNsHAzpdqHjSi9Dkbey9rwG2Wir1koaAZ6+lBhifEKL9t95CNgUJTH0D3Q0co1J1ceGNqHncyf+aH8I+1VCyl0e4Dr7sV0jmZpBEKpW65zhj6hnmv9652xWNF7BWmp1Dky+l8EfSv3rxiPFS7qhIP/NKYFnRjwFzhHvh9TjX9ewB73wL5yam5Y8tr71JqFelpSoXaDcgMVD4Z0MBk59dL19UpKrPXCijxuz7CYKgfU/7p0jj/KEPE=,iv:MBknNiQ5sMe22rRx1tbgDrYG9lqC1MTKLzFkP4/ccYY=,tag:f4XR24H1MhzSspYKpfGvOQ==,type:str]
    tls.key: ENC[AES256_GCM,data:jFgQHytQpkkvqrM6h/5NxwIEgSnW8e/89lbWbOrQcy9ASUa6cTHsia/+yqoaNVkYAuZugOng6lZe4qzTeku9RuwUFnb2fJkkrODtcLUPS7g70VQmhiDEkmpKY0tR3RJelaxaHJo4+K5cc9BgaG785I5LzWXIVNKbeQJc0cK2Y8i+bRyBdm7YDyovPW2OS6hfkdBzOeW+F3cd2z18gtvF3Nw1xTL+gPgrQNOObm7W17ONr31+ob3uWpjrX0XwzqcBJ2yhk51iY5YRuEpyBaJmeH49OIF/ggKaFvQ+DeQvloS4IvuaN+Kmi8v1tyzCMN20MgNnvWm0XIxPXekByngwKxW4PMfhipXJ+32MCz3lDB9BoxRp67GogBbCRCv+R3pdZpQtEkA2yAipfySycTl0ww==,iv:KObbSX+45KDO7Va1AlhoGbxEx7vQ/AQWPYhLfRNHlOA=,tag:ao7pIzpfYuxYja0dcP8Vig==,type:str]
kind: Secret
metadata:
    name: webhook-issuer-tls
    namespace: linkerd
type: kubernetes.io/tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-27T03:35:02Z"
    mac: ENC[AES256_GCM,data:NqGIzSFYdRTlP1UQqMbPw9++dWgikiGQIxOYieaHIwKp2GuuDXDqKiCTJzAtCRd7o0i/OF4Hf7KP0QRWb3TjMlQ5wLupMKqgtmp4aLdhPk69aLMBGTj1C8ptwN7KtA9/mPFggcH2viFXnxE1w3rWpPaJbiF15ZgWLMfdjqxAo+E=,iv:vIcK8FRlM2Qw3du3Hw2PMH8LNSxT3djrPu9WTip9aWA=,tag:o8ciaCW8tN2FjpJPhOjHRQ==,type:str]
    pgp:
        - created_at: "2022-01-27T03:35:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQgAsjKowPvpTbGwhmE6gAvDCoOyR6n9w+A7uK0hj6eUEP/1
            Khi7Ao7J1r9VGkNSgspAQcCmXjFnG6CWeWs1ByUDrtx3z2lPRGCGXVbKpb0pQN8A
            gQJ3JknzaA84oF806MtpbWSBRN8IgNcney8mCSLHFxsY4DPSfhlqKqY1xVQgWzMr
            PuT4sD51BHgB9mTCFMydvKHUkvrrGV2aJTJxuQkIktcZ4A9buDxJG9oXDBsKSLrn
            D1lm6oNzA+YaYf6w9hpPitjP3ibCxudSleT5w+2yX/7U2owuPucW8FaFuf1haMQ2
            8cn/cIoGRhdpS/n98XUOz1NXPsJFDHwVHEkr+/pjidJeAdOfyifvZXfyV1vVOY+m
            jKuuB6ekYobMiMIkJkdNmsd1pFpSdUZcnJXNMLgp0AhfCKFLJyhA/knEo1NIsRGa
            GHONL9JAICAMMXBpXMs8PYSyq7asekXGRZ8vtZRYmg==
            =MixM
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2022-01-27T03:35:02Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAon9KHBGGJPvbbNRvdzcObd4FzFspnalENSxIGSn8Ib8o
            0/O6huEmo2MGFj+4FwJfOu2NDasWWR5W9JFAyMNIA9RS9NcwHqae6L0mOYa2Vd/F
            3AROUcv9vX6WxruA/fnxkOyHBROe0V1rKJWIQK077/UNpVd/xDFiWMwnRoaRxEVT
            82Un1r/Yx9aBaLB2K2uuWi8bosfnqNkLfx2bt2phrrhC94flYb/Yiu3cjTIwPvTi
            0aLq0s9TVjQYMfTm5M032mYtnT+Mf5NcAFYf5AUbmn5JHu615refDShYNs69tv4D
            S03N3V0Fux+8xYUIlGiXOD/GJeQatmzvtM0ICRUusdJeAcLS4EjUc6v9Z+gk3v6c
            CRMYv4TlLWyo33yXqAdTjxwiNPzVa4UP/mU1lYnoROeTLzzqggow+DJLhjxTJrXf
            tz3PRICRP6FnD+XWjwHPsGvKmTA4fc24zuAzIynxew==
            =eXHn
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
