apiVersion: v1
data:
    tls.crt: ENC[AES256_GCM,data:lR0Or58lXFCblbEK2wMlUY5x2cqdUKfCo/ajEuJKp+Yza16pan4473dMq23sWrzm4U92ymg1M555LUyXOXpo5UHEHXMrLfZZC+Dd8yOgPrJj+utbML7U8CJfJByPSnxO0i6AFCp/xaYWsTtyzvAtAI5O9kKURvodQHeVNWu0rXM0gvGSnYAXTooHdLWWRa1Iihm7SEINa47oyRsNO/Ad22a4/mnzJkXIddkzJwmAtENsZQT0lDJqpk7y7vu+0daszXTj4HTtmbmDsBV/qEeEyvG2SPb5MWVd/oCt/ifE7yr8SvnQdxKhrsFDz4LSlKD4bd8RZ2qXUGxiSG5SgXCZ768O+/e+uZpDJn+fYq1YIKBBQrlzGTeRQoS4QT+0T2wKk/oeEGg6tu1yHA9SPMCzSK1x3bWSIJH8h3Qgui9IvdjAQ3gzpnKPmyp9w9Vojou7hXohFgIOB/aTNIGHyRdwdatHxy9b3+q8+gtMH0oYEw/hhRmLtnGLm6pBLalHkcTDG33WtHh+JmpfKEjFfAbrTRTkzeFBlAXSz85sniVzy0Iu8hE1veKilyhpKQusDVMGsCSO4VhfMSSxRD+FX5M7mw6g9mkBWQn6lUhxKhpPbQ/lPiMKz9HF6WkiwkyYlXnTJ8mJPsAoj1MYdldVnZbibUfpCqeIeovVEK7i6OP2OYIqFrW+AuyUsQ1GD1hGT7pfd7m3LuZqdpiC4mNE6DoTcQmBuEnwGJI44zzk3N0XM7KnaemnHBu0AkGxPgbWdOELoED1DzZNWnZPogA8amBSRbwDSrwECMLKtZdr/qcGxscyosAiimlPer3W/hClWsCee7dc1GLlxc3Zscwh3X9iBxk5f9dHriUFDhEU1OGcufjwxGA9oY4snxeTfFkAlqrZhiYjo6jlupY17BlGj4jngVmWOAbGUcuN3GLgLe6P3Kq/+xr24Dcqh8AhMtbwBf3pWEsXVV9XKAvmSxcCQR3GA4brWckWa1L2zyGaAC9z68rNgecJd3PYDomFIU5CtHoCG88h08isGmizgfu5jKnGcwXajcUFoWttVRqcI/Q+2F05XsL8plXaW5sahFQ=,iv:ecgaYe4Djk8OycsRoEI6uYrP4QSXr9z+lkdqZD7BKgw=,tag:FN0JLmBi0kWJTgfWyUQ5aQ==,type:str]
    tls.key: ENC[AES256_GCM,data:KNv5d715ABB+1UCXpnMSLW6E3lQNyJRN69ZVPFSfJ/er90GdbFBX+lAaC0ImAMvAxaZsN1fnxHUaBGZdzEj9uyNVi4Ws0vhX8mAtQkw5reNw6HgRbQFQyovEIoWUY1gnX0BvsOBnUfaW0N3amwxN2WVN7JEcbHCEOCS0fjPGMVwuVSpuR0xp4kJxKeFBFlRi9PUaDwoOFM+sE4VCi6YGq25sth+i1aIg1DEJewjyApsYkAs+voHw28TDzXBfxfs48reMf217xesjaC1aHj+hl4liFpboTICDbsREU96Ra/UuI00bf0YS4gtApAnd0fh+wRja5kiqUuGwpoBaY/lJgS2XsNzaUP19SYpMjb8gqwMF37NG+Nn9kwMQxAaoEaUBkXmPEjtUqGVbUxKGr1wI8g==,iv:oaFkKXxxheB4VxUxzcXFKU/RaSucTQVc+H/JCiyqEOY=,tag:lAFnaSPYKzQ3rDrJW4BrEQ==,type:str]
kind: Secret
metadata:
    name: webhook-issuer-tls
    namespace: linkerd
type: kubernetes.io/tls
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2022-01-26T16:33:25Z"
    mac: ENC[AES256_GCM,data:gytq5ZvXnFyHXR/7K5AV6MdATDhzaDn+DFY4ZCevX2ZmpXmhmS84skjA2+q2x6cKPzi0TXi+hOdBFHtBdZc/7ksVgbcRMELaNWsgszuLTtUai1UNDXb8xMO6ETPoSuSgOBedms0oisqFw0qMoQ0el7K9nMFUdJT1FTfffCpw93Y=,iv:D7zUzEZR+seUNw4PSJ/3aJj3gqcfvsH5nDwDtV8XbzY=,tag:xyd/kFcTcvPrDbUmyHVylA==,type:str]
    pgp:
        - created_at: "2022-01-26T16:33:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMA8us4HTNu7pGAQf/c7zTsHFgPMdRPoD8M6bzQstTKvRkpR745DLaVZwIHuZ5
            6elSv4nKtSsDCuuGgh1TpmKufYWdxdTHkMYOD1EHbafbWmI6sU8j74eHcRcQ+Bch
            HvLIo6ZTjYBqALVtQ0Z962oN+cYETJRDeudZlROWQNVFD1DbmT1ogl9deH1aEgp8
            ILQexHc3zj0vYgr0QDWnMsEf5cS6tsOT2bw6pqiOrjR/h7JqTcgqTVL0sM9L1JTx
            m+gQ3Z2sqWAqFc387SbTL3YHRWY9EnZ2Nla9eQGyjOzKMDUQVPyc8E2GBGTMgZrb
            sgWLL00Mc2kfepaN0akPAFPTKrL3rKaCTNFfa/IOgNJeAXRgrT4rOkIXblt0Z14/
            3HidfhjmFS2FeBEer08m/yIgQ04pRus3tsKxWgljnBqYgI711gCcew8QnUyWD0ZI
            4m7uTPdJRD/ot9onkfX4qPHWVMVzOgoLnwuiHtGW/w==
            =rrxB
            -----END PGP MESSAGE-----
          fp: 1A37BCE8820939248F601E7F79BEF86F25A81443
        - created_at: "2022-01-26T16:33:25Z"
          enc: |
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAsMCutuXMX5nd6OJxIzpMPQnlnGdjTFlaSx1VhYytT/5x
            C/OZqEorrKjL5D4BzXrowxLkRGUwfYYi+jWV2qE+ltJH5hPU7Ywz7WYvO7j4k3vK
            U0CrJNp4VxYnqhLpbMULMoVPJbm1kHIiiLwnGIivQfXej1y4peYZAFQzyzRvSaRW
            4sz92XbCwKktFqRIV+rDaXJRIO9cSBhI7Q/n+BnM/KsD38XJ8F2vph7dYK8GowAO
            Qp/B/SBsjb3qcNMpkcF0igvm28uOidULSmfnX+y7cioR5e39kw3kRvFlbSmpWe87
            ug877JWoWLl+hc/5XmLYTX5DgLEX6oMzeIMTeo2IvtJeAY51aJvBQ4xco+qVdaHk
            EjdwMqDfJqnx8vAmnZXtTPNcMSwLIOavsBzZCzd2IJ0XgHdNMD0L3i8IT3m9bafz
            sPx8yZFbc1zNEsAaeDgs+h4ew2bbmsKqhk2hZ7vMNQ==
            =ggsI
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData)$
    version: 3.7.0
