apiVersion: apps/v1
kind: Deployment
metadata:
  name: wireguard
spec:
  replicas: 1
  template:
    spec:
      containers:
      - name: wireguard
        image: linuxserver/wireguard
        envFrom:
        - configMapRef:
            name: wireguard-config
        securityContext:
          capabilities:
            add:
            - NET_ADMIN
            - SYS_MODULE
          privileged: true
        volumeMounts:
        - name: wg-config
          mountPath: /config
        - name: host-volumes
          mountPath: /lib/modules
        ports:
        - containerPort: 51820
          protocol: UDP
        resources:
          limits:
            memory: 128Mi
            cpu: 200m
          requests:
            memory: 64Mi
            cpu: 100m
      volumes:
      - name: wg-config
        persistentVolumeClaim:
          claimName: pv-claim-wireguard 
      - name: host-volumes
        hostPath:
          path: /lib/modules
          type: Directory