apiVersion: gateway.envoyproxy.io/v1alpha1
kind: BackendTrafficPolicy
metadata:
  name: paperless-auth-redirect
  namespace: paperless
spec:
  targetRefs:
  - group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: paperless
  responseOverride:
  - match:
      statusCodes:
      - type: Value
        value: 302
    redirect:
      scheme: https
      hostname: auth.k8s.cguertin.dev
      path:
        type: ReplaceFullPath
        replaceFullPath: /oauth2/start?rd=https://classeur.cguertin.dev/
      statusCode: 302
