@startuml infra architecture

cloud Internet

cloud LAN {
	
	node Modem
	node Router
	node LoadBalancer
	storage NAS
	storage Ceph

	cloud cluster as "Kubernetes Cluster  \n   192.168.0.0/24"

	node ControlPlane {
		node mediaserver
    	node nvidiaserver
    	node miniitx0

		database etcd
	}

	node DataPlane {
		node worker1
		node worker2
		node worker3
		node worker4
		node worker5
		node worker6
		node worker7
		node worker8
	}

	nvidiaserver -u-> etcd
	mediaserver -u-> etcd
	miniitx0 -u-> etcd

	cluster -d-> ControlPlane
	ControlPlane -d-> Ceph
	DataPlane -d-> NAS

	mediaserver <-d-> worker1
	mediaserver <-d-> worker2
	mediaserver <-d-> worker3
	mediaserver <-d-> worker4
	mediaserver <-d-> worker5
	mediaserver <-d-> worker6
	mediaserver <-d-> worker7
	mediaserver <-d-> worker8
	
	nvidiaserver <-d-> worker1
	nvidiaserver <-d-> worker2
	nvidiaserver <-d-> worker3
	nvidiaserver <-d-> worker4
	nvidiaserver <-d-> worker5
	nvidiaserver <-d-> worker6
	nvidiaserver <-d-> worker7
	nvidiaserver <-d-> worker8

	miniitx0 <-d-> worker1
	miniitx0 <-d-> worker2
	miniitx0 <-d-> worker3
	miniitx0 <-d-> worker4
	miniitx0 <-d-> worker5
	miniitx0 <-d-> worker6
	miniitx0 <-d-> worker7
	miniitx0 <-d-> worker8

}

Internet -r-> Modem : HTTP request
Modem -r-> Router : Forward request
Router -r-> LoadBalancer : Forward request
LoadBalancer -d-> cluster : Forward request

@enduml
