apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: whisper-storage
  labels:
    app.kubernetes.io/name: whisper
    velero.io/exclude-from-backup: "true"
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: v1
kind: Service
metadata:
  name: whisper
  labels:
    app.kubernetes.io/name: whisper
spec:
  selector:
    app.kubernetes.io/name: whisper
  type: NodePort
  ports:
  - name: whisper
    protocol: TCP
    port: 10300
    targetPort: 10300
    nodePort: 30300
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: whisper
  labels: 
    app.kubernetes.io/name: whisper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: whisper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: whisper
    spec:
      runtimeClassName: nvidia # Note: SUPER IMPORTANT
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/hostname
                  operator: In
                  values:
                    - nvidiaserver
      containers:
      - name: whisper
        image: lscr.io/linuxserver/faster-whisper
        envFrom:
        - configMapRef:
            name: whisper-config
        resources:
          limits:
            nvidia.com/gpu: 1 # Request 1 GPU
        ports:
        - containerPort: 10300
          name: whisper
        volumeMounts:
        - name: whisper-storage
          mountPath: /config
      volumes:
      - name: whisper-storage
        persistentVolumeClaim:
          claimName: whisper-storage
      restartPolicy: Always
