apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: piper-storage
  labels:
    app.kubernetes.io/name: piper
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: v1
kind: Service
metadata:
  name: piper
  labels:
    app.kubernetes.io/name: piper
spec:
  selector:
    app.kubernetes.io/name: piper
  type: NodePort
  ports:
  - name: piper
    protocol: TCP
    port: 10200
    targetPort: 10200
    nodePort: 30200
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: piper
  labels: 
    app.kubernetes.io/name: piper
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: piper
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app.kubernetes.io/name: piper
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
                - key: kubernetes.io/arch
                  operator: In
                  values:
                    - amd64
      containers:
      - name: piper
        image: lscr.io/linuxserver/piper
        envFrom:
        - configMapRef:
            name: piper-config
        resources: {}
        ports:
        - containerPort: 10200
          name: piper
        volumeMounts:
        - name: piper-storage
          mountPath: /config
      volumes:
      - name: piper-storage
        persistentVolumeClaim:
          claimName: piper-storage
      restartPolicy: Always