apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: linkerd-viz
name: linkerd-viz
repo: https://helm.linkerd.io/stable
version: v2.11.1
releaseName: linkerd-viz
releaseNamespace: linkerd
includeCRDs: true
valuesInline:
  grafana:
    enabled: false
  prometheus:
    enabled: false
  dashboard:
    enforcedHostRegexp: ^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|mesh\.k8s\.cguertin\.dev|\[::1\])(:\d+)?$
  installNamespace: false
  identity:
    issuer:
      scheme: kubernetes.io/tls