apiVersion: builtin
kind: HelmChartInflationGenerator
metadata:
  name: linkerd-viz
name: linkerd-viz
repo: https://helm.linkerd.io/stable
version: v2.11.1
releaseName: linkerd-viz
releaseNamespace: linkerd
includeCRDs: true
valuesInline:
  grafana:
    enabled: false
  prometheus:
    enabled: true # To easily collect metrics with federation
  prometheusUrl: http://prometheus-k8s.monitoring.svc.cluster.local:9090
  grafanaUrl: https://monitoring.k8s.cguertin.dev
  dashboard:
    enforcedHostRegexp: ^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|mesh\.k8s\.cguertin\.dev|\[::1\])(:\d+)?$
  installNamespace: false
  identity:
    issuer:
      scheme: kubernetes.io/tls