grafana:
  enabled: false
prometheus:
  enabled: false
grafanaUrl: https://monitoring.k8s.cguertin.dev
prometheusUrl: http://prometheus-k8s.monitoring.svc.cluster.local:9090
installNamespace: false
identity:
  issuer:
    scheme: kubernetes.io/tls

## HA configuration
# 
# The following values contain the values needed to enable HA mode.
enablePodAntiAffinity: true
resources: &ha_resources
  cpu: &ha_resources_cpu
    limit: ""
    request: 100m
  memory:
    limit: 250Mi
    request: 50Mi

# tap configuration
tap:
  replicas: 3
  resources: *ha_resources

# web configuration
dashboard:
  enforcedHostRegexp: ^(localhost|127\.0\.0\.1|web\.linkerd-viz\.svc\.cluster\.local|web\.linkerd-viz\.svc|mesh\.k8s\.cguertin\.dev|\[::1\])(:\d+)?$
  resources: *ha_resources