apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:e3GNP0JOGaT6TA==,iv:Tw0hOM+yZTJXz+RAOjUadotxCblUD9lJUIBPB/Dc00s=,tag:3ChVPIwDalv0UwnTQS+cXw==,type:str]
type: Opaque
stringData:
    PLEX_CLAIM: ENC[AES256_GCM,data:dA6n8AIow3XWKsk5f8HjTMZWtKciDwXZpl0=,iv:PzjTLeFpRSxsQL3aVa3X7f/kGNSRc++o5CXa9irSblI=,tag:agzU17ZaGtO2t0gkzJxV/w==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2024-01-07T04:36:16Z"
    mac: ENC[AES256_GCM,data:/nhEruorNG94qAx5vRXOs3lFYVoJRHJCX/dVznoLFRsie2NJPxSoTpkgxA1Ma/URChVamSGTxoZqkvD5AzmJTt+L4C1wp0nqfzxlq9nJqdalB1fM/ATcyh6BxTKUGjDXuLXQWL19UOpr+Qs/bFspSaWkKBLGUjP4Lu8Bl8Oum4U=,iv:aaMYLjYtEqpHbPv93SVSzqVD9Tp29hRrxg8Lma6T8BY=,tag:nkZaLZfaYUu6V9FhLxDPrA==,type:str]
    pgp:
        - created_at: "2024-01-07T04:36:16Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAo3u/UPw8mZ3vf2ZEluo2CyZuszonLcjisKP0+8DMQhYc
            sCzavK8zv/Vl4IPE6IWvT0lQhsrWmNJNxOkzDmTUTBV2WbFiu4fMzbQnGjU8+8cN
            NKtdG6KFFo6qSG+7FAVgJE2A1BQywVFMpget4CPIKjyc3Z3Mmgam/ka4QrVBiXJ0
            s6sGoCkuIFFVGXLIlGRQb5uM1plfFTJk7o0JG/p7UmWzDlQqdxyigW8gKdEufHg7
            +Li1/W/rrn1lZ/s0JP0xsGgbvM8Qk2nQV4FEBe8yTMwX9KtmPDOjlLjvuIZyhtW7
            qvM8gUfXWyRDl963RX7CtSVHndHlzIjScRBx6BXCsNJeASNFzdfyiECv3p6+EM8L
            WWI/hjRqZIzwRXqb95786esSfJcM3a2lgqetDBdmQh7JGoQ39IWxJdW3LXRm6Jwb
            w+ibgeFuqp1VtthhhBJKBYxAFRhzE9j6dxH0OXZo5Q==
            =af8I
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.8.0-rc.1
