- op: replace
  path: /spec/template/spec/containers/0/args
  value:
    - "--global.checknewversion"
    - "--entryPoints.traefik.address=:9000/tcp"
    - "--entryPoints.web.address=:8000/tcp"
    - "--entrypoints.web.http.redirections.entryPoint.to=:443"
    - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
    - "--entryPoints.websecure.address=:8443/tcp"
    - "--api.dashboard=true"
    - "--api.insecure=true"
    - "--metrics.prometheus=true"
    - "--metrics.prometheus.buckets=0.100000, 0.300000, 0.500000, 0.700000, 1.200000, 5.000000"
    - "--ping=true"
    - "--providers.kubernetescrd"
    - "--providers.kubernetesingress"