apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-storage-adjustable
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 500Gi
