apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: immich-photos-storage
  annotations:
    velero.io/csi-volumesnapshot-class: "ceph-block"
spec:
  storageClassName: ceph-block
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 2Ti