apiVersion: apps/v1
kind: Deployment
metadata:
  name: immich-kiosk
spec:
  replicas: 1
  selector:
    matchLabels:
      app: immich-kiosk
  template:
    metadata:
      labels:
        app: immich-kiosk
    spec:
      containers:
      - name: immich-kiosk
        image: ghcr.io/damongolding/immich-kiosk
        ports:
        - containerPort: 3000
        env:
        - name: LANG
          value: fr_CA
        - name: TZ
          value: America/Toronto
        - name: KIOSK_IMMICH_URL
          value: http://immich-server:2283
        - name: KIOSK_IMMICH_API_KEY
          valueFrom:
            secretKeyRef:
              name: immich-kiosk-api-key
              key: api-key
        - name: KIOSK_SHOW_IMAGE_EXIF
          value: "true"
        - name: KIOSK_SHOW_IMAGE_CAMERA
          value: "true"
        - name: KIOSK_SHOW_IMAGE_DATE
          value: "true"
        - name: KIOSK_SHOW_IMAGE_TIME
          value: "true"
        - name: KIOSK_SHOW_IMAGE_LOCATION
          value: "true"
        - name: KIOSK_SHOW_PROGRESS_BAR
          value: "true"
        - name: KIOSK_TRANSITION
          value: cross-fade
        - name: KIOSK_ALBUMS
          value: "4be7397b-09bc-426a-a3ea-9617006f05ed" # Current theme: Winter
        - name: KIOSK_SHOW_ALBUM_NAME
          value: "true"
        resources:
          requests:
            cpu: 50m
            memory: 256Mi
          limits:
            memory: 256Mi
        livenessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 30
          timeoutSeconds: 5
          failureThreshold: 3
        readinessProbe:
          httpGet:
            path: /
            port: 3000
          periodSeconds: 10
          timeoutSeconds: 5
          failureThreshold: 3
