apiVersion: apps/v1
kind: Deployment
metadata:
  name: traefik
spec:
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
    type: RollingUpdate
  template: 
    spec:
      containers:
      - name: traefik
        args:
          - "--api.dashboard=true"
          - "--global.checknewversion"
          - "--entryPoints.traefik.address=:9000/tcp"
          - "--entryPoints.web.address=:8000/tcp"
          - "--entrypoints.web.http.redirections.entryPoint.to=:443"
          - "--entrypoints.web.http.redirections.entryPoint.scheme=https"
          - "--entryPoints.websecure.address=:8443/tcp"
          - "--metrics.prometheus=true"
          - "--ping=true"
          - "--providers.kubernetescrd"
          - "--providers.kubernetesingress"
      - image: thomseddon/traefik-forward-auth
        name: traefik-forward-auth
        ports:
        - containerPort: 4181
          protocol: TCP
        envFrom:
        - secretRef:
            name: traefik-forward-auth-secrets
        env:
        - name: CONFIG
          value: "/config"
        volumeMounts:
        - name: traefik-forward-auth-config
          mountPath: /config
          subPath: traefik-forward-auth.ini
      volumes:
        - name: traefik-forward-auth-config
          configMap:
            name: traefik-forward-auth-config
        - name: traefik-forward-auth-secrets
          secret:
            secretName: traefik-forward-auth-secrets
        - name: traefik-data
          emptyDir: {}
        - name: tmp
          emptyDir: {}
      securityContext:
        fsGroup: 65532