apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: metrics-server

helmCharts:
- name: metrics-server
  releaseName: metrics-server
  version: 3.13.0
  repo: https://kubernetes-sigs.github.io/metrics-server/
  namespace: kube-system
  valuesInline:
    replicas: 3 # HA
    apiService:
      create: false # handled by ../monitoring/overlays/prod/patches/apiservice-metrics-server.yml
