apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: kube-system

commonLabels:
  app.kubernetes.io/name: metrics-server

helmCharts:
- name: metrics-server
  releaseName: metrics-server
  version: 3.9.0
  repo: https://kubernetes-sigs.github.io/metrics-server/
  namespace: kube-system
