apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:5gBabLr4CD/D6Z9NYAZnPijR/CANsu4wqA9M,iv:lIGDL3A1xiumpxrleQHs1yAESMAsrdTwR5X15Fp4X8Q=,tag:3Q6bBnTmwkw1GuGkQp568w==,type:str]
    annotations:
        kustomize.config.k8s.io/behavior: merge
type: Opaque
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:nIy4w+mmsM5bmiIRQhaIT1146xNqqkUTd/taHFN4lTuI2UKDQfM8BLEeKa5qNPT4Hhrkt8CTpKu9XcizaIQ04SNE+pbdr4hxLFt7KK5fXvcF,iv:/hgVx6cFNF/smYvPSfgAbG4BV6Rgq6GjjCZp3IkUmh0=,tag:WgL+XJRz7C/95wHQfcUWlw==,type:str]
sops:
    lastmodified: "2026-04-05T23:13:05Z"
    mac: ENC[AES256_GCM,data:lBOGxlhLHBEYSHBdZ6/Lh6aE4kV+FqyTLS8ClAojtq0F+UKbJphQeL+z7HjJia825cqGjatlcBYWmfvyjyd4Yik2uF9QYVg3MW/JgwJ2RfgUBNUG7YxDKQAwPGd7ISi7uJkMM5FjJQt+RLnQTyhTI70520oyxwoLbS1iRkIlHyc=,iv:yuaudEFuxRPIky0BtcLZAQ1AN5jVrMzENFhGon3Pp7E=,tag:sm4dxqA9VoL0hItD6QeDaA==,type:str]
    pgp:
        - created_at: "2026-04-05T23:13:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQgAmSVBcDA1NqCmbYxPwGwG9DW76EqTAPq8RFFEupKyf6ni
            wTfspDoh20E+ePT5QHJ6fDVlfKCA44Ffro8wPSjRANIrDAATqaKXTT0fLfsExk60
            4Mubx9DPTeU3ZYYHpeLRx2bs0rJF7Pkyb9oMh/NvAZfj1q15pwDjhTEGG011sRX0
            0RrUdEhAnCLO65WwX9WFsKKQsIDflKJEHZe9gk/jOI3Ejoz+NfrlfaWdC6BgrfST
            QHDo2Dh2LKa9XLNu+cWJzdZ7cQ1NJGllS2vUtqJZZyuHNLZHJe9gs+Gx75RkdwfI
            +RAool2HQ/GxGT3lSPjWfsGavvgzMwyCNJwLZeEpzNJeAcTI46HK7R4pqoHWiJsd
            xW7pStm0P8y5BS+xt39luL6taqIZf/DGCNXuxrX7hxVUr0MLpR/pFofm5+gk1l5D
            fFfxgQ48HJLDMeFNXKI+KeJueBPktmD9UB0+NyY5ww==
            =BvJW
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-04-05T23:13:05Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQwAvH8FhBcwaPitD1LZwykmJG7urxRYf3wxZ9PlR8k4S1KV
            kaGNIJi/aO4jrZdHFDsZJG7B2pQzP9nzdoUuVOVW9hrP6O4f/Vnurfj8maxse9/5
            mjasuMHj6jTnCdwY5s/vge0QG17XAkSZ+w8uEjVjM8JvMdvqFgd68Jtnp8te5eId
            dKwHAB7WMVc2cnh/Zc7cRaGJ4J8urBS71JUD7paSB2nZcQ9mS63cvEKq0ta89M7a
            mep4hEolqmqOEGfpb+3a5gSyxGMMisjmweJHztz/CLi189EFTIvPWpX3/FIBIMtg
            OCrVeqzNXHz7uyMBc4l0tSmmrr5RM+UrEYPjspVTyMNbYMsvC+xbEYtNL0/rZpxw
            R3zlmwwkvFBO9uJsDHUfpu1sf+2779byZdNEzmf1grIKYtVayrb3qjnSuJZcyQd9
            mKyt1cRIqYTu76wQs1scqMHfEj0fwAKpThJRwvtDwVk/J+G+gdSsFxQQOGCa8CUs
            3HBSC0m6mHSpdAL1fYRY0l4BxarfJDg459/5XsAqQBhlpMEgxqaZDGRNDHvpIcop
            QecTQfCWm3hPF3dEw6sjaLink+/pK1u0AIS09obTMR5dZREdY1MQnrR639T2zuen
            pK4wvpDJpzTuam0vZiKN
            =Qh9s
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
