apiVersion: v1
kind: Secret
metadata:
    name: ENC[AES256_GCM,data:FX7P1F5wG/Q+1LvOSP5wep6rntHB1digeUzI,iv:jICPlz6/f/sDwVf8kH+8l/hO1qArnEYnmFSup51FV6Y=,tag:KMR5DBdkTs4Oq6BKNMINiQ==,type:str]
type: Opaque
stringData:
    slack-webhook-url: ENC[AES256_GCM,data:XffDPxwtFXQBpfSVswMPrQjqx/3n/oP+71j67uhLtGMoV9upRn6/kd3KP3Ue/sRr/nFuu0gumcTnfR+MRRBqDEkl8/1YndGOuRqvfs6yFHaa,iv:sLbPCaD2/GAC3sgv+gL/948jRmlmz24K4mFrTz1SJyo=,tag:KOeR1CtbUd1jEHqnwICpFg==,type:str]
sops:
    lastmodified: "2026-04-05T23:08:55Z"
    mac: ENC[AES256_GCM,data:qzK6jbHhdEClcBexd7YfNptHfhb8d2QVHcEiXCizRHhkwpfUZJ2JPn6EIkm9xp2aKugXPFy8Gf8QaOfsruQSyF6yWxbuIHGsGXORZa0yGHDIqFzqFk3ra2xDxFirm27ntreERb5DiFNtcjfyaVuoFujf75X6heVxVOD0o8fcqp4=,iv:H+x+nlQQ6rU8qpJoI/e8oPn/P1qm//iCJCTJuLKWO/k=,tag:WykGctQJ/jtQLGRqE857iA==,type:str]
    pgp:
        - created_at: "2026-04-05T23:08:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMAz1lFUBZqj6mAQf9Hz7YuzX7yTnl9sVylLtw0urYUoS2d9b4kjvkQamfkQuu
            oxMaDkCCZI//CXWzNrCc/cRqN48KDXvgPrb64yieKe3+isF/76Nj1JnTD89yDtOv
            Z3Rvuq9SOYh9hrChWysBev4dg+Q105wKlJXh31FLGOnx0ySSpw0FS2mJG+MtKmaH
            QCQHpP9o6GPUNFfTTViMIOiv6KIjknx3C+4G5q4N4BmXdZB0uWYJ9MJN+pGdyvcy
            luMcIZbtYzoiNUBb1URiMd4SRK3iK/t3jT+ICWpfD+z5QRhhLC7EqdQ2QTSzJCvv
            FVRU0rq6wFFZXMwpC2qtqtlDc+n0SUOOlA61oOwcjNJeAdi5ECh+FXLdjV4xVjti
            8G5wxwhm7ZgvBGyk7Br3YG6WkVXKIptF8YxdnvW36R7m8fpKSMltXVgrtp5eYVA7
            fc8vQPKS/qZ46ff3AePRy2zaopY5T+oeHjhFj0wU4w==
            =aWNE
            -----END PGP MESSAGE-----
          fp: FB43BB6AE3C36AD515570A4FD7A77BD6F799A804
        - created_at: "2026-04-05T23:08:55Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQGMAxrKRq88dumKAQwAhyJozop3/MPA6zpTJU2622qmzp7fjw86Uz0TOCK6wWFa
            HjRZXZhb4TqOzl3sr79NrA4pLZ5wERCg9Hz8fL8dqEsLltatxUvXpBm1fpzUxKSj
            iF8tJG8Bwizwmac9aA4vUEzhQbsTm57AkkTR0ISGLUplo/PPJO7JZs592p/p6W7h
            fbcrwFaMgRF0l4XtHsh3YvzMWBiGtkE+ZvEqgjruEwAN5BoI5qwGyNehnnPrcBAJ
            rojrqgxIrzM2zGHGOlizofC80xxF/R4Kfwyj1S5Si1ew4s0/Lr/yM0zXkMYIqjAD
            zXO3hva3wmWMb/J3a/0s1FTVq8PMyeN8ryA7KZTLLWrtRK81ronVoVf1ylAhmi5y
            fcCU65OacV2RJ8pQegoaJ/C7POkbIrzIsXfqeeA3GWouxU69ng81K5f0EPyj2RNC
            rufnHKWUd/gHxp73Q9Eb56GU4wOo/F02K8ZhIAyLBpfKTtRYhiCKNM671FSTUenp
            gDJn7JlsUmJf/9FLatYG0l4BXylUPwUDequ3yA9GXz1MGugZt1BrTER+pbQaap4K
            8cb8i3Gx6uw9WlVdnzb4SgsFgVixz1mUfSvxKnvYjUgx9jEze2VF0PkJdDjjgb+h
            KJoQUie/N0CK5105iJu/
            =sxSA
            -----END PGP MESSAGE-----
          fp: 00147B487D93E97077A21F898C32FAF457DC2C54
    encrypted_regex: ^(data|stringData|name|db)$
    version: 3.11.0
